### ISSUE TITLE
Editor fails to launch if the user prefs file is corrupted

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1457] opened 2021-11-27 17:22 UTC
**Problem**

This has been reported few times already (e.g. [forum thread](https://www.adventuregamestudio.co.uk/forums/index.php?topic=59358.0)), but if the preferences file gets corrupted for whatever reason Editor refuses to start, displaying "unhandled exception".

**Expected behavior**

Leaving the corruption problem aside, there has to be a way to launch the program even if the prefs cannot be loaded, using defaults.

**To reproduce**

1. Open current preferences file (should be in `%USERPROFILE%\AppData\Local\AGS\AGSEditor.exe_StrongName_mqpdv5kqypl2dezfmjnjxse4zvfvse2h\<VERSION NUMBER>\user.config`) with a text editor.
2. Put random garbage inside and save.
3. Try launching AGS Editor. Observe the exception.

**Comment by ivan-mogilko** [comment] 2022-01-02 02:03
@morganwillcock I'd like to ask you, since you wrote the new preferences.

From what I gather, the AppSettings class retrieves the values by calling base SettingsBase class members directly in its properties (RecentGames, etc); there's no explicit "load settings now" method.
This means that the first file read may occur anytime, whenever someone is getting any of the AppSettings property values. If one would like to catch xml parse or other exceptions there, then they would have to add try/catch inside each property's getter.

May it be a better solution to instead have an explicit "Load" method that loads settings on start and creates all the necessary lists etc with either read values, or empty values in case load failed in the base class? Or does this class assume that reading may be repeated (not sure if it's the case with the Editor)?

**Comment by morganwillcock** [comment] 2022-01-02 18:14
In terms of XML parsing surely there is no difference between reading one value and reading them all when the problem is that XML file has been corrupted? If there was a graceful way to handle the XML error that would be good but I don't think any of the default settings or storage classes will give the opportunity for the error to be handled, so any attempt to improve the error recovery will probably mean partially replacing the underling storage and data classes.

Given that the Editor is not designed to recover its state to re-sync with a data reset there is likely only place that an error check could be safely made at the moment, that is before the AGSEditor class creates the settings instance:

```c#
private AppSettings _applicationSettings = new AppSettings();
```

Settings are read as part of construction of this instance but the XML file shouldn't have been touched before this point, effectively this is 'load all' because the XML file will get parsed. If something was going to make a rudimentary test that the config file content was valid XML the path should be available as `ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal).FilePath` and the file could be deleted if XML parsing failed. This should allow the Editor to start as normal,

Alternatively, maybe wrap the construction itself in a try/except block with an additional attempt after recovery actions. The file path does seem to be part of the exception information or it could be looked up as above. Or just give instructions on which file to remove as the error message.

Alternatively, if it is deemed the built-in .NET system for storing application settings is not reliable or recoverable enough it is probably best to plan on moving to using something else. Does anyone have any suggestions? It is unclear from the report whether this is affecting multiple users without any external factors or just affects users with underlying hardware or power problems. I've tested this a lot in the past and I've never seen file corruption, I have seen it where someone's hard drive was clearly failing and if that person reports it 5 times I wouldn't count that as 5 instances of a problem.

**Comment by ivan-mogilko** [comment] 2022-01-03 02:47
Right now I'm interested in applying a hotfix. Unlike layout screwup when the editor at least starts, any mistake in preferences file locks it at the splash screen; which is not good. So I'd like to at least let it into the editor itself, even if at the cost of loosing preferences.

> In terms of XML parsing surely there is no difference between reading one value and reading them all when the problem is that XML file has been corrupted?

Hm, I think there is; depending on how much is corrupted (whole file, or certain values have invalid format), and whether XML is parsed awhole or read to the minimal required extent - in the latter case many nodes will be skipped.

Anyway, I will try one of your above suggestions and see how it works out.

**Comment by ivan-mogilko** [comment] 2022-01-03 07:59
So, I found this quite an old page, which uses `ConfigurationManager.OpenExeConfiguration` to test config for corruption:
https://www.codeproject.com/Articles/30216/Handling-Corrupt-user-config-Settings

The code snippet works with minimal updates & fixes.

**Comment by ivan-mogilko** [comment] 2022-01-03 09:04
Opened PR: #1476

> Alternatively, if it is deemed the built-in .NET system for storing application settings is not reliable or recoverable enough it is probably best to plan on moving to using something else. Does anyone have any suggestions?

Tbh I cannot say much about this now. I don't think it's specifically bad how it's stored, except the generated folder names are weird. It could be that Editor does not use this Settings class correctly enough. Personally I'm used to a deterministic config loading when you control exactly when it happens, but currently it's hard to tell whether it may or not reload a file in the middle of the work. Maybe if it was coded slightly differently, potential problems could be avoided.

PS. on a side note, I noticed that it's being saved on multiple occasions too. For example, for some reason it is saved every time the Color Themes list is opened; maybe it's an unintended side effect, but it defeats the purpose of the "Cancel" button in Preferences dialog.

**Closed** 2022-01-04 18:45 UTC
Labels: type: bug, what: editor
