### ISSUE TITLE
No music running 2.56 game with 3.5.0.21 engine

### ISSUE THREAD

**Issue by necros2k7** [adventuregamestudio/ags#1006] opened 2019-12-12 09:53 UTC
**Describe the bug**
No music running 2.56 game with 3.5.0.21 engine

**AGS Version**
3.5.0.21

**Game**
Hit the freak
[git.tar.gz](https://github.com/adventuregamestudio/ags/files/3955030/git.tar.gz)

**To [Reproduce**]
Start game

**Expected behavior**
Music and sound

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Win 10
 - Version 1903

**Comment by ivan-mogilko** [comment] 2019-12-21 19:10
So, this is a curious situation. The game uses old-style audio system (pre-3.2.0), but does not have a "music.vox", and has the music & sound files lying in the game dir instead.

At the moment engine has following procedure when mapping old style music&sound to run in the new system: when the game begins it searches for the files of certain pattern in the main game file and *music.vox*, and registers everything found. But *it does no search in the game directory*.

The obvious solution here would be to add search in the directory as well.


There's something less important to note though: files may be placed into a directory during game run, and the old ags engines would probably find them even if they are placed later. New engine won't do that unless search is performed each time script starts a new sound. Maybe this is not necessary at the moment, and may be considered an unintended behavior of an old engine.

**Comment by ivan-mogilko** [comment] 2019-12-22 13:29
@necros2k7 I pushed a fix to the current master: 500808b104f4023750a6b8a9fc0db5e5516ef451

**Comment by ivan-mogilko** [comment] 2020-01-08 09:02
Should be fixed in master now.

**Closed by ivan-mogilko** 2020-01-08 09:02 UTC
Labels: context: bw-compat, type: bug
