### ISSUE TITLE
AGS4: Dismantle Game Explorer, add a build number that is auto incremented

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1266] opened 2021-04-27 06:38 UTC
(1) As far as I know, the Windows Game Explorer was invented for Windows Vista and really pushed in Windows 7. However, it dropped out of favour afterwards and was normally hidden in Windows 8.1. Now it has gone for good: Ever since version 1809 of Windows 10 came out, it isn't even hiddenly available any more. 

This means that the "Windows Game Explorer" functionality in AGS is losing its usefulness. Even when the Game Explorer integration is switched on in General Settings, the number of Windows boxes that can actually do something with it will be rapidly decreasing.

Even if it was not going away, the "Windows Game Explorer" nowadays is a special case, in parallel to Valve, GOG, Epic integration etc. From the vantage point of high-level design, it would be much better to transfer the code to a module.

So I'd like to suggest dismantling the functionality in AGS4.

However, some fields in that section would still be universally useful – if there was a way within the games to access them from code, e.g., in order to show them on a title screen. We'd have to discuss which fields specifically are worthy to keep. The following might be eligible (ordered by the way they are listed in General Settings/Windows Game Explorer):
- Developer website
- Game Description
- Release Date
- Version

I'd like to suggest either moving these fields to the top of the General Settings window, under "(Basic properties)", or else choosing a more universal name for the category "Windows Game Explorer". All the fields that we do keep should be available to the code, e.g., as subfields of `Game`.

----

(2) Currently, if you want to keep track of the builds of a game, you need to do it by hand. You define, e.g., a global variable and then have to remember infallibly to increment it each time yourself whenever you compile or at least whenever you publish. This is __very__ error prone. Forget it only once and you will be forced to distinguish your game versions by file size or some such.

So I'd like to suggest - in addition to the "version" field - a __new__ integer field to General Settings named, e.g., "build number". This field should be settable per hand within the Editor but the editor would see to it that it is incremented whenever a compilation is triggered. It should be available to code. 

The difference to the "version" field would be that "version" is a free-form string and left alone whereas "build number" is a non-negative integer that is auto incremented by the Editor.

**Comment by morganwillcock** [comment] 2021-04-27 17:43
Removing the Game Explorer integration seems a good idea.

I'm not sure on the build number. I can imagine that if an automatic counter was built-in then someone will want controls to modify, customise, or reset the counter. I think it is probably better handled externally by a build system (replacing the current hard-coded build rules) where anyone can manage the values by themselves and define/derive their own meaning. Just going on common version control features there are already potentially incompatible  references which could represent the output of a build.

**Comment by ivan-mogilko** [comment] 2021-04-27 18:39
My proposal (made in discussion elsewhere) was to have an option in editor preferences that makes it to increment the build number (except I suggested to increment last version component).
Thus it's not hard-coded, but an equivalent to build script step built in the IDE.

**Comment by ivan-mogilko** [comment] 2021-04-27 18:45
My proposal (made elsewhere) was to have an option in editor preferences that would tell editor to increment the build number (except I suggested to increment last version component). Thus it won't be hardcoded, may be off by default, work as an automation for user action, and the field may be changed by external tool as well.

**Comment by ivan-mogilko** [comment] 2021-04-28 05:34
Back when this topic was briefly touched on forums I proposed a setting in Editor's preference which would automatically increment last Version's component, assuming Version is saved as a 4-component number. Because such option may be on or off, and Version is a rather generic field saved in a project file, this option might co-exist with external tools.

Imagining we have all build system made of a stand-alone tools, there will still be many users who prefer running and configuring it from the Editor. How may such system of configuring custom values look like from the perspective of IDE?

**Comment by rofl0r** [comment] 2021-04-28 08:36
> Imagining we have all build system made of a stand-alone tools, there will still be many users who prefer running and configuring it from the Editor. How may such system of configuring custom values look like from the perspective of IDE?

those could be passed as CPPFLAGS for the compiler, like `ascc -DBUILDNUMBER=1337 foo.asc` (which would expand the macro BUILDNUMBER to 1337) , though any such variable passed along will make the command line longer and as such make it harder to use IDE-less, therefore imo things like that should be used sparingly.

**Comment by ivan-mogilko** [comment] 2021-04-28 08:47
To clarify, by "IDE perspective" I meant - how this is supposed to be organized in a graphic interface.
For instance in above example we would need to have some kind of menu for setting up user macroses for compilation.

**Comment by ericoporto** [comment] 2021-04-28 12:09
The listed `Developer website`,  `Game Description`, `Release Date` and `Version` looks OK to be part of a manifest file - like properties that makes sense to be accessible in-game but also metadata that would be available to whatever can launch the game binaries.

I think the general settings interface is our game ["manifest file"](https://en.wikipedia.org/wiki/Manifest_file) and the `game` (lowercase) object is the closest to a script accessible representation of what's inserted in the manifest (missing those entries at the moment and with other extras though).

**Comment by ivan-mogilko** [comment] 2021-04-28 12:37
> the `game` (lowercase) object is the closest to a script accessible representation of what's inserted in the manifest (missing those entries at the moment and with other extras though).

Why lowercase `game` and not `Game` struct? For example, there's already `Game.Name` property, but looking at the `game` I do not see anything related to the "meta" information.
As far as I know, the division between these two comes from switch from plain structs to OOP-style API which happened around AGS 2.72; the only nuance is that this transition was not complete, some of the old struct variables got replaced with properties and others were not. So this is more a question of direction in which we like to develop script API.

**Comment by ivan-mogilko** [comment] 2021-04-28 12:44
> the `game` (lowercase) object is the closest to a script accessible representation of what's inserted in the manifest

This may be irrelevant at the moment, but are you refering to `game` object in script, or `game` object in the engine's code?

**Comment by morganwillcock** [comment] 2021-04-28 13:07
The idea that project source files should modified by the compilation process seems a bad one. Two builds in an identical environment should give the same result not a different one. It would also remove the ability to compile when the source is read-only.

> This ticket would work best if split in two different ones.

This seems a good idea.

I think the problem needs to be explored further because handling 'things I forgot to do' is going vary person to person. GUI controls shouldn't be a consideration until the problem is well defined.

**Comment by ivan-mogilko** [comment] 2021-04-28 13:58
I agree with splitting the ticket of course, but also would like to clarify -

> The idea that project source files should modified by the compilation process seems a bad one. Two builds in an identical environment should give the same result not a different one. It would also remove the ability to compile when the source is read-only.

The proposed field incrementation is not supposed to be a part of _compilation_ process, but a _pre-compilation_ step that adjusts the source prior to building it. This is mostly a problem of automating user actions. For example, when I am preparing AGS for public release I adjust version.json and run Script/push_version.py. If the source is readonly such step would of course be impossible, but it may be as well just skipped in this case. And of course two builds of same source in two enviroments that are configured same way (incrementing some field before compilation) would end up in same result, for what it's worth.

**Comment by ericoporto** [comment] 2021-04-28 14:58
TBH I don't like the idea of auto-incrementing either. 

Anyway, I remembered other thing that exists that would be useful.

https://github.com/adventuregamestudio/ags/blob/b31631d749e8a8ce7dd06d47e87e0193d8fb8871/Common/gui/guimain.cpp#L758

There are these String Macros, I believe they were invented because on the GUI Editor you can only write a string as a label property, but these things mentioned like game author and such (game name is already there), they would work as these string macros, like, imagine making a GUI in the GUI Editor and setting up these tokens in the string so they appear in a in-game menu.

**Comment by ivan-mogilko** [comment] 2021-04-28 15:21
> About mentioned lowercase game , it was the script: https://adventuregamestudio.github.io/ags-manual/Gamevariables.html#game-variables

Hmm, I thought you could mean one in the engine, because I do not remember any "meta/manifest" information in the `game` script object, but on the other hand `Game` struct (uppercase) does have "Name" property.
The difference between these two is that `game` is original one, and `Game` is new struct introduced around 2.7 as a part of OOP-style script update. In the past we were moving parts of `game` to their own structs like `Speech` for instance. So the choice here mostly depends on what directions we want to develop the script API in.

**Comment by ericoporto** [comment] 2021-04-28 16:01
Ah, it's alright, I was mostly trying to think if there was something that hold the game settings in-game and remembered I saw some stuff in the `game` object. `Game` is fine too, I didn't knew there was a name property there.

**Comment by ivan-mogilko** [comment] 2022-07-02 00:07
UPDATE: for the reference, the Game Explorer integration has since been removed in both 3.6.0 and ags4. Few fields, including "(game) Version" were kept and moved into (Information) section of General Settings.

**Comment by ivan-mogilko** [comment] 2023-04-02 05:49
Will close this, as the main part is solved, and there's apparently lack of interest from contributors to investigate the possible "version increment" feature.

If such feature is actually wanted, then it's best to open a dedicated issue.

**Closed by ivan-mogilko** 2023-04-02 05:49 UTC
Labels: what: editor, ags 4
