### ISSUE TITLE
Updating make_ags+libraries.sh to use Debian 8 instead of Debian 7

### ISSUE THREAD

**Issue by tobihan** [adventuregamestudio/ags#544] opened 2018-12-19 10:40 UTC
VGA asked me to help him to use this script, so I'm opening this issue for the discussion.

First of all, the script is not intended to be run on Debian wheezy. It is intended to be run on any Debian or Ubuntu as long as the wheezy distribution is still available. It uses the libraries from wheezy. It could probably be updated now, but one shouldn't use a distribution that is too new, because then the result could depend on a glibc that is newer than what most people have.

One has to follow the instructions in the file make_ags+libraries.sh. That means to create the wheezy chroots first:

sudo apt-get install ubuntu-dev-tools cowbuilder
cowbuilder-dist wheezy i386 create
cowbuilder-dist wheezy amd64 create

Then one can try to run the script in a clean git snapshot of ags:

debian/make_ags+libraries.sh

This fails immediately because someone removed the Debian revision from the package version. This can be fixed by reverting the commits b86554b485c54a490, 1988c97a80a974e28 and 726b0394fa7d430fc or (better) by changing the file debian/source/format to "3.0 (native)".

Then the script seems to do it job, but the build of AGS fails because of this:

ac/audioclip.o
In file included from ../Common/ac/gamesetupstructbase.h:23:0,
                 from ../Common/ac/gamesetupstruct.h:26,
                 from ac/audioclip.cpp:18:
../Common/ac/gamestructdefines.h:145:28: error: 'INT32_MIN' was not declared in this scope

So AGS doesn't build anymore on Debian 7 (wheezy) for some reason.

I updated the script (in the master branch) to use Debian 8 (jessie) instead and there AGS still builds.

**Comment by ivan-mogilko** [comment] 2018-12-19 11:07
I was always able to run this script up to latest 3.4.1 release, don't remember having any issues with script itself but then again I was using pretty old version of Ubuntu.
I had to make a fresh reinstall of Ubuntu recently so currently setting everything up. Later I will try to build this script and see what needs to be fixed in the engine code.

Regarding INT32_MIN issue, I found this yesterday and vga256 have already confirmed that same change fixes it:
https://github.com/jackaudio/jack2/pull/229

**Comment by tobihan** [comment] 2018-12-19 13:15
Anyway I think updating it to Debian 8 was a good thing. Debian 7 is not supported anymore. Debian 8 uses glibc 2.19 and the INT32_MIN issue does not happen there. This just means that the ags+libraries that comes out will now depend on glibc >= 2.19 instead of 2.13.

**Comment by rofl0r** [comment] 2018-12-19 15:43
the linked solution for the INT32_MIN macro is bogus. their solution is to hack a glibc-internal macro (detectable due to double-underscore prefix) __STDC_LIMIT_MACROS into their build process, which can have unintended side-effects. since an int32 is always 32 bit, the value of INT32_MIN is fixed.

so the proper solution would be something like that:

```c
#include <stdint.h>
#ifndef INT32_MIN
#define INT32_MIN (-2147483647-1)
#endif
```

or even better, replace all usage of INT32_MIN by MY_INT32_MIN or similar, which is defined to (-2147483647-1).

**Comment by 256colour** [comment] 2018-12-19 17:59
@tobihan I'm working in [toojays' openGL+linux branch now](url
https://github.com/toojays/ags/tree/ags3+linux-opengl), and trying to use the make_ags+libraries script. During compilation, it halts here:

```
gfx/gfxfilter_aaogl.o
gfx/ali3dogl.o
gfx/ali3dogl.cpp: In member function 'void AGS::Engine::OGL::OGLGraphicsDriver::FirstTimeInit()':
gfx/ali3dogl.cpp:385:28: error: 'glxewInit' was not declared in this scope
   int glxew_rc = glxewInit();
                            ^
compilation terminated due to -Wfatal-errors.
Makefile:45: recipe for target 'gfx/ali3dogl.o' failed
make[2]: *** [gfx/ali3dogl.o] Error 1
make[2]: Leaving directory '/build/ags-3.5.0.1/Engine'
```

That suggests to me that the compiler isn't seeing the GLEW library (libglew-dev), which is installed on my system. When I run the usual make --directory=Engine, it compiles properly. Is there a line I need to add to make_ags+libraries to make sure that it can see libglew-dev and include it in header searches?

**Comment by ivan-mogilko** [comment] 2018-12-19 18:04
@256colour actually it sees the library, otherwise the error would be pointing at #include <glew.h> command saying that header is not found or something alike.

It does not see particular functions inside the header, because they are hidden behind macros and for some reason their conditions are not met. I mentioned that problem here: https://github.com/adventuregamestudio/ags/issues/510#issuecomment-424288561

**Comment by tobihan** [comment] 2018-12-19 18:45
The script does not build ags on your system, it builds it in two Debian 8 chroots (one for 32 bit one for 64 bit). So it does not matter what is installed on your system. If you add additional dependencies you have to add them to the list of Build-Depends in debian/control so that they get installed in the chroot (in this case libglew-dev). Debian 8 came with glew 1.10, so that's the version that will be used.

In order for the library to be added to the bundle you also have to add libGLEW.so.1.10.0 to the list of libraries and libglew1.10 to the list of packages in debian/ags+libraries/hooks/B00_copy_libs.sh.

**Comment by ivan-mogilko** [comment] 2018-12-19 21:30
> The reason for the error is that glew 1.10 does not have glxewInit.

So, seems like the actual solution is to adjust the code to comply to glew 1.10.

**Comment by 256colour** [comment] 2018-12-20 01:54
Thanks for the explanation @tobihan - that confirms what I was seeing in the script with the use of cowbuilder. I'm going to start researching possible edits to @toojays code to make it comply with the older version of glew if that's possible. I'd rather keep the script as backwards-compatible as possible.

**Comment by toojays** [comment] 2018-12-20 11:04
> the linked solution for the INT32_MIN macro is bogus. their solution is to hack a glibc-internal macro (detectable due to double-underscore prefix) __STDC_LIMIT_MACROS into their build process

Double-underscore prefixes do not always indicate that a symbol is internal-only. ``__cplusplus`` in an obvious counterexample. Quoting from footnote 226 at the bottom of page 257 of [the last C99 draft](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf): "C++  implementations  should  define  these  macros  only  when __STDC_LIMIT_MACROS is  defined before <stdint.h>is included." This restriction was apparently removed in C11 but glibc was slow to adjust, see [glibc bug 15366](https://sourceware.org/bugzilla/show_bug.cgi?id=15366).

If you really dislike it though, another alternative may be to use ``std::numeric_limits<int32_t>::min()`` instead.

**Comment by rofl0r** [comment] 2018-12-20 12:46
> If you really dislike it though, another alternative may be to use std::numeric_limits<int32_t>::min() instead.

that sounds like a function call, i.e. is much worse than a constant for performance and codesize reasons.

**Comment by toojays** [comment] 2018-12-20 22:53
> that sounds like a function call, i.e. is much worse than a constant for performance and codesize reasons.

[std::numeric_limits<int32_t>::min()](https://en.cppreference.com/w/cpp/types/numeric_limits/min) is declared as ``constexpr``, which means it can be evaluated at compile time, and used anywhere a compile-time constant is required. In practice it will not result in a function call unless compiling with optimizations disabled.

In the one place where ags uses ``INT32_MIN``, a compile-time constant is required - you can't define a member of an enumeration to be the result of a non-constexpr function call anyway. So even with optimization disabled ``std::numeric_limits<int32_t>::min()`` will not result in a function call there.

**Comment by toojays** [comment] 2018-12-28 11:51
> Looking at the branch I see that libglew-dev is already in Build-Depends. The reason for the error is that glew 1.10 does not have glxewInit.

It turns out the call to glxewInit() isn't even necessary! I have removed it in commit 31f5276. I was able to build the result on Jessie. I only lightly verified that it ran on Ubuntu 18.04 though (i.e. copied the libGLEW.so.1.10 from Jessie, and including that in my LD_LIBRARY_PATH I was able to run the Jessie-built binary).

**Comment by 256colour** [comment] 2019-01-11 18:02
Nice work :) I'm going to cherrypick this patch today, and see if I can build on jessie.

**Comment by tobihan** [comment] 2019-01-28 19:54
Yes, I fixed debian/format in c4d512d5eec1b427ad22c3174e422d9d063603f6 and updated ags+libraries to Debian 8 in  a800ef2f461d97d9a2bd82fbfddfd523a829eaf1, both in the master branch.
Debian 7 is already the oldest distribution on the Debian servers, the next to be removed.

**Comment by ivan-mogilko** [comment] 2019-01-28 20:30
We are currently developing also in "ags3" branch, is it necessary to copy these fixes there?

**Comment by tobihan** [comment] 2019-01-29 13:38
Yes, it would make sense to apply it everywhere.

**Comment by ivan-mogilko** [comment] 2019-02-07 20:29
Ok, applied these changes to ags3 too.

**Closed by ivan-mogilko** 2019-02-07 20:29 UTC
