### ISSUE TITLE
Clipping fonts in GUIs

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2213] opened 2023-11-07 21:47 UTC
**Describe the bug**
If "GUI controls clip their contents" is set to false, Labels with a TTF font will nevertheless clip the font.

**AGS Version**
3.6.0.53

**To Reproduce**
1. Create a GUI with a label
2. Have a font that is taller than the label (note that I am using the font's LineSpacing setting)
3. See error in-game (in the editor the label looks fine)

**Expected behavior**
Labels obey the "GUI controls clip their contents" setting.

**Desktop (please complete the following information):**
Windows 11

**Comment by ivan-mogilko** [comment] 2023-11-08 00:21
Labels always clip their contents, this is a historical behavior.

The "GUI controls clip their contents" was introduced in order to force clip the contents for gui controls that did not do that, not other way around. The option to not clip contents is for backwards compatibility only.

**Comment by ivan-mogilko** [comment] 2023-11-08 00:50
I cannot reproduce this, tried both WFN and TTF fonts, and clip and non clip settings. Everything seems to work fine and consistent in Editor and at runtime.

Could you please tell which font and font settings do you use?

**Comment by ivan-mogilko** [comment] 2023-11-08 00:54
Is it possible that your label's text is too long to be displayed in one line and is wrapped?
Labels always limit the displayed text by their height. Historically the next line is only displayed if there's at least 1 extra pixel available, that's how it should work in non-clipping mode.

**Comment by ivan-mogilko** [comment] 2023-11-08 01:10
I noticed that this property is not documented in the manual. I added it now, here's the list of exceptions in its work:

> Button images are clipped using individual button's property called "ClipImage".
Label with a wrapped text will only ever display next line if there's at least 1 extra pixel of height available past the line spacing.
Sliders DO NOT clip as of AGS 3.6.0. This is left so for the time being, because the positions of their elements historically is calculated to be outside of their bounds.

**Comment by ivan-mogilko** [comment] 2023-11-10 16:07
@Crystal-Shard , could you please clarify the steps to reproduce this problem? Such as: font, font properties, label's text and sizes.
If it's possible, then it will help to have a test game or project.

**Comment by Crystal-Shard** [comment] 2023-11-10 18:07
Sorry, busy week. I'll try and upload a sample this weekend.

**Comment by Crystal-Shard** [comment] 2023-11-12 09:09
[FontTest.zip](https://github.com/adventuregamestudio/ags/files/13327592/FontTest.zip)

Please check the attached "game" and note how the GUI looks different in the editor than when playing the game via F5.

**Comment by ivan-mogilko** [comment] 2023-11-12 09:22
It looks the same for me?... just opened in 3.6.0 editor and hit f5:
![FontTest1](https://github.com/adventuregamestudio/ags/assets/1833754/be879823-78b9-4d8d-9bb2-5e84b3de603b)

**Comment by ivan-mogilko** [comment] 2023-11-12 09:26
It looks like it's the bug with font height + position calculation. The label had to cut the text much earlier, not drawing the second line at all, because it lies completely past the label's bounds (as I mentioned above, the text is never drawn in that case).
I can't explain why there's a difference between editor and engine. But in the game the text is clipped not by the real label's bottom (it's much higher).

**Comment by Crystal-Shard** [comment] 2023-11-12 09:32
If I increase the label (not the GUI) height to 150, it does display properly in game.

**Comment by ivan-mogilko** [comment] 2023-11-12 10:07
> If I increase the label (not the GUI) height to 150, it does display properly in game.

For all the new games I recommend enabling clipping, because that seems a proper behavior.
Disabled clipping is a backwards compatible setting meant to run old games that are not meant for a bigger upgrade.

**Comment by ivan-mogilko** [comment] 2023-11-12 19:59
Right, so this is because Label does not account for the font's "VerticalOffset" when calculating how much text fits in it. It assumes that offset is 0, as if text was drawn higher (in this case).
"VerticalOffset" was added in 3.4.1, unfortunately nobody noticed this mistake in time.

As much time has passed, I will have to make a version switch in case this behavior was relied upon in existing games.

**Comment by ivan-mogilko** [comment] 2023-11-12 22:21
Nevermind the previous comment (i deleted it).
The problem here happens because Label does not account for the font's "VerticalOffset" a) when it calculates how much text fits in its bounds **AND** b) when it calculates the text's graphical boundaries. It assumes that offset is 0, as if text was drawn higher (in this case).
The case **a)** causes too much text drawn although second line already lies beyond the label's rect;
case **b)** causes drawn text to get clipped by texture being not big enough to accommodate it.

NOTE: "VerticalOffset" was added in 3.4.1, unfortunately nobody noticed this mistake in time.

So, the way I see this now, case **b)** may actually get hotfixed in 3.6.0, as it's about calculating proper texture size to hold the text so that it won't cut off at a seemingly random position.

Case a) is rather fixed by a change in behavior, so I'd rather do this in 3.6.1.

**Comment by ivan-mogilko** [comment] 2023-11-25 04:29
I pushed a fix for 3.6.0, for all gui controls that have text:
02b15886d09b1025ac051bc8adfd6c3e5e7cd171, c9572541a6f8d38ed2ca1ba7af8e235c5d56c8f2.

Follow build may be used to test this out:
https://cirrus-ci.com/task/5344911348727808

**Comment by Crystal-Shard** [comment] 2023-11-28 18:13
I confirm that it works now.

**Closed** 2023-11-28 18:57 UTC
Labels: type: bug, context: graphics, context: fonts
