### ISSUE TITLE
3.6.0 Android: user reports no cursor and touch controls not working

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags#1756] opened 2022-08-22 05:25 UTC
This is a strange report, but one user claims that when they use 3.6.0 Android port (AGS Player to be precise) there's no game cursor displayed on screen, and touch controls don't result in clicks in the game.

This occurs on Android 11.

Original posts on AGS forums:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=59751.msg636648819#msg636648819
https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636649007#msg636649007

I was not sure how to diagnose this, so did not try to ask for more information yet.

**Comment by ericoporto** [comment] 2022-08-23 08:16
The symptoms looks like https://github.com/libsdl-org/SDL/issues/5322, this is a curious issue if it is that, I could not reproduce this in any device I own, and I do have Samsung devices with S-Pen. 

I made an experimental version using SDL2 after 2.24.0 from this commit (https://github.com/libsdl-org/SDL/tree/a204ef50bbf20b77083c0a14124e673efc3a53c6) and it appears to fix for the user - this version should include the fix for the SDL issue above.

The user reports using a OnePlus 10 Nord 5g, with Android 11, but from reading on it, I can't see how it could have an additional device in it to cause the SDL bug above.

**Comment by ericoporto** [comment] 2022-08-24 19:45
Almost, SDL 2.24 has building bug for me, on Android, so I used a later commit that has it fixed - linked it above.

**Comment by ericoporto** [comment] 2022-09-03 00:47
Hey, does it makes sense upgrading SDL2 version just for Android? In case it does, I can make a PR for it for using the mentioned commit above for Android.

**Comment by ivan-mogilko** [comment] 2022-09-03 18:07
> Hey, does it makes sense upgrading SDL2 version just for Android? In case it does, I can make a PR for it for using the mentioned commit above for Android.

I guess; but also, maybe we could just update it for everything this time? API is the same, so it's mostly updates to behavior on some systems (i think?).

**Comment by ericoporto** [comment] 2022-09-03 19:02
From what I understand they switched from 2.0.X to 2.X.Y versioning, which I think is meant for patches in Y, and also since I think `X==12`, odd numbers in X means development and even numbers mean releases. But regarding stability, I don't think so, at least until now all releases included new features along with the bug fixes.

**Comment by ericoporto** [comment] 2022-09-09 22:02
this should be fixed by the 2.24.0 upgrade (#1764) but I found a minor regression on the keyboard on Android that is mapped here: https://github.com/libsdl-org/SDL/issues/6202 . Because the change is in a single line in the java project that is in our repo too, we can easily patch it on our side, just waiting a bit to see what happens upstream, but if nothing happens, we can modify this line here before the next version is released.

**Comment by ivan-mogilko** [comment] 2022-09-19 13:41
@ericoporto is this fixed now by #1764?

**Comment by ericoporto** [comment] 2022-09-19 16:33
It should be, but I don't have a device that is affected by this. But the upgrade in that PR is what I had done for the build I sent tservo on forums. :)

**Closed** 2022-09-19 16:46 UTC
Labels: type: bug, system: android, res: needs testing, context: input
