### ISSUE TITLE
Add script function for writing into a console log

### ISSUE THREAD

**Issue by alkhimey** [adventuregamestudio/ags#640] opened 2019-02-19 23:40 UTC
The script debugging features of AGS are very basic. It is possible to break the script on certain lines watch the call stack and and watch room information, but there is not way to see the values of script variables.

Implementing a watch table might be hard task. Alternative easier suggestion is to add a debug console output command. This will allow script developers to debug by "printing" the values of the variables which is a very reasonable technique.

**Comment by ivan-mogilko** [comment] 2019-02-19 23:45
That is an interesting suggestion. Engine already has a logging system which may configure the "message type" and where it logs to (file, in-game console, etc).
There's also a hook to AGS Editor output panel if game was run from IDE. I believe it should be possible  write such messages there too.

**Comment by mgambrell** [comment] 2019-03-02 22:22
we had to add this ourselves while doing console ports. it's essential. implemented as a private plugin though.

**Comment by messengerbag** [comment] 2019-03-03 06:56
I'm sure most big AGS projects have some sort of logging system implemented. Here's the one for the AGS Awards client:

https://bitbucket.org/agsa/ags-awards-source/src/master/AGS%20Project/Log.ash
https://bitbucket.org/agsa/ags-awards-source/src/master/AGS%20Project/Log.asc

It would certainly be convenient to output log messages to the IDE console or built-in debug console.

**Comment by ericoporto** [comment] 2019-12-23 03:24
A simple print string to stdout would be pretty useful, specially when calling the Engine from command line on Windows. I can currently print strings through plug-in on Linux to the command line, but I wasn't able to figure out how it's done on Windows.

**Comment by ivan-mogilko** [comment] 2019-12-23 08:50
>  I wasn't able to figure out how it's done on Windows.

It's done about the same way, except engine is run as a non-console application, which means it is not attached to console by default, this is something that has to be done (can't tell if it's possible to do in plugin though, but maybe).


Since we'are at this, I think in general we need to decide on API and what it expected to do. For example, I doubt that having an explicit "print to stdout" function is ideal, because on some systems stdout may not be easily accessible, so there has to be something more abstract that translates to actual output depending on a system.

BTW, if I understand correctly, the original proposal was to make a proper in-game *console* where you could print to from script. AGS currently has one, but it has limited use, and also serious convenience issue because it has to rely on provided game fonts and is rendered in game's native resolution (could be pretty low).

**Comment by ericoporto** [comment] 2019-12-23 10:40
Yes, my usage is different, I want it to be able to print to stdout so I can run tests on the CI and have it printing the tests as they run instead of printing to a file and later on print the file, because if something wrong happens on Windows, the Engine outputs to a window with an ok button, which is invisible to the log of the CI and hangs the pipeline.

**Comment by ivan-mogilko** [comment] 2019-12-23 10:57
Maybe we could add something like a script function `System.PrintStdOut(string fmt, ...)` that is defined as "writing to the standard system output, individual for each platform"?

> Also, this may be other request, have the errors and messages on the Engine in Windows be printed to stdout instead of a message box.

Hey, I already added this option in 3.5.0. Seems like I forgot to mention this in release notes and in options...
c2828eeea9758d3308c8b2cebed61fe32cadebc7
a3aa331610defcc0dec6a56a3d0b4d8486f31920

**Comment by ericoporto** [comment] 2019-12-23 12:08
Ah, that would be awesome, I am already running the game from command line so it would be great.

> System.PrintStdOut(string fmt, ...)

That looks perfect! On Windows, if the user didn't enabled command line printing, I would expect this Script line to just do nothing instead of spawning endless message boxes xD . I would maybe advise at using it with just `String output` arguments and leave formatting to the `String.Format(String fmt, ...)` command, in case #1015 gets fixed in the future.

**Comment by ivan-mogilko** [comment] 2019-12-23 12:23
>  I would maybe advise at using it with just String output arguments and leave formatting to the String.Format(String fmt, ...) command, in case #1015 gets fixed in the future.

All script functions use same formatting method internally.

**Comment by rofl0r** [comment] 2019-12-23 14:26
> It's done about the same way, except engine is run as a non-console application, which means it is not attached to console by default

in that case printing will simply fail silenty and cause no harm. the developper debugging the bug will launch it from terminal though, where it works.

**Comment by ericoporto** [comment] 2019-12-23 14:34
Hey, I created the #1019 for the alert message box as stdout text task, I can also create an issue more similar to a task for the `System.PrintStdOut(string fmt, ...)` thing since here things were dealing more with the in Engine console or with the Editor debug console interface.

**Comment by ivan-mogilko** [comment] 2019-12-23 17:04
> in that case printing will simply fail silenty and cause no harm. the developper debugging the bug will launch it from terminal though, where it works.

No, it does not work when run from a terminal, that's the point. It's how non-console apps work on Windows.

**Comment by ericoporto** [comment] 2020-02-18 16:27
Just to replicate the information @morganwillcock posted on the other issue:
https://docs.microsoft.com/en-us/windows/console/attachconsole

> Attaches the calling process to the console of the specified process.
> ```
> BOOL WINAPI AttachConsole(
>   _In_ DWORD dwProcessId
> );
> ```
> 
> Value | Meaning
> -- | --
> pid | Use the console of the specified process.
> ATTACH_PARENT_PROCESS (DWORD)-1 | Use the console of the parent of the current process.
> 
>

**Closed** 2020-07-26 18:34 UTC
Labels: context: script api, res: in consideration, type: enhancement

**Comment by ivan-mogilko** [comment] 2020-07-26 18:38
For now implemented System.Log() script function (#1108), and more precise logging configuration with which it's possible to toggle various message groups in stdout, log file, game console etc (#1103). This is the minimal solution for the problem, but some enhancements could be added later if necessary (like better in-game console, etc).

**Comment by jumpjack** [comment] 2022-12-21 10:22
I don't undrestand how to use System.log() in editor: I don't see anything in "output" panel if the editor and in the DOS box where I launched editor from.

**Comment by ivan-mogilko** [comment] 2022-12-21 11:15
@jumpjack 
Logging is done either to console or file. Logging setup is explained [here](https://github.com/adventuregamestudio/ags/blob/master/OPTIONS.md) (look for "log").

When you run the game exe from the Windows console, you need to also pass `--console-attach` in command line.
Running *editor* from the console won't give any result in this sense.

There's also a log output in the editor prepared as a feature, but not yet merged: #1518

**Comment by jumpjack** [comment] 2022-12-21 11:23
So currently there is no way to have a log while using the editor? It also overwrites acsetup.cfg , so editing it is useless.

**Comment by ivan-mogilko** [comment] 2022-12-21 11:27
Yes, there no way to have a log wihin editor.

Yes, there's currently an issue that config in Compiled is completely overwritten when you rebuild a game. This is a messy situation that has to be resolved somehow.

**Comment by jumpjack** [comment] 2022-12-21 11:34
It looks like the only possible workaround is using Display() to show debug messages inside the game interface.

```
  int number = 123;
  String mex = "Hello %d\nNew line";
  Display(mex,  number);
```

**Comment by ivan-mogilko** [comment] 2022-12-21 11:39
You may also write into a label or listbox on gui.

**Comment by jumpjack** [comment] 2022-12-21 11:51
I was indeed investigating about how to write to file, but also the label idea is not bad.
Any clue about both of them?

**Comment by ivan-mogilko** [comment] 2022-12-21 12:03
> I was indeed investigating about how to write to file, but also the label idea is not bad.
Any clue about both of them?

For a label you'd need to create a GUI with a label on it, and setup its position in its properties to whichever convenient for you.
The label text is modified simply as `MyLabel.Text = "new text"`. If you need appending to the existing text, use String.Append, and other functions, here's the relevant article in the manual:
https://adventuregamestudio.github.io/ags-manual/String.html

For custom files, there's another article:
https://adventuregamestudio.github.io/ags-manual/File.html

The biggest issue with the files currently is that AGS denies writing directly into the game's directory. Instead it uses "special locations" (as explained in the article) which correspond to "save game dir" and "app data dir".
This may be worked around by setting custom paths for one of these "special locations" to current directory (afaik game authors use this setting for Steam releases). If you need this, go to the "Default Setup" in the editor, and set "Use custom game saves path" or "Use custom shared data path", and leave the path itself blank.

**Comment by jumpjack** [comment] 2022-12-21 13:06
I ended up with this function in global script:

```
function debugPrint(String text) {
  Display("Debug");
  
  File *output = File.Open("$SAVEGAMEDIR$/log.txt", eFileAppend);
  if (output == null)
    Display("Error opening file.");
  else {
    DateTime *dt = DateTime.Now;
    String finaltext = String.Format("%4d/%2d/%2d %2d:%2d:%2d" , dt.Year, dt.Month, dt.DayOfMonth,  dt.Hour,  dt.Minute,  dt.Second);
    finaltext.Append(" - ");
    finaltext.Append(text);
    finaltext.Append("\n");
    output.WriteString(finaltext);       
    output.Close();
  }
 }
```

It works, but the file it creates contains non-ASCII characters; probably it's an UNICODE file, but I am not an unicode expert...
I am using 3.6.0 RC3.

**Comment by ivan-mogilko** [comment] 2022-12-21 13:31
> It works, but the file it creates contains non-ASCII characters; probably it's an UNICODE file, but I am not an unicode expert...

AGS works in unicode mode by default since 3.6.0, it writes files in UTF-8. If you printed text containing non-ascii chars then they end up in a file too, but if you haven't, and the file contains something unusual, that might be an error. I cannot say more, unless I see some example, comparing what you were intending to print, and what was output into the file.

**Comment by jumpjack** [comment] 2022-12-21 13:47
Same issue detected in 3.5.1.

I am just printing current date/time and one word.

But I get this:

![image](https://user-images.githubusercontent.com/1620953/208920042-a53527a2-4124-41f3-b0ac-e46ae9ae210a.png)

**Comment by ivan-mogilko** [comment] 2022-12-21 14:03
Oh, that. You need to use File.WriteRawLine instead. Some of the File functions add special tags for testing when reading data back.

File.WriteRawLine also adds \n automatically.

**Comment by jumpjack** [comment] 2022-12-21 14:47
Thanks, this is my final script:

```
function debugPrint(String text,  bool displ) { 
  File *output = File.Open("$SAVEGAMEDIR$/log.txt", eFileAppend);
  if (output == null)
    Display("Error opening file.");
  else {
    DateTime *dt = DateTime.Now;
    String finaltext = String.Format("%4d/%02d/%02d %02d:%02d:%02d" , dt.Year, dt.Month, dt.DayOfMonth,  dt.Hour,  dt.Minute,  dt.Second);
    finaltext = finaltext.Append(" - ");
    finaltext = finaltext.Append(text);
    output.WriteRawLine(finaltext);       
    output.Close();
    if (displ) {
        Display(finaltext);
    }
  }
 }
```
Usage: 

```
function room_LeaveRight() {
  player.ChangeRoomAutoPosition(13);
  debugPrint("Leaving room 10 on the right",  true);
}
```

If second parameter is "true", message is not just saved but also displayed, blocking the game, so it shall not be used until the room becomes visible.

Result:

```
2022/12/21 15:44:03 - Leaving room 10 on the left
2022/12/21 15:44:05 - Creating room 10
2022/12/21 15:44:06 - Leaving room 10 on the left
2022/12/21 15:44:08 - Creating room 10

```

**Comment by ericoporto** [comment] 2022-12-21 16:51
I didn't understand much of the conversation but you can set a log output and file in acsetup.cfg and use System.Log and just have notepad++ or something else with the log file open. There are already logs from engine for room change and stuff like that, but they need to be set. Once it's annotated in acsetup.cfg, launching from the editor debugger should still write to there.

**Comment by ivan-mogilko** [comment] 2022-12-21 17:01
> Once it's annotated in acsetup.cfg, launching from the editor debugger should still write to there.

The problem is that the editor overwrites acsetup.cfg completely each time, and all the log config dissapears.

**Comment by jumpjack** [comment] 2022-12-28 06:54
Just found this plugin, not yet tested:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=60050.0
