### ISSUE TITLE
Full screen problems with multi monitor setup

### ISSUE THREAD

**Issue by Kirtai** [adventuregamestudio/ags#1082] opened 2020-05-31 02:14 UTC
**Describe the bug**
Fullscreen does not restrict itself to one screen in multi monitor setups. It tries to span all monitors at once

**AGS Version**
3.5.0.24, compiled from source, and allegro-4.4.3.1.

**Game**
GOG Games such as Primordia and Techobabylon

**To Reproduce**
Start the game with a version of AGS compiled from the 3.5.0.24 release on a system with multiple monitors.

**Expected behavior**
The game should be full screen on my primary monitor.

**Desktop (please complete the following information):**
 - OS: Kubuntu 
 - Version 20.04

**Additional context**
The old linux binary of AGS supplied with Primordia from GOG does correctly full screen on only my primary monitor. The version from github releases does not. This appears to be a regression. Technobabylon is windows only so I can't compare engines there.

Attached are the logs from both engines starting up Primordia.

[logs.zip](https://github.com/adventuregamestudio/ags/files/4706987/logs.zip)

**Comment by ericoporto** [comment] 2020-05-31 02:33
Duplicate of https://github.com/adventuregamestudio/ags/issues/258 .

**Closed** 2020-05-31 02:38 UTC
