### ISSUE TITLE
Font size doubles via RunAGSGame()

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2363] opened 2024-03-23 12:08 UTC
**Describe the bug**
If I run a game directly from Windows, the fonts look like the screen on the left. If I run this game via RunAGSGame(), then the fonts are doubled in size, like the screen on the right.
![fonterror](https://github.com/adventuregamestudio/ags/assets/107799718/2cc87c30-38ef-49fc-ab2a-d167792f8296)

**AGS Version**
3.6.0.53
(the earlier build is in AGS 3.3 and did not have this problem; I'm trying to upgrade to 3.6)

**Game**
CS Adventure Bundle, https://store.steampowered.com/app/551840

**To Reproduce**
1. Open game 1 by dragging its .AGS file onto the main executable
2. See normal-sized fonts
3. Open game 2
4. From game 2, open game 1 via RunAGSGame
5. See double-sized fonts

**Expected behavior**
Fonts have the normal size.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by ivan-mogilko** [comment] 2024-03-23 15:05
@Crystal-Shard please clarify, how do I reproduce this problem using this exact game? I tried running other games from the bundle menu, but don't observe the wrong font size in them.

**Comment by Crystal-Shard** [comment] 2024-03-23 15:30
Hi @ivan-mogilko, thanks for checking this out!

The main build in Steam is in AGS3.3 (which works fine). If you switch to the betatest branch, you'll get the AGS3.6 build which has the above bug. I.e. from the Steam interface, right-click on the game and select properties, go to the betas tab, and type in the password: crystal77shard

**Comment by ivan-mogilko** [comment] 2024-03-23 15:32
I forgot to mention that I've been running this game using current 3.6.0 engine.

**Comment by ivan-mogilko** [comment] 2024-03-23 15:51
@Crystal-Shard unfortunately, the "password" you gave is not working, if I try entering it in "Enter beta access code".

**Comment by Crystal-Shard** [comment] 2024-03-23 16:07
@ivan-mogilko You mean like this?

![image](https://github.com/adventuregamestudio/ags/assets/107799718/127ec07e-934e-445f-9ebb-6add5caf90ee)

**Comment by ivan-mogilko** [comment] 2024-03-23 16:14
Alright, it worked now, no idea what happened earlier.

**Comment by ivan-mogilko** [comment] 2024-03-23 17:54
Well, this is happening because some data is not properly reset when switching from one game to another.

**Comment by Crystal-Shard** [comment] 2024-03-23 18:22
Alternatively, is there some code I can add to the game_start() of the second function that would reset the data? Like, the setting for manually overriding font height, something like that?

**Comment by ivan-mogilko** [comment] 2024-03-23 19:54
> Alternatively, is there some code I can add to the game_start() of the second game that would reset this specific bit of data? Like, the setting for manually overriding font height, something like that?

No, fonts cannot be edited script (unless they are drawn by plugin or script).

I pushed a fix, and it may be downloaded here:
https://cirrus-ci.com/task/6379375594045440

**Comment by Crystal-Shard** [comment] 2024-03-24 13:12
That works. Looks like it even works if I don't recompile either game but just switch out the executable.
Thanks!

**Closed** 2024-03-24 16:48 UTC
Labels: type: bug, context: fonts
