### ISSUE TITLE
Editor: Auto Complete not always selecting proper line from the list

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1599] opened 2022-04-04 13:50 UTC
**Describe the bug**
Auto complete doesn't always complete the typed name e.x. AGS_MAX_REGION doesn't work, but AGS_MAX_OBJECT works just fine

**AGS Version**
4.0

**To Reproduce**
1. Type AGS_MAX_R and noticed that auto complete doesn't select the proper name from the list.
2. Type AGS_MAX_O and it will select AGS_MAX_OBJECTS correctly

**Expected behavior**
It should select proper name from the list

**Screenshots**
Built in AGS variable
https://i.gyazo.com/40993ad3bce2ff8e00ed80ab1b79c85e.mp4

Custom variable
https://i.gyazo.com/050dc2ea83d4bd1f1fe373f12800d0dc.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 
 **Additional Context**
 I have another projected opened on the side in 3.5.1 version of AGS(No idea if having 2 projects opened at the same time, even in 2 versions of the editor could be responsible for it, but who knows...)

**Comment by ivan-mogilko** [comment] 2022-06-28 16:14
Reproduces in both 3.* and ags4.

**Comment by ivan-mogilko** [comment] 2022-06-28 20:34
Report from another user, possibly related to the same problem:

> it seems that the "\_" symbol doesn't allow to correctly find the "keyword" we are writing into the editor. For example, if I have to write into the editor my variable "is_bright", when I write "is_", it should appear in the list and select my variable (so then I just press enter and it's done). I mean for "autocompletion". Since 3.6, it doesn't understand the "\_" symbol. Maybe other symbols do the same problem, I don't know.

**Comment by ivan-mogilko** [comment] 2022-06-29 02:30
@tarnos12 I made a [fix](https://github.com/adventuregamestudio/ags/pull/1723), could you test your cases there (because they may require full project)?
Editor build: https://cirrus-ci.com/task/4977914415415296

**Comment by tarnos12** [comment] 2022-06-29 06:20
@ivan-mogilko 

In 3.5.1.16 there is no issue with the underscore.
Your version fixed the issue I have in 4.0 with underscore and some camelCase autocomplete.

This issue is still there:
https://i.gyazo.com/8405f59b0a2d40e7f8720b1f6cdac884.mp4

The autocomplete for camelCase variables might be broken.(but not all of them, maybe it's just local variables in the same function)

**Comment by ivan-mogilko** [comment] 2022-06-29 12:33
> This issue is still there:
https://i.gyazo.com/8405f59b0a2d40e7f8720b1f6cdac884.mp4

Please, clarify what the issue is? From what I see, the variable is not even in the list (not just not selected)?

**Comment by tarnos12** [comment] 2022-06-29 12:50
I have to test it more and create a test project for different versions of ags.
Because some things work in 4.0 suddenly(same as in gyazo video) so that is confusing.

**Comment by ivan-mogilko** [comment] 2022-07-03 21:55
I'll mark this closed by #1726, as primary mistake has been fixed. If there are any other problems, please open a new report.

**Closed by ivan-mogilko** 2022-07-03 21:55 UTC
Labels: type: bug, what: editor, context: ui/ux
