### ISSUE TITLE
Font rendering on iOS has issues

### ISSUE THREAD

**Issue by rdurfee** [adventuregamestudio/ags#994] opened 2019-11-25 21:52 UTC
**Describe the bug**
Font rendering on iOS has issues with certain characters in the fonts included with AGS. Perhaps it is a true type hinting issue?

**AGS Version**
AGS 3.5.0.19

**Game**
This game was created based on the Thimbleweed Template.
A beta version of the game is available via TestFlight: https://testflight.apple.com/join/qXMyvvzn

**To Reproduce**
This occurs with the speech font and the text font. Tiny font appears to be unaffected. The characters that are broken are consistent. For example lowercase “v” is always broken in the Speech font.

An asterisk in the speech font amplifies the issue, pushing the color text outside of the black outlines.

Speech font examples: z, g, p, v, k, *
Text font examples: w, m, c, y, W

**Expected behavior**
The fonts should render as they do in the other platforms. 

**Screenshots**
See attached.
![0B4CD1A4-C783-4641-A847-E2081AE8A9B3](https://user-images.githubusercontent.com/12246002/69580863-6e218d80-0fa3-11ea-989e-ca5a18f24adf.jpeg)
![604C9E5C-55D7-4123-A555-E678ED591EE7](https://user-images.githubusercontent.com/12246002/69580864-6e218d80-0fa3-11ea-8df0-facfb7f21ab1.jpeg)
![35D6CA2D-FAD8-4A66-AFB3-3C837E70434D](https://user-images.githubusercontent.com/12246002/69580865-6e218d80-0fa3-11ea-9a10-305e32bb37cc.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS, iPad OS
 - Version: 13

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11, iPhone XS Max
 - OS: iOS 
 - Version: 13

**Additional context**

**Comment by ivan-mogilko** [comment] 2019-11-25 22:37
AFAIK the iOS port was not updated to the latest version of AGS yet, and it may still use old Allegro/Alfont patches.

**Comment by btrdurfee** [comment] 2019-11-26 15:32
Ah, iOS buildall.sh uses libsrc/download.sh which gets allegro-4.4.2.tar.gz.

It looks like the other platforms use fetchallegro.cmake which gets allegro-4.4.3.1-agspatch

**Comment by rdurfee** [comment] 2019-11-28 03:36
SO, I updated my scripts and patches to build allegro-4.4.3.1 instead, and it didn't help the situation. (On the plus side, the main allegro patch looks to be completely merged into 4.4.3.1, so I didn't need it at all. I only had to create a small 4.4.3.1 patch for each architecture to get it to build correctly.)

I worked around the issue where the color font busts out of the outline after an asterisk by changing the OutlineStyle to Automatic instead of Font. Apparently the fonts used in the template are not spaced the same when rendered on iOS. The character glyphs are still skewed, but at least they're outlined correctly now.

**Comment by ericoporto** [comment] 2019-11-28 12:13
In the picture above, it's only wrong for the first line, is this a repeatable behavior, does it only gets wrong in the first line of text?

**Comment by rdurfee** [comment] 2019-11-28 12:21
It happens on any line, and it’s always the same characters no matter where they are.

If you look at the 3rd screenshot, you’ll see the two “p” characters are missing a pixel, and the “v” character is poorly formed. These characters always appear that way no matter where they are.

**Comment by ivan-mogilko** [comment] 2019-11-28 12:57
There's this hack in the code, which may be related, originally it was only done for Linux:
https://github.com/adventuregamestudio/ags/blob/release-3.5.0/Common/font/ttffontrenderer.cpp#L112

**Comment by ericoporto** [comment] 2019-12-30 19:04
@rdurfee not sure if relevant, but I found someone named @jonreyno, who was apparently making a iOS port here: https://github.com/jonreyno/AGS/commit/6922847542401f451a26c6cc31b9d51b5889a008

**Comment by ivan-mogilko** [comment] 2019-12-30 19:44
@ericoporto it's based of 3.4.0, as far as I can see.

**Comment by jonreyno** [comment] 2019-12-31 03:20
Hey guys,
I’m actually in the process of getting 3.5 working properly in iOS so maybe I can take a look...

**Comment by rdurfee** [comment] 2019-12-31 03:55
I built with 3.5.0.19. I haven't tried with the final release of 3.5 since I didn't think the differences were applicable to the run-time of my game.

I'm wondering if it's a combination of the fonts and the font renderer. Maybe there's something about the renderer that makes some TrueType fonts not hint correctly. Since the outline font actually looks OK, but the font used for the colored inside is bad.

**Comment by jonreyno** [comment] 2020-01-01 18:40
I’m also using a slightly older version of 3.5 and I just tested that dialog you listed on my iPad and didn’t see that issue. I should note that my build does not use the Xcode project that’s in the repo and instead uses a modified version of the auto generated macOS project using cmake. There was a scaling issue that I fixed that might be a factor, but if you have that problem the whole screen would look off (not just the text). I can try and get my repo in order and get everything checked in if you’d like to try it.
![0F69F351-338F-4219-81A9-9628788ABE9C](https://user-images.githubusercontent.com/24993647/71644781-17cefb00-2c83-11ea-95fa-fdec7ce8d37a.png)

**Comment by ericoporto** [comment] 2020-01-08 15:56
@jonreyno can you point what was the scaling problem on iOS on the code and what you changed? And if the generated Xcode project required modifications, maybe they can be implemented in the CMake back. This information can be useful to others.

**Comment by jonreyno** [comment] 2020-01-10 06:22
@ericoporto I opened a pull request with the associated files for the scaling fix here: https://github.com/adventuregamestudio/ags/pull/1029

**Comment by ericoporto** [comment] 2020-06-24 01:48
The PR for this issue was apparently merged. It would be interesting to see if it can be closed. Have you checked @rdurfee ?

**Comment by ericoporto** [comment] 2023-12-17 23:58
I tested this with the Tumbleweed template (and other games too), and as far as can tell this issue is not happening anymore.

**Comment by ivan-mogilko** [comment] 2023-12-18 01:37
I will close this as possibly fixed in 3.6.1. If there's still an issue, please open a new bug ticket.

Although personally I believe that this was caused by particular font ("LucasFan-Font") incompatibility with the alfont/freetype version we're using. As mentioned in above comment:
https://github.com/adventuregamestudio/ags/issues/994#issuecomment-559484880
in early 3.5.0 this hack was applied only on Linux, but in later engine versions it is applied for all platforms
https://github.com/adventuregamestudio/ags/blob/2a631fbb3f19312acba971787ff4208fe49e9174/Engine/game/game_init.cpp#L347-L356

**Closed by ivan-mogilko** 2023-12-18 01:37 UTC
Labels: type: bug, context: fonts, res: needs testing, system: ios
