### ISSUE TITLE
super jazz man demo rendering issues in 3.5.1+

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#1356] opened 2021-07-09 20:23 UTC
https://www.adventuregamestudio.co.uk/site/games/game/821-super-jazz-man/

i have the demo version, and it should look like in the screenshot on that page, but backgrounds aren't rendered at all, and foreground things seem to be added one after the another when the character moves in.

**Comment by ivan-mogilko** [comment] 2021-07-09 20:43
Please tell, what graphic driver do you use, and what commit precisely do you build engine from?

**Comment by ivan-mogilko** [comment] 2021-07-09 20:48
Oh, nevermind, I confirmed this with every gfx driver on current master.

**Comment by ivan-mogilko** [comment] 2021-07-09 20:58
So, this is apparently a palette issue on OpenGL driver (and Direct3D on Windows).

Runs well with software driver on release--3.5.1 branch.

I cannot startup software driver on master for some reason, which may be a new bug.

**Comment by ivan-mogilko** [comment] 2021-07-28 03:45
This was fixed in software renderer:
0f9392a
28a882e

OpenGL does not work correctly, possibly because textures are not updated when palette changes. This is a general problem that persists with 8-bit games at the moment.

**Comment by rofl0r** [comment] 2021-07-28 12:57
thanks. i suppose we should regenerate the textures then.

**Comment by ivan-mogilko** [comment] 2021-07-28 16:16
I opened an issue regarding the texture problem in 8-bit games: #1376

Will close this, as it's possible to play the game using software renderer.

**Closed by ivan-mogilko** 2021-07-28 16:16 UTC
Labels: context: 8-bit gfx, context: graphics, type: bug
