### ISSUE TITLE
Script compiler incorrectly handles undeclared variable

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#492] opened 2018-08-15 20:33 UTC
This bug was found by @jeancallisti.

**UPD:** The error is basically that compiler may confuse an undeclared variable with a member of same name declared inside a struct, if certain expression is met (see below):

Following is the minimal known code that causes the mistake:
<pre>
struct MyStruct
{
    int var;
    import void Func();
};
 
function game_start()
{
    MyStruct s;
    MyStruct arrs[10];
    if (s.var == 1) arrs[var].Func(); // this must throw compiler error but does not
/*
    if (s.var == 1) arrs[var].var = 1; // this correctly throws compiler error
*/
}
</pre>

So, what happens here is that compiler sees **"[var]"** in the expression `if (s.var == 1) arrs[var].Func();` and for some reason does not realize it is not declared in that scope (probably mistaking it for the struct's member variable).

This line is parsed incorrectly and compiled into *something*. When run in the engine it causes following interpreter error:
`
Error: internal error: SCMD_CALLOBJ argument is not an object of built-in or user-defined type
`

**Expected:** compiler should realize that it is dealing with a use of an undeclared symbol and throw error.

**Comment by ericoporto** [comment] 2019-12-19 11:49
I think the reason this happens is because the linking happens at run time, so there's no check that this import doesn't have a pair.

**Comment by ivan-mogilko** [comment] 2019-12-19 12:12
If you are speaking of a runtime error, it happens basically because compiler generates incorrect reference to something that does not exist. But engine's behavior may not be important here, it all begins at compiler doing something silly.

**Comment by ericoporto** [comment] 2019-12-19 16:21
Is preventing imports not on header files sufficient here?

Or this is an error that happens with every array import independently if it's written in a header or script file.

**Comment by ivan-mogilko** [comment] 2019-12-19 16:26
> Is preventing imports not on header files sufficient here?

I am not sure if I understand you correctly. What "imports" are you referring to? There is no import "var" in the global namespace, this variable is declared inside the struct. I do not know where exactly the error is, but it could as well be during parsing. Compiler is confusing undeclared variable for struct's member.

**Comment by ivan-mogilko** [comment] 2019-12-19 16:49
Okay, probably I realized why there was a confusion. You were referring to MyStruct.Func's import all this time, right?

The error has nothing to do with that. You may implement this function, if you prefer, it does not matter.

The error is because compiler incorrectly interprets "var" symbol. It's probably thinks that code means MyStruct.var, but in reality it is undeclared in that scope, a variable that does not even exist.

**Comment by ericoporto** [comment] 2019-12-19 18:06
Oh.. tou were talking about arrs[**var**], the `var` between brackets.

**Comment by ivan-mogilko** [comment] 2019-12-19 18:30
Yes, sorry, I added more details to the bug description.

**Comment by ivan-mogilko** [comment] 2021-01-31 19:02
This is very strange, but I can no longer reproduce this. Even went back to AGS 3.2.1, and it works there, as in - compiler correctly throws "undeclared variable" error.

**Comment by fernewelten** [comment] 2021-02-14 16:58
For reference, AFAICS the new compiler will balk at `arrs[var]` with the message `Unexpected 'var'`. Both variants of the example code.

**Comment by ivan-mogilko** [comment] 2021-02-15 03:22
Alright, let's say this is definitely fixed in the new compiler.

**Closed by ivan-mogilko** 2021-02-15 03:22 UTC
Labels: context: script compiler, res: needs testing, type: bug, what: editor
