### ISSUE TITLE
Autocomplete can crash to desktop with badly named `import`

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1776] opened 2022-09-13 20:32 UTC
**Describe the bug**
A malformed `import` with a circular reference will crash the editor without any message.

**AGS Version**
3.6 and 4

**To Reproduce**
1. Write on a header `import crash crash;`
2. Save
3. Type in any script `crash.`
4. The editor closes without any feedback

**Expected behavior**
Circular imports should be ignored by the autocomplete.

**Comment by ericoporto** [comment] 2022-09-17 23:52
This is interesting because it generates a `System.StackOverflowException`, and it appears the Call Stack in the VS debugger can't be entirely trusted in this case. I think it's in [FindGlobalVariableOrType](https://github.com/adventuregamestudio/ags/blob/318045de7aef415daf7084891b829ba00956c338/Editor/AGS.Editor/Panes/ScintillaWrapper.cs#L1309) of the scintilla wrapper where the overflow is happening, because it's the only recursive function I notice on the stack.

**Comment by ivan-mogilko** [comment] 2022-09-18 12:56
The root of the problem here is that one function deals with multiple unrelated cases, and there's no way to tell what you expect from it.

When you have `import crash crash;` autocomplete sees *type* `crash` and *variable* `crash`, or the variable `crash` of type `crash`. (By the way, this is valid in some programming languages; probably not in AGS script.)

First time the function FindGlobalVariableOrType called with the intention to find a variable `crash`, which it finds successfully. But then it's called with the intention to find a **type** `crash`. However such type does not exist, so it skips further into searching variables again. Although it really should not, as we are not interested in variable now (we already found one). This is a clear mistake in function design.

**Comment by ivan-mogilko** [comment] 2022-09-18 14:43
Pushed a fix: 2934259cc4d15bf7888852b5ec68b2814059067a

**Comment by ericoporto** [comment] 2022-09-18 15:01
Awesome! Hey, I don't understand how the local variable `staticAccess` is assigned inside the function without being declared.

**Comment by ivan-mogilko** [comment] 2022-09-18 15:31
> I don't understand how the local variable staticAccess is assigned inside the function without being declared.

It's not a local variable, it's a function argument passed as a reference.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref

**Comment by ericoporto** [comment] 2022-09-18 19:36
Thank you! I didn't knew this was possible.

Can I ask if you reproduce something? When I create a new game from the sierra template, then on Global Script, if I type `player.`, then the autocomplete shows as it should, but if I type `cEgo.`, it doesn't. If I roll back these two new commits, `cEgo.` brings the autocomplete correctly. I don't know the difference between `player` and `cEgo` for the autocomplete.

**Comment by ivan-mogilko** [comment] 2022-09-18 21:59
I did it wrong first time, pushed another variant: 96770282d619c01fcda25eb8561e8317e3e20379

**Comment by ericoporto** [comment] 2022-09-18 22:05
yeahp, that fixes for me! All good!

**Closed** 2022-09-19 13:41 UTC
Labels: type: bug, what: editor
