### ISSUE TITLE
Can't click on menu main menu buttons for Donna Avenger of Blood

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#740] opened 2019-04-30 20:36 UTC
This is *not* this bug https://github.com/adventuregamestudio/ags/issues/122 ; but the main menu as you start the game.

as you can probably tell, this game worked before. Many things changed on ubuntu linux meanwhile: wayland, XWayland, libudev etc.

I tried: run on XWayland on a wayland session, run on X.org by login-out and selecting the option on log-in, run windowed and fullscreen on both cases.

XWayland on Wayland doen't show the window on alt-tab or the ubuntu overview, but on Xorg it shows.

In all cases pressing the buttons with the mouse cursor does nothing, but you can see the keyboard is passing keypresses because if you press 'ESC' during the intro quote it skips right to the menu.

The game can be found here: https://www.adventuregamestudio.co.uk/site/games/game/1523/

Well sort of, the AGS archive went down, but it links to a torrent of them now, so you can download the game that way. I'm using the actual game not the smaller demo also in the torrent, but the problem may manifest there too.

**Comment by morganwillcock** [comment] 2019-04-30 21:55
Just to check, was this with the software renderer or with the OpenGL one?
(you didn't mention a version number)

**Comment by i30817** [comment] 2019-04-30 21:56
```
ags --windowed  --gfxfilter none 1
Adventure Game Studio v3.5 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2019 others
ACI version 3.5.0.10

Initializing allegro
Initializing game data
Located game data file: /media/i30817/Huggin/Downloads/DONNA AoB 1.5/DONNA.exe
Opened game data file: game28.dta
Game data version: 36
Compiled with: 3.0.1
Setting up game configuration
Logging scipt to "warnings.log"
Data directory: /media/i30817/Huggin/Downloads/DONNA AoB 1.5
Voice pack found and initialized.
music.vox found and initialized.
Setting up window
Initializing TTF renderer
Initializing keyboard
Initializing mouse: number of buttons reported is 3
Sound settings: digital driver ID: 'AUTO' (0xffffffff), MIDI driver ID: 'AUTO' (0xffffffff)
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
Trying to init: digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'NONE' (0x0)
Warning: cannot enable MIDI audio.
Problem: No compatible drivers found in the system.

You may supress this message by disabling MIDI sound in the game setup.
Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'NONE' (0x0)
Install exit handler
Initialize path finder library
Game GUI version: 115
Game title: 'Donna: Avenger of Blood'
Checking for disk space
Initializing MOD/XM player
Game native resolution: 640 x 400 (16 bit)
Graphic settings: driver: Software, windowed: yes, screen def: scaling, screen size: 0 x 0, match device ratio: ignore, game scale: 1
Mouse control: off, base: 1,000000, speed: 1,000000
Initialize sprites
Audio is processed on the main thread
Engine initialization complete
Starting game
***** ENGINE HAS SHUTDOWN

```

**Comment by ivan-mogilko** [comment] 2019-04-30 22:02
I can confirm this in 3.5.0.10, independent of graphics driver.

**Comment by ivan-mogilko** [comment] 2019-05-01 07:29
Pushed a fix: 929503c0ce1796e3923cad7fbc62d1ee190df8cb

**Comment by i30817** [comment] 2019-05-01 11:19
That fixed this but fullscreen is still broken in Wayland. I think it never gains focus because esc does nothing during the intro.

**Comment by i30817** [comment] 2019-05-01 11:45
Interestingly if you wait until the game naturally progresses to the menu and then press the new game button you can start it, and then esc will work to skip again.

**Comment by ivan-mogilko** [comment] 2019-05-01 14:03
Oh, tbh I skiped what you've said about focus and was only fixing the main menu bug.
I do not know much about linux systems, and mostly relied to Allegro 4 library doing its job. Maybe it's incompatible with newer linux versions?

**Comment by ivan-mogilko** [comment] 2019-05-01 14:09
By the way, your log displays software graphics driver, have you tried running with OpenGL renderer?
<pre>[graphics]
driver=OGL</pre>
in acsetup.cfg

**Comment by i30817** [comment] 2019-05-01 14:50
That worked. No more 'wait until the intro' and the window is available in wayland.
The acsetup.cfg that is actually used is all the way in `~/.local/share/ags/Donna Avenger of Blood` (with the saves), so it's a bit tricky to figure out.

**Comment by ivan-mogilko** [comment] 2019-05-01 15:06
> The acsetup.cfg that is actually used is all the way in ~/.local/share/ags/Donna Avenger of Blood (with the saves), so it's a bit tricky to figure out.

Engine uses 3 config files that override each other -- this is explained in OPTIONS.md. Only existing settings get overriden, so if driver was not set in savegame dir then engine should have used one from game dir, or one from "global config".

> I'm wondering why OGL isn't the default on linux instead of software.

OpenGL support was added only recently so some things could be missing or untested.

But it should be default if "driver" is not set, otherwise it uses one set in config.

**Comment by i30817** [comment] 2019-05-01 17:17
> > The acsetup.cfg that is actually used is all the way in ~/.local/share/ags/Donna Avenger of Blood (with the saves), so it's a bit tricky to figure out.
> 
> Engine uses 3 config files that override each other -- this is explained in OPTIONS.md. Only existing settings get overriden, so if driver was not set in savegame dir then engine should have used one from game dir, or one from "global config".

I had deleted the game dir one because the game expected DX5 and came with a config for that (and i didn't know the OGL marker). No big deal, once opengl is stable you can set it as fallback on linux instead of software and now you know about this software bug on XWayland.

**Comment by i30817** [comment] 2019-05-02 08:18
The new fix seems to work without the crash.

**Comment by ivan-mogilko** [comment] 2019-05-02 08:47
Oh, I posted in wrong comments, I ended up redoing the fix differently because the first variant caused more bugs: 81f8f51

**Comment by ivan-mogilko** [comment] 2019-05-02 09:20
Also set OpenGL to default setting for Linux: 01fdf56c412a6cfc1ec4559cbf7c6a0dd789eefc

**Comment by ivan-mogilko** [comment] 2019-05-05 07:49
Ok, I believe this was fixed?

**Closed by ivan-mogilko** 2019-05-05 07:49 UTC
Labels: ags3, bug
