### ISSUE TITLE
8-bit games are no longer rendered correctly

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1369] opened 2021-07-19 00:18 UTC
I was first alerted to the problem from a bug report that Trilby's Note (a paletted 8-bit game) was no longer rendering properly. I tracked it down to the change to GetDisplayDepthForNativeDepth, which always forced 32-bit mode. For ScummVM, reverting it fixed the problem. However, for the standalone codebase, it doesn't, so it may require further fixes elsewhere as well.

I tested another 8-bit game at random, Ace Quest (from the 2001 folder of the agsarchive torrent), and it too didn't render either. So I'm presuming it's a generalized issue with all 8-bit games.

**Comment by rofl0r** [comment] 2021-07-19 00:34
probably related to or duplicate of https://github.com/adventuregamestudio/ags/issues/1356

**Comment by ivan-mogilko** [comment] 2021-07-19 07:30
@dreammaster GetDisplayDepthForNativeDepth depends purely on how particular renderer handles final output, and all it does is helps to define which display mode to create.

Previously we had Allegro 4 software renderer setting a display mode exactly matching the game native color depth, but since switching to SDL2 the software renderer is using SDL_Renderer in texture mode for the final output, hence there's no longer a need for that.

I don't know how much of the our renderer code you are using in scummvm, and how, so GetDisplayDepthForNativeDepth depends on what your "graphic driver" class is doing.

**Comment by ivan-mogilko** [comment] 2021-07-19 13:12
It's interesting that unlike with #1356 case, OpenGL renderer displays "Trilby's Notes" fine, but not software renderer.

**Comment by ivan-mogilko** [comment] 2021-07-19 15:51
Pushed couple of commits, making the new SDL-based software renderer actually working with 8-bit games correctly.

**Comment by dreammaster** [comment] 2021-07-21 01:40
Kudos on the quick fix. When I get time, I'll bring the ScummVM codebase up to date with it, and give it a test.

**Comment by ivan-mogilko** [comment] 2021-07-28 16:18
Opened ticket regarding displaying 8-bit games with the texture-based renderers: #1376

Will close this one as it's possible to play using software mode for now.

**Closed by ivan-mogilko** 2021-07-28 16:18 UTC
Labels: context: 8-bit gfx, type: bug
