### ISSUE TITLE
Gemini Rue crashes with ags from master branch when screenres=1

### ISSUE THREAD

**Issue by criezy** [adventuregamestudio/ags#1246] opened 2021-03-26 00:05 UTC
**Describe the bug**
When playing the Gemini Rue version from GOG, if `screenres=1` in the acsetup.cfg file, the games starts in 1/4 of the windows and promptly crashes when reaching the menu screen.

The crash is accompanied with the following error:
```
An error has occurred. Please contact the game author for support, as this is likely to be an error in game logic or script and not a bug in AGS engine.
(ACI version 3.5.1.0)

in "room125.asc", line 817

Error: Error running function 'repeatedly_execute_always':
Error: Script appears to be hung (a while loop ran 150001 times). The problem may be in a calling function; check the call stack.
```
The games works well when setting `screenres=0` in the acsetup.cfg file.
It also works well with ags from the 3.5.0 branch.

**AGS Version**
This can be reproduced with AGS version compile from master (I used 638b50fa29f15af13297edd708afedc59d56db07 to test this today, but also saw it with older commits).

As noted above, when compiling from the `branch-3.5.0` (2c928a000418ac8de87a57155f36b4c39c3eca8b) the issue does not occur.

**Game**
Gemini Rue from GOG.
I don't have the Steam version to check if the same occurs.
I initially saw this because I have been using the Mac version of the game without issues, but out of curiosity I downloaded the Windows version and saw this issue. However the Mac version is just the Windows version with wine, and the executables between the two versions are identical. The only difference was in the `acsetup.cfg` file. In the mac version `screenres` is set to 0, but it is set to 1 in the Windows version. And indeed changing it to 0 fixes both the 1/4 screen display issue and the crash.

**To Reproduce**
Start the game and waits a few seconds (or press escape to get it to crash earlier).

**Expected behavior**
The game should fill the window.
It should also not crash.

**Screenshots**
For the display issue, before the crash, it looks like this:
![image](https://user-images.githubusercontent.com/552105/112557754-15dfe300-8dc5-11eb-8af5-41b7499c4f2e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Big Sur (11.2)

**Comment by criezy** [comment] 2021-03-26 00:13
A `git bisect` points the finger to 14609109451d19cacbe7df5c78dd5dd92c50b961 for both issues.

**Comment by ivan-mogilko** [comment] 2021-03-26 03:57
So, basically running the game in upscale mode (640x400) does this?

Note you may also switch it using 
<pre>[override]
upscale = 1
</pre>
in config

**Comment by ivan-mogilko** [comment] 2021-03-26 13:13
Actually, to think about it, what version of AGS was this game compiled by? I thought Gemini Rue was made in a rather modern one. Maybe the problem is that upscale mode is applied where it should not be.

**Comment by criezy** [comment] 2021-03-26 15:50
It was compiled with AGS 3.2.0 (at least that is what is reported when starting the game).

**Comment by rofl0r** [comment] 2021-03-26 16:13
the code in question looks like this:

```asm
label000000013247: ; inside repeatedly_execute_always$0, ; referenced by 2 spots
	sourceline 810
	li mar, @var000104
	memread4 ax
	push ax
	li ax, 50
	pop bx
	lt bx, ax
	mr ax, bx
	jzi label000000013500
	sourceline 811
	li ax, 107
	push ax
	li ax, 10
	farpush ax
	setfuncargs 1
	li ax, Random
	farcall ax
	farsubsp 1
	pop bx
	add bx, ax
	mr ax, bx
	mr mar, sp
	memwrite4 ax
	addi sp, 4
	sourceline 812
	li ax, 90
	push ax
	li ax, 230
	farpush ax
	setfuncargs 1
	li ax, Random
	farcall ax
	farsubsp 1
	pop bx
	add bx, ax
	mr ax, bx
	mr mar, sp
	memwrite4 ax
	addi sp, 4
	sourceline 813
	ptrstack 8
	memread4 ax
	farpush ax
	ptrstack 4
	memread4 ax
	farpush ax
	setfuncargs 2
	li ax, Region::GetAtRoomXY^2
	farcall ax
	farsubsp 2
	push ax
	li ax, 9
	assertlte ax, 16
	muli ax, 8
	mr cx, ax
	li mar, region
	add mar, cx
	mr ax, mar
	pop bx
	cmpeq bx, ax
	mr ax, bx
	jzi label000000013493
	sourceline 814
	push op
	li ax, 31998
	farpush ax
	li ax, 31998
	farpush ax
	li ax, 60
	push ax
	li ax, 40
	farpush ax
	setfuncargs 1
	li ax, Random
	farcall ax
	farsubsp 1
	pop bx
	add bx, ax
	mr ax, bx
	farpush ax
	li ax, 303
	farpush ax
	ptrstack 12
	memread4 ax
	farpush ax
	ptrstack 8
	memread4 ax
	farpush ax
	li mar, @var000108
	push mar
	pop mar
	ptrget ax
	callobj ax
	setfuncargs 6
	li ax, DrawingSurface::DrawImage^6
	farcall ax
	farsubsp 6
	pop op
	sourceline 815
	li mar, @var000104
	memread4 ax
	addi ax, 1
	memwrite4 ax
label000000013493: ; inside repeatedly_execute_always$0, ; referenced by 1 spots
	sourceline 817
	subi sp, 8
	jmpi label000000013247
```

so roughly equivalent to this c code:

```c
while(1) {
  if(var000014 > 50) break;
  int a = Random();
  int b = Random();
  if(GetAtRoomXY(a,b) == region[9]) continue;
  DrawingSurface::DrawImage(... Random(), ... );
  var000104 += 1;
}
```

so it seems the GetAtRoomXY() code always triggers, so the increment code below isnt triggered (or maybe i interpreted > wrong and it actually is <).

**Comment by rofl0r** [comment] 2021-03-26 16:43
acsetup.cfg shipped with the game:

```ini
[misc]
gamecolordepth=16
defaultres=1
screenres=0
letterbox=0
defaultgfxdriver=DX5
gfxdriver=D3D9
titletext=Gemini Rue Setup
windowed=0
refresh=0
gfxfilter=StdScale2
antialias=1
sideborders=0
```

**Comment by criezy** [comment] 2021-03-26 18:21
The `acsetup.cfg` from the GOG Mac version I have looks like yours.
But the `acsetup.cfg` from the GOG Windows version I downloaded yesterday is different:
```ini
[misc]
gamecolordepth=32
defaultres=1
screenres=1
letterbox=0
defaultgfxdriver=D3D9
gfxdriver=D3D9
titletext=Gemini Rue Setup
windowed=0
refresh=0
gfxfilter=StdScale4
antialias=1
sideborders=0
```

Note that I did not run the installer, and I used `innoextract` to get the content. But I don't expect the installer would modify the files?

**Comment by rofl0r** [comment] 2021-03-26 19:40
> Note that I did not run the installer, and I used innoextract to get the content. But I don't expect the installer would modify the files?

i did the same... so apparently there are different versions of GOG version on trackers...

btw the code i reversed above is responsible for the "rain" animation on the start screen.

**Comment by criezy** [comment] 2021-03-26 20:22
> btw the code i reversed above is responsible for the "rain" animation on the start screen.

Which I don't have since I am not on Windows (see https://github.com/adventuregamestudio/ags/issues/81). I can get the rain sound very briefly (and then it still crashes) if I add `os=win` override in my accepting.cfg, so the issue does not seem to be related to whether the rain animation is actually used or not.

**Comment by rofl0r** [comment] 2021-03-26 21:08
i can see the rain just fine on linux.

> so the issue does not seem to be related to whether the rain animation is actually used or not.

the code retrieves random coordinates, when they're not inside the region 9, rain animation is added, otherwise the counter increased. the issue seems to be that the counter never reaches 50, which means the test for region == 9 always succeeds (or that the variable is set to a high negative number before entering the loop, which seems unlikely).

**Comment by ivan-mogilko** [comment] 2021-03-26 21:54
I doubt there's a need for such thorough investigation though, if the game was compiled with AGS 3.2.0 then it is not meant to be run "upscaled" at all. I forgot to add condition checking game data version when this feature was deprecated. Everything else is probably result of that. A quick guess was that coordinates are getting multiplied or divided unnecessarily and that what makes some condition in script never match.

**Comment by ivan-mogilko** [comment] 2021-03-27 00:23
Pushed a fix to ignore upscale mode for games made with 3.1.0 and higher: 8ab1f8164341cb59a0b845901d8c533af7105870

Also, while at that I realized there's another conversion-related mistake made during previous refactoring, which is also fixed now: 50f35df4e8b4983591bd0e452356c44906aff24b

**Comment by criezy** [comment] 2021-03-27 00:29
Thank you. That indeed fixes it without the need to mess with the acsetup.cfg.

**Comment by rofl0r** [comment] 2021-03-27 00:42
can you see the rain now ?

**Comment by criezy** [comment] 2021-03-27 00:46
> can you see the rain now ?
No. Not without setting the os override in the acsetup.csf (or modifying the code of `AGSMac::GetSystemOSID()` to pretend to be on Windows).

**Comment by rofl0r** [comment] 2021-03-27 00:53
for the record, i'm refering to what's dripping down here from the roof:

![](https://0x0.st/-qnb.png)

**Comment by rofl0r** [comment] 2021-03-27 01:04
oh, interesting. there is indeed OS specific code.

i patched my globalscript.s like this:

```diff
--- O/globalscript.s.org
+++ O/globalscript.s
@@ -22759,15 +22759,16 @@
 	sourceline 2371
 	thisaddr 51896
 	sourceline 2373
-	li ax, 0
-	setfuncargs 0
-	li ax, System::get_OperatingSystem
-	farcall ax
-	push ax
-	li ax, 2
-	pop bx
-	cmpeq bx, ax
-	mr ax, bx
+;	li ax, 0
+;	setfuncargs 0
+;	li ax, System::get_OperatingSystem
+;	farcall ax
+;	push ax
+;	li ax, 2
+;	pop bx
+;	cmpeq bx, ax
+;	mr ax, bx
+li ax, 1
 	jnzi label000000051960
 	push ax
 	li ax, 0
@@ -22918,15 +22919,16 @@
 	jzi label000000052256
 label000000052256: ; inside Rain$1, ; referenced by 1 spots
 	sourceline 2403
-	li ax, 0
-	setfuncargs 0
-	li ax, System::get_OperatingSystem
-	farcall ax
-	push ax
-	li ax, 2
-	pop bx
-	cmpeq bx, ax
-	mr ax, bx
+;	li ax, 0
+;	setfuncargs 0
+;	li ax, System::get_OperatingSystem
+;	farcall ax
+;	push ax
+;	li ax, 2
+;	pop bx
+;	cmpeq bx, ax
+;	mr ax, bx
+li ax, 1
 	jnzi label000000052316
 	push ax
 	li ax, 0
```

and now i can see heavy rain everywhere on the screen.

**Comment by criezy** [comment] 2021-03-27 01:04
Oh! That I can see it yes.

I though you meant the falling rain you can see all over the screen (as well as the additional rain sound). It is for example clearly visible in front of the building on the image below.

![image](https://user-images.githubusercontent.com/552105/112705777-27de8600-8e98-11eb-870a-e5064ebeab6a.png)

**Comment by ivan-mogilko** [comment] 2021-03-27 01:05
If I remember correctly, the rain drops from room objects and on the floor were made with regular animations, but full-screen rain effect was made using either separate script module or plugin, that for some reason was disabled anywhere but on Windows.

This is why we added "override os" setting in config.

**Comment by ivan-mogilko** [comment] 2021-03-27 22:16
Upscale mode problem was fixed, so closing.

**Closed by ivan-mogilko** 2021-03-27 22:16 UTC
Labels: ags3, context: bw-compat, type: bug
