### ISSUE TITLE
[4.0] Setting mouse cursor image property to -1 crashes the editor

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1724] opened 2022-06-29 14:07 UTC
**Describe the bug**
Setting an image property of the mouse cursor to -1, crashes the editor without saving anything.

**AGS Version**
4.0 specifically this <https://github.com/adventuregamestudio/ags/commit/ea81938764215d3bfea6aab22e7e2eb6dd8572db>

**To Reproduce**
1. Set mouse cursor image to -1 and press enter, the engine will hang and eventually crash.

**Expected behavior**
An error should appear preventing you from setting an incorrect value.

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by tarnos12** [comment] 2022-06-29 15:42
> I was not able to reproduce this exactly as told above, but there's a crash if you set to non-existing sprite and then try to change the preview zoom. Could you double check what is happening?

Yeah, I should have mentioned that, but I also used preview zoom which didn't do anything, but that probably was the cause of the crash.

**Comment by ivan-mogilko** [comment] 2022-06-29 16:21
Ok, after testing bit more: if you set a non-existing but positive sprite number then it will display placeholder sprite instead, so everything is fine. The problem is if you set negative sprite number.

Editor did not exactly crash for me instantly, but there's definitely some internal exceptions happening if you try to change the preview zoom, so I guess eventually that could lead to a crash.

Possibly need to do 2 things:
1, improve the preview safety in case of a bad sprite value;
2. implement a proper range check for cursor image property.

**Comment by ivan-mogilko** [comment] 2022-08-02 00:56
Fixed by a9e0e47ecfeec205a49ceaf8dd681944eede5eca and 9e71dd8997a3e7d5ef201878dce02c152ba19e0c

**Closed by ivan-mogilko** 2022-08-02 00:56 UTC
Labels: type: bug, what: editor, context: ui/ux
