### ISSUE TITLE
Potential vector subscript error when character is turning

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#2022] opened 2023-06-02 18:20 UTC
https://github.com/scummvm/scummvm/commit/e97a4ac06a6a8779a76524af7b3750a4e1002269

**Comment by ericoporto** [comment] 2023-06-02 19:12
ScummVm ticket: https://bugs.scummvm.org/ticket/14491

**Comment by ivan-mogilko** [comment] 2023-06-03 09:58
How to reproduce:

1. General Settings -> Character movement -> Turn to face direction = must be True.
2. Make a View with only 1 loop (looking down). DONT assign it to the character (see explanation below).
3. In script:
    * change the character to that special view using ChangeView;
    * order that character to face elsewhere using FaceDirection.
4. Run the game, observe error.

* Why not assign the view to the character right in the Editor. Apparently AGS 3.* editor does a "safety fix" to all Views assigned to characters at start, and creates at least 4 loops to them with dummy frames.

The bug itself seem to be the ancient one, it did not alert previously because loops were stored in a raw C array that did not do any access assertions.

**Comment by ivan-mogilko** [comment] 2023-06-03 10:05
@i30817 , @tag2015

I pushed a slightly different change, in order to not duplicate the condition:
fca247a28fe2d0609cdbd71ab734929c1c451f1c

**Closed** 2023-06-03 10:22 UTC
Labels: type: bug, context: game logic
