### ISSUE TITLE
When Run from Editor the game window is always maximized

### ISSUE THREAD

**Issue by kuxv** [adventuregamestudio/ags#1402] opened 2021-08-25 08:47 UTC
**Describe the bug**
When Run from Editor the game window is always maximized unless the game setup is run and the options are modified there. The Default Setup options are ignored (like Windowed Mode).

**AGS Version**
3.5.1.10

**Game**
Basic BASS Template

**To Reproduce**
1. Create a new game from BASS template
2. Set Windowed Mode to True in Default Setup
3. Run F5

**Expected behavior**
The Game is running in a windowed mode with the size of the game's resolution.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by ivan-mogilko** [comment] 2021-08-25 09:08
Apparently, the problem is that the config file is not written until the full game is built (done with Build -> Build EXE).
So if a user creates a game, changes Default Setup, then runs a test (F5), the config is not getting written, and the engine does not know about it.

If this assumption is correct, the fix would be to also write default config when the game is run in a test mode.

**Comment by ivan-mogilko** [comment] 2021-11-10 16:36
Should be fixed by 8e5be48f33e5fafa39acf23d91cc6906f0129594, as a part of 3.6.0 version.

**Closed by ivan-mogilko** 2021-11-10 16:36 UTC
Labels: type: bug, context: graphics mode, res: needs testing
