### ISSUE TITLE
Duplicate check for & symbol

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2264] opened 2023-12-17 06:57 UTC
**Describe the bug**
The following code crashes with an error: DisplaySpeech: auto-voice symbol '&' not followed by valid integer
```
    cCharacter.Say ("&123 The office of Dewey, Cheatem,");
    cCharacter.Say ("&124 & Howe, attorneys at law.");
```

**AGS Version**
3.6.0.53

**To Reproduce**
Run the code above.

**Expected behavior**
That it doesn't crash. I get that & is a reserved symbol, but it's odd that the engine checks for it twice.
Not an urgent issue since it has an obvious workaround.

**Desktop (please complete the following information):**
Windows 11

**Comment by ivan-mogilko** [comment] 2023-12-17 12:03
So, this is a logical bug caused by one speech function calling another internally, but both are running voice tag check, thus this action gets duplicated.
I suspect that if you have two valid consecutive tags inside the string, then it will actually play the second one.

This seems to be an ancient error, also reproduced in 3.2.1 at least.

The solution is likely to create a 3rd function which is called by both and contains only code that has to be shared.
Related functions are: `_displayspeech` and `_display_at` (_displayspeech calls _display_at).

**Comment by ivan-mogilko** [comment] 2023-12-17 19:02
I fixed this problem in both master and release-3.6.0 branches.

temp 3.6.0 build will be available for testing here after a short while:
https://cirrus-ci.com/task/4624123578548224

However, while trying this out, I noticed that there's another unexpected behavior: prior to displaying a text engine will cut out any preceding `&` sign if it's located at the index 0 of string. This happens even after cutting the first "&N" out.
So in your example
```
"&124 & Howe, attorneys at law."
```
will be displayed as
```
"Howe, attorneys at law."
```
This may be worked around by adding at least 1 space before "&".

This behavior is ridiculous, because it's implemented as a part of splitting text into lines whenever the context supports wrapping text. So even labels and dialog options will do this, for instance.

Furthermore, the "&"-skipping logic works so bad, that it also skips anything glued to "&" char, until the next space.
So, if you have a label with "&One Two", it will display "Two".

**Comment by ericoporto** [comment] 2023-12-17 19:54
> Furthermore, the "&"-skipping logic works so bad, that it also skips anything glued to "&" char, until the next space.

I am not completely sure, but I think I found a small change on the logic that make it work

```diff
diff --git a/Engine/ac/display.cpp b/Engine/ac/display.cpp
index 439133515..3f29b0532 100644
--- a/Engine/ac/display.cpp
+++ b/Engine/ac/display.cpp
@@ -435,7 +435,7 @@ bool try_auto_play_speech(const char *text, const char *&replace_text, int chari
         return false;

     int sndid = atoi(&src[1]);
-    while ((src[0] != ' ') & (src[0] != 0)) src++;
+    do { src++; } while (src[0] >= '0' && src[0]<= '9');
     if (src[0] == ' ') src++;
     if (sndid <= 0)
         quit("DisplaySpeech: auto-voice symbol '&' not followed by valid integer");
@@ -462,9 +462,9 @@ int GetTextDisplayLength(const char *text)
     {
         // if there's an "&12 text" type line, remove "&12 " from the source length
         size_t j = 0;
-        while ((text[j] != ' ') && (text[j] != 0))
-            j++;
-        j++;
+        do { j++; } while (text[j] >= '0' && text[j]<= '9');
+        if (text[j] == ' ') j++;
+
         len -= j;
     }
     return len;
```

**Comment by ivan-mogilko** [comment] 2023-12-17 20:01
I was speaking about a different place, in line-breaking function, which acts as a duplicate, and checks for & after the voice number was potentially already removed:
https://github.com/adventuregamestudio/ags/blob/1899fad4c4df0e2ddce7eb04699eb262e3638674/Engine/ac/string.cpp#L292-L295

**Comment by ericoporto** [comment] 2023-12-17 20:24
It looks like these logics (the part with `&` (ampersand) symbol could be in `Common/util`, so at least it could be consistent, even if used in different places.

**Comment by ivan-mogilko** [comment] 2023-12-17 20:33
So, anyway, I was too rushed when fixing this. Apparent I fixed only one part of the problem, but the second remains. Although there's no runtime error now, the second & will still be omitted.

On another hand, even without my first fix, there's a working workaround: adding an extra space right before the second &.

Also, I think i will be only changing this in 3.6.1 and not in 3.6.0 patches, because there likely to be script modules that assume this behavior, and I would like to take a safe route.

**Closed** 2023-12-21 01:04 UTC
Labels: type: bug
