### ISSUE TITLE
Among Thorns does not allow 'background movement click'

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#823] opened 2019-06-08 09:55 UTC
Game is here for your testing pleasure: https://archive.org/details/among-thorns

Anyway, if you run it on wine, and click play, you'll see after the short dialog and intro that the game allows left click to move the ego. However if you use the release-3.5.0 build, left click does nothing and you have to depend on clicking 'interactable objects'

This leads to a deadend situation later where you have to click to move, but since it's not necessary to reproduce, i'm not giving a save.

I haven't regression tested yet, just notifying.

**Comment by i30817** [comment] 2019-06-08 11:38
I'm doing a regression test now, telling to avoid duplicate work.

**Comment by ivan-mogilko** [comment] 2019-06-08 12:10
Hmm, I could not reproduce this with latest release-3.5.0 branch.
Could you give more detail, like where do you click on screen?

I also noticed, in original game too, that after intro finishes there's a moment when left click on empty space does not work first 1-2 times. Idk if there's some invisible delay or a bug in the game.

**Comment by i30817** [comment] 2019-06-08 12:24
That delay is because the game is slowing some popups to show where the inventory and menu buttons are (top left and top right), so i think it's normal.

About the 'can't reproduce', i'm seriously considering it since i'm 5 bisects away from release-3.5.0 with the bisect always good but we'll see.

**Comment by i30817** [comment] 2019-06-08 12:32
Ugh, turns out that the bisect i was doing was useless, because the problem occurs only on that scene i mentioned later (3rd room).

I'll redo it with a save from 3.4.7 (game is 3.4.6, which isn't a real release in the repo).

**Comment by ivan-mogilko** [comment] 2019-06-08 12:39
> because the problem occurs only on that scene i mentioned later (3rd room)

Oh, so it's seen in the 3rd room, not the first one? Earlier I got impression that I only have to click through the first dialog.

> I'll redo it with a save from 3.4.7 (game is 3.4.6, which isn't a real release in the repo).

3.4.0.7 and 3.4.0.6 perhaps? 3.4.6 would be different thing (and does not exist).
3.4.0.6 was the wip beta version of 3.4.0.

**Comment by i30817** [comment] 2019-06-08 12:52
> Oh, so it's seen in the 3rd room, not the first one? Earlier I got impression that I only have to click through the first dialog.

So did i until you mentioned you couldn't reproduce (because of that delay). To be clear the bug happens once you get out of the subway train, talk to the contact and go down the 'escalator' (which is is a ego movement that moves without sprite animation). In wine, you regain mouse click control on backgrounds, in the current ags you can 'only' click on interactable objects, which gets you stuck if you go right on the same scene where you talk to a cop, because you can't go back.


> > I'll redo it with a save from 3.4.7 (game is 3.4.6, which isn't a real release in the repo).
> 
> 3.4.0.7 and 3.4.0.6 perhaps? 3.4.6 would be different thing (and does not exist).
> 3.4.0.6 was the wip beta version of 3.4.0.

Yeah that. Game said it was built with `3.4.0.6`, which doesn't exist in the repo, so i checked out 3.4.0.7

**Comment by i30817** [comment] 2019-06-08 12:59
Mini walkthrough to get to the room:

use credit card on auto-attendant, look at sign, exit right, click on dumpster, click on communicator on the left of the dumpster, talk to the person there, ask for help, ask for his id, exit conversation, click on the green buzzer, ask for services, ask for free sample, show the hardware you got in the dumpster, exit conversation, give cable to person, use id on communicator, exit..

Then you'll be on the 3rd scene.

**Comment by i30817** [comment] 2019-06-08 14:44
r3ebdc9f59aa39d48f24549eb694019c83de2b3c2 is the first bad commit
commit 3ebdc9f59aa39d48f24549eb694019c83de2b3c2
Author: Ivan Mogilko <ikm_spb@yahoo.com>
Date:   Mon Apr 22 01:53:14 2019 +0300

    Engine: formal support for having multiple viewports and cameras

:040000 040000 7bfa5c18943b205cc55e05c8a9d8ac45034dec7f 3b20e981c55dec1bdff71e71a9163d96cf20f2aa M	Engine
:040000 040000 8d80285546f133733717e33303a858f5b85ea83a c6317e9386f4ac6efb60d535df8f9713f698f634 M	Solutions

**Comment by ivan-mogilko** [comment] 2019-06-08 16:41
Aha, I see what's wrong, ProcessClick does not work correctly.

**Comment by ivan-mogilko** [comment] 2019-06-08 17:51
Should be fixed with 172fc653df5a1bf2522a202568a5ac7d181f3412

**Comment by i30817** [comment] 2019-06-09 00:08
fixed

**Closed** 2019-06-09 00:41 UTC
Labels: ags3, backwards compatibility, bug
