### ISSUE TITLE
Transparent GUI's controls are incorrectly blending with the parent GUI

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1838] opened 2022-11-28 21:43 UTC
**Describe the bug**
In hardware accelerated rendering, semi-transparent GUIs are being rendered incorrectly because controls are being blended with the underlying GUI graphics.

**AGS Version**
AGS 3.6 and AGS4 (D3D9 and OpenGL)

**To Reproduce**
1. Create a GUI with a black background and colored border
2. Create a control, like a text box with some colors and borders so it overlaps with other visible elements
3. Make the GUI 50% transparent or so
4. Controls are drawn on top of the semi-transparent GUI mixing with the underlying content

**Expected behavior**
![immagine](https://user-images.githubusercontent.com/1430815/204387156-a7cd2356-bc2f-4137-89b3-ab48dcb0d394.png)
(correct, software rendering)

**Screenshots**
![immagine](https://user-images.githubusercontent.com/1430815/204385696-0c00f8f6-74e4-4878-b4df-ef7828352f8e.png)
(wrong, D3D/OGL)
The controls shouldn't be mixing with what's underneath that is part fo the GUI.

**Comment by ivan-mogilko** [comment] 2022-11-29 01:03
Also reproduced in 3.6.0, so it's a 3.6.0 bug.

**Comment by ivan-mogilko** [comment] 2022-12-08 03:31
@AlanDrake 
Looks like I made a successful experiment:
https://github.com/ivan-mogilko/ags-refactoring/tree/360--guitexturerenderfix2

Basically, this lets to pass a texture when you call BeginSpriteBatch, and the whole batch and all the nested sprites will be rendered on that texture target instead.
The nice thing is that then this texture may be added just like a regular sprite, with any transforms and effects.
Unfortunate thing is that the code organization is clumsy.

Made it work with Direct3D for now, next will do for OpenGL, and try to tidy the code.

**Comment by AlanDrake** [comment] 2022-12-08 14:15
I tried it, but I see the GUI transparency is not being applied somehow, though it's being set to the new texture.

**Comment by ivan-mogilko** [comment] 2022-12-08 17:20
> The 3.6 version of the Test Wretcher project, if you still have it.

Apparently the 3.5 (or 3.6?) version of the Wretcher had "Classic" gui render style set, which makes GUI draw in software mode. I haven't tried the ags4 version yet.
Pushed a fix that broke the software mode now.

**Comment by AlanDrake** [comment] 2022-12-08 17:30
Ah, that explains why I had never noticed the blending working differently on 3.x... I just wasn't using proper alpha blending.
Now it appears to work as expected with this branch, in both modes. 👍

**Comment by ivan-mogilko** [comment] 2022-12-12 17:10
Updated the test branch with OpenGL supporting render targets; but I'm probably missing something, because the GUI images are now vertically mirrored. Either the sprites are drawn inverted along the y axis on the texture, or the texture is drawn inverted itself, not sure yet.

Another thing that's missing is that Direct3D must release these "buffer" textures after window is resized, otherwise IDirect3DDevice9::Reset will fail. On another hand, I'm curious whether there's a way around that.

**Comment by ivan-mogilko** [comment] 2022-12-13 14:16
Unfortunately current code does not work correctly. This is not seen while only GUI has transparency, because that transparency is applied to the final texture (used as a render target). But if you set transparencies to individual gui controls, this produces a weird effect where the control's image would blend with contents of a main backbuffer, and then pasted on top of the render target texture (or so it seems).

This is an example of how this looks like (direct3d):
![test-screenshot01](https://user-images.githubusercontent.com/1833754/207357104-5af6e018-60dd-44e2-b9a9-117fa613c9d1.png)

**Comment by ericoporto** [comment] 2022-12-13 15:56
You bind to the framebuffer that is the GUI texture, do the drawing, and later you bind to the framebuffer that is the top on stack (screen). It looks correct [following this tutorial](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-14-render-to-texture/). Maybe add an asset current_fbo is bigger than 0 in the first bind, just in case.

**Comment by ivan-mogilko** [comment] 2022-12-14 06:12
@ericoporto have found that there are alpha blend settings that may fix this problem. The code is experimental, but pushed to this branch for a test. It's for Direct3D at the moment, but supposedly similar thing may be done for OpenGL.

In regards to the OpenGL inverting GUI, I suspect this may be related to the sprite rendering relying on either native-res surface size or window size when applying positions. This should be rewritten to use sprite batch's matrix instead.
(There's another related thing that potentially may be optimized, it's the choice of a scaling filter, which also depends on "render in native res" / "render in screen res" setting, and will conflict with the new code.)

**Comment by ivan-mogilko** [comment] 2022-12-15 09:50
Hm, on another hand, I realized that #1708 will be necessary for this regardless, because right now there are some global sprite batch settings being applied in every batch, that will conflict with ones rendered onto a texture.

**Comment by ivan-mogilko** [comment] 2022-12-23 23:40
So, back at this (after #1708 is resolved).

The updated test branch: https://github.com/ivan-mogilko/ags-refactoring/tree/360--guitexturerenderfix3

Fixed inverted GUIs with OpenGL, and few minor things.

Remaining problems:
1. Blending bug, described above in a comment with a screenshot. There's a fix suggested by @ericoporto, which seem to fix this problem, but it in turn breaks anti-aliasing, which means that the blending settings are still not fully suitable, and have to be adjusted further. This is what I will be investigating next.
2. All render targets must be released and recreated under Direct3D when the screen mode changes.
3. Tidy code...

**Comment by ivan-mogilko** [comment] 2022-12-24 21:34
About the blending fix, after [reading an explanation](https://learn.microsoft.com/en-us/windows/win32/direct3d9/render-target-alpha) of what these modes mean, I suppose the proper settings would be something like:
```
direct3ddevice->SetRenderState(D3DRS_SEPARATEALPHABLENDENABLE, TRUE);
direct3ddevice->SetRenderState(D3DRS_SRCBLENDALPHA, D3DBLEND_SRCALPHA);
direct3ddevice->SetRenderState(D3DRS_DESTBLENDALPHA, D3DBLEND_ZERO);
direct3ddevice->SetRenderState(D3DRS_BLENDOPALPHA, D3DBLENDOP_ADD);
// or direct3ddevice->SetRenderState(D3DRS_BLENDOPALPHA, D3DBLENDOP_MAX);
```
Supposedly that should mean: take source alpha as-is, zero the dest (render target) and either add or choose the max; in either case the render target's own alpha is discarded, and the rendered sprite's is used as a final result.

Unfortunately, even with these settings, there's still something wrong or missing. Following are screenshots comparing two version of the same GUI with a alpha gradient: first is how the engine renders gui now (and worked before), and how it renders it using these settings:

![scr-alphagradient-normal](https://user-images.githubusercontent.com/1833754/209451499-878e9619-b163-4e12-bafc-f0cd5a608644.png)
![scr-alphagradient-separatemode](https://user-images.githubusercontent.com/1833754/209451501-b993a094-62b2-40ea-81a6-a9a48144d3d0.png)

As you may notice, it looks like some percentage of a source alpha is lost.

**Comment by ivan-mogilko** [comment] 2022-12-25 00:16
I found a source of another error, which I initially attributed to the aforementioned alpha blending settings. But in the end I realized it's not that. The problem was that the GUI background with alpha channel and translucent parts was rendered as if alpha value was additionally decreased (more transparent than necessary). I figured out this is because the background is still being *blended* with the texture buffer (which has some clear color), while what we need is to it get *copied*.

The solution which I decided to try was to introduce "blend mode" for the sprite, similar to what @AlanDrake did in ags4, only with 1 special blend mode that does plain src copy: https://github.com/ivan-mogilko/ags-refactoring/commit/c5aa2327c286be96fabc56b51ec6d30b3c127153
This seem to fix that erroneous behavior.

So far from what I see there's one issue remaining, which we noticed randomly testing Dave Gilbert's new game "Old Skies". With this branch the options of the main menu appear missing anti-aliasing. Following are two screenshots comparing the original and new look:

![oldskies--normal](https://user-images.githubusercontent.com/1833754/209453724-3caafdf8-4d58-47eb-9fa8-3e00ea9191ea.png)
![oldskies--sharp](https://user-images.githubusercontent.com/1833754/209453728-7f7b4ce8-aea1-4221-b4e2-3b21011e2790.png)

This does not depend on whether the alpha blending settings are done or not. I thought this is too going to be fixed with this latest blend mode fix, but it was not, so there's something else missing.

**Comment by ericoporto** [comment] 2022-12-25 01:14
When reading the blending stuff, something that went over my head, but maybe you can make sense of, is the premultiplication of alpha with the colors, I am not sure how it works, but this seems to darken things when done incorrectly, just thought to mention in case it this helps.

**Comment by ivan-mogilko** [comment] 2022-12-25 01:23
The above appears to be the same problem I was trying to fix with blend mode change; except I was thinking that copying gui background is enough. But same issue reoccurs if gui background is transparent while the buttons are translucent.

**Comment by ericoporto** [comment] 2022-12-25 01:39
Does using white vs black makes any difference?

**Comment by ivan-mogilko** [comment] 2022-12-25 12:17
> Does using white vs black makes any difference? I mean because white is all 255, so the blending I think would maintain all range if this is the observed behavior, in case the premultiplication is impacting.

Do you mean the color which is used to clear the surface? If so, then the white color gives an opposite, "lighter", effect.

Overall, the root of the problem is that the sprite's color is blended with the surface, but we don't need it to blend with the surface at all, we need it to plain copy onto the surface. But at the same time blend with each other...

Here's the test game I am using: 
[test--351guihires.zip](https://github.com/adventuregamestudio/ags/files/10299919/test--351guihires.zip)
It has a GUI with a button, both with the same "gradient" sprites. Key 1 toggle the GUI's graphic, Key 2 toggles the button. It's very easy to see the difference between expected and the current branch.

**Comment by ericoporto** [comment] 2022-12-25 13:21
Uhm, I wonder if it makes sense testing this in AGS4 context, just to see
- rotation is indeed working (from previous PR)
- existing blendmodes are working

**Comment by ivan-mogilko** [comment] 2022-12-25 14:00
> I wonder if it makes sense testing this in AGS4 context, just to see

What for? My intent is to fix the transparency issue in 3.6.0.

**Comment by ivan-mogilko** [comment] 2022-12-25 19:03
> Uhm, I wonder if it makes sense testing this in AGS4 context, just to see
> 
> * rotation is indeed working (from previous PR)
> * existing blendmodes are working (we can fix them later, but just to be aware)

I don't see why rotation would not work, if it would be about rotating a single texture - that is what it currently does easily.
As for blendmodes, tbh I would ignore these for now, if they would allow me to fix this problem in 3.6.0. Perhaps they may be reimplemented using shaders in ags4 (iirc some of them do not work properly in Direct3D anyway, and require some extra hacks).

**Comment by AlanDrake** [comment] 2022-12-25 19:05
> iirc some of them do not work properly

Correct, one can only do so much with single pass of blend modes. For perfect implementation we need to turn them into shaders.

**Comment by ivan-mogilko** [comment] 2022-12-25 21:17
Hmm, I finally realized that was thinking about whole blending of multiple textures in a wrong way (maybe a case of a mental block), and now fully understand what that separate alpha operation setting was about, and what the "premultiplied alpha" case is.

So, now I get it, these settings make it so that the render target has the alpha component corresponding to all the sprites summed together, which makes the final alpha applied to the render target's pixels **correct**.

But, because the sprite colors (RGB component) were combined *using sprite's src alphas* along the way, including the first pixels getting onto the render target itself, these colors, so to speak, already include alpha factor. This is what "premultiplied alpha" is, if i understand correctly.

And that's a problem, because now, when we finally draw the texture, previously used as a render target, itself on screen, all the colors will be multiplied by the alpha *again*, even though they were already multiplied by it.

Previously I found a solution for this: use a special blend mode for this texture, where the source color is taken as is, but the destination color is still multiplied by inverse of a source alpha:
```
direct3ddevice->SetRenderState(D3DRS_BLENDOP, D3DBLENDOP_ADD);
direct3ddevice->SetRenderState(D3DRS_SRCBLEND, D3DBLEND_ONE);
direct3ddevice->SetRenderState(D3DRS_DESTBLEND, D3DBLEND_INVSRCALPHA);
```
This works *perfectly*, but right until you apply GUI's Transparency to this texture: because it was not used when drawing onto the render target, its colors do not have it in them, and basically do not change, while the background colors increase. The result looks like the background begins to shine through the gui... sort of... anyway, it's wrong.

So, this is where I'm currently at.

NOTE: I cannot apply this GUI Transparency the sprites I draw onto render target, because then I will be back at the problem I am trying to fix with render targets in the first place.

**Comment by ivan-mogilko** [comment] 2022-12-25 22:23
> Hypothetically, it might work if there were a way to do this:

> multiply src color with transparency alpha
> multiply dst color with (transparency alpha * pixel alpha)

Oh, wow, looks like this is possible:

```
direct3ddevice->SetRenderState(D3DRS_BLENDFACTOR, D3DCOLOR_RGBA(alpha, alpha, alpha, 255));
direct3ddevice->SetRenderState(D3DRS_BLENDOP, D3DBLENDOP_ADD);
direct3ddevice->SetRenderState(D3DRS_SRCBLEND, D3DBLEND_BLENDFACTOR /*D3DBLEND_ONE*/);
direct3ddevice->SetRenderState(D3DRS_DESTBLEND, D3DBLEND_INVSRCALPHA);
```

**Comment by ivan-mogilko** [comment] 2022-12-26 21:23
Alright, I updated with fixing OpenGL's blending, and fixing Direct3D failing to reset device when window size/mode changes.
https://github.com/ivan-mogilko/ags-refactoring/tree/360--guitexturerenderfix3

I think this resolves the issue, except maybe some minor things that we did not notice yet.

I will be tidying the code and making proper PR now.

**Closed** 2023-01-01 21:11 UTC
Labels: type: bug, context: graphics
