### ISSUE TITLE
replace sprite from source confirm dialogue

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#794] opened 2019-05-27 22:08 UTC
when replacing a sprinte from source AGS shows a popup window that tells you everything is alright.
Well, this is my usual expectation for everything to be alright, so I'd prefer it when AGS only reports errors when replacing from source and NOT show that dialog that I have to click away. It is just convenience to have one less click on frequently used operations.
This probably applies to a lot of AGS operations but this stood out. probably also for other sprite editor operations and image replacings, if this is an easy fix I'd start with listing wherever this appears....

**Comment by ericoporto** [comment] 2019-05-29 04:01
I think the problem is if you do a minor fix in a sprite, there is no visual feedback that the sprite was successfully updated. So something should show somewhere saying that thing you did was ok (flash green, write in a status bar, some indication...). I agree a message box with an ok is annoying, but I just wanted to state what was the rationale I imagined for it - from being fixing a ton of minor details these days...

**Comment by morganwillcock** [comment] 2019-06-13 23:15
I'm pretty sure that the new sprite import (in 3.5) doesn't use a message box if nothing has gone wrong. I also find lots of message boxes very annoying, mainly because of the accompanying sound effect, so I've tried to remove them where I can.

The reason that the design is so reliant on these is because the Editor doesn't accommodate doing anything in parallel and so you'd typically need something (like a message box) to indicate the difference between the editor finishing doing something or still doing something. The new progress bar is a bit of hack and only its bar gets repainted, but it good enough to see that your import has finished.

**Comment by tzachshabtay** [comment] 2019-06-14 01:20
> I also find lots of message boxes very annoying, mainly because of the accompanying sound effect, so I've tried to remove them where I can.

Untested, but from what I read if you show a message box without an icon (i.e `MessageBoxIcon.None`) it won't make the sound effect.

Of course, the sound effect is not the only reason message boxes are annoying, it's the general interruption of your workflow. In case the message box is still needed, though, as a general solution I like the "Don't show this again" checkbox.
You'll need to [implement your own dialog for that](https://stackoverflow.com/questions/33962193/create-a-message-box-that-user-can-choose-to-dont-show-it-again), but then as a bonus, you can have icons AND no sound.

**Comment by ivan-mogilko** [comment] 2019-10-24 18:40
> I'm pretty sure that the new sprite import (in 3.5) doesn't use a message box if nothing has gone wrong.

So, this covers user suggestion then, correct?

**Comment by ivan-mogilko** [comment] 2019-10-26 19:14
Should be fixed in 3.5.0.

**Closed** 2019-10-26 19:14 UTC
Labels: res: in consideration, type: enhancement, what: editor
