### ISSUE TITLE
Editor, Feature Request: isometric and vanishing-point directional movement.

### ISSUE THREAD

**Issue by sschroeder256** [adventuregamestudio/ags#1061] opened 2020-04-29 02:22 UTC
I'd like to provide a simple user friendly way to modify the directional keyboard inputs on a room-by-room basis. My goal is to have a system where users draw lines to indicate how the character moves, in a similar manner to how users currently specify the Edges using the EdgesEditorFilter. With these lines users could specify an isometric direction for their keyboard inputs, or a direction towards a vanishing point at the intersection of two such lines.

For example, in the following game:
![1 3KkmHtAkXsOGBzcUoW3YoQ](https://user-images.githubusercontent.com/190336/80554977-dcc4a600-899c-11ea-9c60-9a9fcff03d62.gif)
The player's vertical inputs follow the perspective of the room, but that direction is interpolated based on the location in the scene.

I'd propose a "WalkDirectionEditorFilter". Users could drag up to two deletable lines from the left or right of the screen that act as guidance for the up/down direction. With no lines, the character walks up and down as normal. With a single line, the character's up/down direction is parallel to the line. With two lines, the character's up/down direction is towards or away from the lines' intersection. Users could perform the analogous actions with lines from the top or bottom of the screen created to modify the left/right directions analogously. Users could not create more than two lines for each cardinal direction pair (up to 4 total), and could delete lines to restore base functionality.
The default would be to have no lines present, so that all current games would experience no changes.

**Comment by ivan-mogilko** [comment] 2020-04-29 11:22
Is there anything that prevents from simply scripting this, without adding a specialized editor and engine mode?
Keyboard movement itself is not a part of the engine, in the default (now "Sierra-like") template it is a module. In script you can already detect input, and command character to Walk into coordinates, which could be calculated using vector algebra in a same way as you've described.

**Comment by sschroeder256** [comment] 2020-04-29 13:49
No, there isn't anything that would prevent a user from having a script they make that has the desired in-game result here. I had wanted to have the visualization method just to make it faster since it's something I'd probably do for a lot of rooms, and that it might make it easier for others too; But since keyboard movement isn't part of the engine, it sounds to me like this just isn't the way to go about doing this in AGS.

**Comment by ivan-mogilko** [comment] 2020-04-29 14:08
There may be a sense in idea of having a room filter for design purposes too. Unfortunately, I do not remember if editor plugin API supports adding custom filter, if it was that could be a solution.

Also, in the past someone was suggesting a new type of "helper object",  - a point in the room, with edit mode for creating and setting them. According to this idea these points could be used as coordinate references, instead of hard-coding them in script.
Perhaps this idea may be developed further into geometric shapes.

**Comment by sschroeder256** [comment] 2020-04-29 14:38
Taking a cursory glance at the plugin, I don't think I understand it enough to be able to comment on how possible that is.
That latter idea sounds like it could have some good uses, and be pretty versatile.

**Comment by fernewelten** [comment] 2020-04-30 02:40
As I understand isometric perspective, as the term seems to be understood in the gaming world, its "tiles" are angled by 30 ° (or sometimes, with raster graphics, by 26½ °). See, for instance, https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Freecol_095_05.jpg/1280px-Freecol_095_05.jpg

Thus the characters that walk or pathfind “isometrically” neither do 45 ° nor 90 °, they do something "in between". 

To reproduce this isometric perspective properly in AGS, it wouldn't be enough to warp perspective lines in backgrounds. One would also have to modify the moving/pathfinding algorithm to embrace 30° and 60 ° angles instead of the standard 45° / 90 ° angles. I don't think that a module can do this on its own, without engine additions.

**Comment by sschroeder256** [comment] 2020-04-30 12:53
Isometric may have been a poor choice of words then. What I had intended only to mean was moving parallel to a vector other than "up", rather than towards or away from a vanishing point.

**Comment by messengerbag** [comment] 2020-04-30 13:42
> One would also have to modify the moving/pathfinding algorithm to embrace 30° and 60 ° angles instead of the standard 45° / 90 ° angles.

There's no pathfinding involved here. With keyboard movement, the character moves in a straight line until it reaches an obstacle, and then stops. That straight line can in principle be at whatever angle you want, and could perfectly well be calculated and set in the module.

There is the issue of assigning the right directional view to the character. I think if you use 8 directions (separate diagonal loops) it should all work out in isometric, but if not there are workarounds (lock the view, overwrite the animation loops).

It has previously been suggested to add a property that would let users define the movement angles for which the various directions will be applied, which would also solve that.

**Comment by sschroeder256** [comment] 2020-04-30 16:16
> There is the issue of assigning the right directional view to the character.

That's a very good point, I wasn't able to find the script named like "eMouseMove" to see what exactly AGS does right now, are those mouse scripts in a strange place?

**Comment by AlanDrake** [comment] 2020-09-26 14:37
I'm closing this ticket since the request is more befitting of a module rather than a editor feature.

**Closed by AlanDrake** 2020-09-26 14:37 UTC
