### ISSUE TITLE
New Compiler: Errors and unexpected behaviors

### ISSUE THREAD

**Issue by AlanDrake** [adventuregamestudio/ags#1167] opened 2021-01-13 21:06 UTC
I encountered a couple of issues with the compiler so far:

- [x] blank room scripts throw an exception
- [x] `String GetAchievementName(Achievements achievement)` was recognized as "String " with an extra space, thus throwing an error if the function is imported in the header
- [x] `this` is now a reserved word and can't be used as a function parameter (check if it was done on purpose)
- [x] With a `String buffer[20];` we'll get a `Null pointer referenceed` when trying to determine if `buffer[0] != null`
- [x] `import String* GetAchievementName(Achievements achievement);` compiles, but used to throw an error saying `Invalid use of '*'`
- [x] the new compiler should default to False, until we're sure it's safe
- [x] `Cannot write to readonly 'player'` error with the following `player.InventoryQuantity[iKey.ID] = 0;`
- [x] `obj.Graphic++;` now throws an  `Expected an expression, found ';' instead`

**Comment by AlanDrake** [comment] 2021-01-13 21:33
I also got this error when tryng to run the game, after the compile. It did not happen when building the EXE.
```---------------------------
Adventure Game Studio
---------------------------
A serious error occurred and the AGS Editor may now be in an unstable state. You are STRONGLY ADVISED to shut down the editor and restart it. Before saving your work, make a backup copy of your game folder in case any data has been corrupted.


Error: System.Xml.XmlException: The character '', with hexadecimal value 0x03, is not valid. Row 4, position 7.
   in System.Xml.XmlTextReaderImpl.Throw(Exception e)
   in System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   in System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   in System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   in System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   in System.Xml.XmlTextReaderImpl.ParseElementContent()
   in System.Xml.XmlTextReaderImpl.Read()
   in System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   in System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   in System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   in System.Xml.XmlDocument.Load(XmlReader reader)
   in System.Xml.XmlDocument.LoadXml(String xml)
   in AGS.Editor.NamedPipesEngineCommunication.MessageSenderThread()
   in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()```

**Comment by ivan-mogilko** [comment] 2021-01-13 22:03
> import String* GetAchievementName(Achievements achievement); compiles, but used to throw an error saying Invalid use of '*'

This might be correct, as String is in fact a pointer to managed object.

**Comment by ivan-mogilko** [comment] 2021-01-13 22:05
@fernewelten

**Comment by ivan-mogilko** [comment] 2021-01-13 22:58
The big exception is most curious, because I was successfully compiling my games with the new compiler many times before.
It could be some other change affected this.

**Comment by ivan-mogilko** [comment] 2021-01-13 23:20
So, I found out that the exception is happening if you have an empty script - any script. In such case new compiler gets into an infinite loop and keeps allocating memory for this script over and over until memory alloc fails.

**Comment by rofl0r** [comment] 2021-01-13 23:42
> This might be correct, as String is in fact a pointer to managed object.

as i understood String was in the past roughly equivalent to `typedef managed_thing_whatever_behind_the_scenes* String;`, i.e. a typedef to a pointer, so using `String*` would be equivalent to `managed_thing_whatever_behind_the_scenes**`.

btw i recently added support for full-blown `#if' directive parsing to ascc's preprocessor based on the latest C++ preprocessor version in ags git history, maybe this would be interesting to merge back into ags. it supports unlimited nesting of parens, `defined(macro)`, all operators supported by C, `#elif`, `#else`, etc. i used it to support AGS 2.61 era stuff in agsdefns.sh like so `#if defined(AGS_SCRIPT_COMPAT_v330) || SCRIPT_API <= 261000`.

**Comment by ericoporto** [comment] 2021-01-13 23:52
For now the preprocessor code is in C# because it's used in the Editor for providing proper autocomplete when coding. 

See: https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.CScript.Compiler/Preprocessor.cs

I am not sure, but if there's a c++ preprocessor I don't think it's used. :/

**Comment by ivan-mogilko** [comment] 2021-01-14 00:15
> as i understood String was in the past roughly equivalent to typedef managed_thing_whatever_behind_the_scenes* String;, i.e. a typedef to a pointer, so using String* would be equivalent to managed_thing_whatever_behind_the_scenes**.

Not quite, the String type was declared with a special keyword that made compiler ignore the abscence of *, so it was sort of adding * for the user. If I understand correctly, the new compiler does this for all types, which also may mean it allows to use * with String.

Regarding preprocessor changes, it's best to discuss this separately, to keep this thread for aforementioned bugs.
I do not know much about C++ preprocessor myself.

**Comment by fernewelten** [comment] 2021-01-14 00:37
- blank room scripts throw an exception
    - This is certainly a bug. I'll look into it.
- `String GetAchievementName(Achievements achievement)` was recognized as `"String "` with an extra space, thus throwing an error if the function is imported in the header
    - This ought to work, and the blank after "String" shouldn't be at the core of the trouble. So I'd like to know more about that error. Just what exactly does the compiler complain about? 
- `this` is now a reserved word and can't be used as a function parameter (check if it was done on purpose)
    - AFAICR, yes. I'll look into the logic of this.
- With a `String buffer[20];` we'll get a Null pointer referenced when trying to determine if buffer[0] != null
    - This would be a bug.
- `import String* GetAchievementName(Achievements achievement);` compiles, but used to throw an error saying Invalid use of '*'
    - Yes, this would work: `String` has an implicit following `*`, so when the compiler finds an _explicit_ `*` it will simply nod “Yes, I know it's a pointer type” and carry on compiling. 
- the new compiler should default to False, until we're sure it's safe
     - We can easily change the default if we reach consensus about it. However, just what do you mean by “being sure” it's safe? What would be an actionable criterion for that?

**Comment by fernewelten** [comment] 2021-01-14 00:46
As far as I know, _all_ preprocessing is done within the Editor. There are functions and stubs in the C++ compiler directory for preprocessing, but those aren't called from anywhere.

**Comment by fernewelten** [comment] 2021-01-14 00:59
>`Error: System.Xml.XmlException: The character '�', with hexadecimal value 0x03, is not valid. Row 4, position 7`

On a blind, wild guess, the compiler might perhaps have generated this on encountering a string with a C string backslash combination, say, `"foo\3bar"` or `"foo\x03bar"`. Otherwise, I'd need more context to go on.

**Comment by rofl0r** [comment] 2021-01-14 05:39
> As far as I know, all preprocessing is done within the Editor. There are functions and stubs in the C++ compiler directory for preprocessing, but those aren't called from anywhere.

correct, however when i started with agscc project i went way back in the commit history and dug out the old C++ preprocessor code and plugged it in, since i can't run C# code.

**Comment by AlanDrake** [comment] 2021-01-14 11:05
> 
> 
> > `Error: System.Xml.XmlException: The character '�', with hexadecimal value 0x03, is not valid. Row 4, position 7`
> 
> On a blind, wild guess, the compiler might perhaps have generated this on encountering a string with a C string backslash combination, say, `"foo\3bar"` or `"foo\x03bar"`. Otherwise, I'd need more context to go on.

I'm not sure what's happening here, I just tried on another version of the project, I got  the same error but with a 0x12 character, then the editor crashed, I reopened it and now it no longer throws that exception when running the game with F5.

The compiling ran fine, so I have no idea why running the game from the editor with the new compiler could cause this, why does the editor need to read xml to run the game? Maybe for getting the paths to data? Could it be that the memory was corrupted due to the other issues?

**Comment by ivan-mogilko** [comment] 2021-01-14 12:20
Please note that I set new compiler to be off by default, but that's rather for convenience of other users, since it was causing strange crashes. Maybe I should not have. It's still essential to regularily test it on various scripts, otherwise it will never be complete. All these bugs were found only because it was on by default, and a person tried to compile existing project in the new version.

**Comment by ivan-mogilko** [comment] 2021-01-14 12:48
> this is now a reserved word and can't be used as a function parameter (check if it was done on purpose)

IMO that's a correct thing, if it's a reserved word its use should be restricted. The original compiler was supposed to do the same.

**Comment by ericoporto** [comment] 2021-01-14 14:46
@AlanDrake have you tried getting the  `System.Xml.XmlException` running AGS through VS debugger? It seems the problem is in some data the Editor has to send through its debug interface with the Engine (the named pipes on the stack).

**Comment by AlanDrake** [comment] 2021-01-14 15:08
@ericoporto I wanted to do that... but it's not breaking today, even though I'm using the same compiled code from yesterday with the same project. 

@ivan-mogilko Morally, we should deceive users into opting in, but I guess we can switch it back once we confirm that our own games are all running proper (and maybe Dave's one too). It's just that if we want to promote this version, it should at least work as expected out of the box.

**Comment by AlanDrake** [comment] 2021-01-14 15:46
Added another issue:
`player.InventoryQuantity[iKey.ID] = 0;` this throws the following error `Cannot write to readonly 'player'`

**Comment by fernewelten** [comment] 2021-01-14 18:00
@AlanDrake This might be a buffering issue. 

Let's suppose that some changes come rolling into version 4.0, so the Editor does things in a different way than before. But the act of installing changes doesn't invalidate the buffers. So the already existing projects contain bogus entries that the Editor considers to be valid. 

When generating those projects with F7, the system balks and crashes. At that time, the Editor notices that its files have been corrupted, so it invalidates them. Thus on redoing the generation, everything is generated from scratch and the bugs miraculously fade away.

**Comment by AlanDrake** [comment] 2021-01-14 18:05
@fernewelten You were right, sorry. I was certain I had tried a full rebuild, but I hadn't;

**Comment by AlanDrake** [comment] 2021-01-14 18:11
@fernewelten Alas, I had forgotten I was compiling with the old compiler, and now another suprise came about:
`obj.Graphic++;` is no longer valid

**Comment by fernewelten** [comment] 2021-01-14 22:11
> `obj.Graphic++;` is no longer valid (`Expected an expression, found ';' instead`)

Fixed in #1174

**Comment by fernewelten** [comment] 2021-01-14 22:53
> `player.InventoryQuantity[iKey.ID] = 0;` this throws the following error `Cannot write to readonly 'player'`

`player` is a readonly pointer. The thing pointed to is _not_ readonly, but the compiler treats it that way. Wrongly. I'm currently fixing this.

**Comment by fernewelten** [comment] 2021-01-16 17:29
To summarize:

> * [ ]  `String GetAchievementName(Achievements achievement)` was recognized as "String " with an extra space, thus throwing an error if the function is imported in the header

Should be fixed in PR #1173.

> * [ ]  With a `String buffer[20];` we'll get a `Null pointer referenceed` when trying to determine if `buffer[0] != null`

Should be fixed with #1172, #1173

> * [ ]  `import String* GetAchievementName(Achievements achievement);` compiles, but used to throw an error saying `Invalid use of '*'`

This is intended: `String` has an implicit following `*`. Whenever an explicit `*` follows in code, the compiler will take this as an explicit corroboration of that implicit `*`. It doesn't take this as _another_ following `*`.

> * [ ]  `Cannot write to readonly 'player'` error with the following `player.InventoryQuantity[iKey.ID] = 0;`

Should be fixed in #1178

> * [ ]  `obj.Graphic++;` now throws an  `Expected an expression, found ';' instead`

Should be fixed in #1174

**Comment by AlanDrake** [comment] 2021-01-16 18:12
@fernewelten  Almost everything works now, except `if (buffer[j] != null)` which still throws the null pointer error

**Comment by fernewelten** [comment] 2021-01-17 03:52
> except `if (buffer[j] != null)` which still throws the null pointer error

Should be fixed in #1179.

AFAICS, the troublemaker was the `!=`. The compiler has generated a _string_ comparison opcode for that. But with this opcode, the Engine throws a null pointer error unless both operands are non-null. So a normal (non-string) comparison opcode would be the correct choice for comparing a string to `null`.

**Comment by AlanDrake** [comment] 2021-01-17 12:29
Okay, with the last fix all my test cases seem to be working according to spec.  I'll try to get others to test their games.

**Comment by ericoporto** [comment] 2021-01-17 15:54
@AlanDrake if you pass this to other people, bear in mind the default has not been switched back to the new compiler. Maybe it's best to switch back before sending to others.

**Comment by AlanDrake** [comment] 2021-01-17 16:27
I'm aware of that, anyway everyone was seemigly offline today, I guess they had better things to do this sunday.

A note about the templates, some of the use `static` stuff, so the getter/setter functions will need to be updated with the static qualifier (which doesn't compile on old compiler)

**Comment by ivan-mogilko** [comment] 2021-01-18 02:15
> A note about the templates, some of them use static stuff, so the getter/setter functions will need to be updated with the static qualifier (which doesn't compile on old compiler)

This is important, we should create a ags4 branch for [template sources](https://github.com/adventuregamestudio/ags-template-source) and [template package](https://github.com/adventuregamestudio/ags-templates) repositories. BTW I don't remember if CI takes templates from master all the time, or looks for branch with name identical to code branch?

**Comment by ericoporto** [comment] 2021-01-18 08:22
Macros are not part of ags compiler, so you mean the Editor preprocessor has to create these define macros from the options selected in general settings.

**Comment by ivan-mogilko** [comment] 2021-01-18 08:53
> Macros are not part of ags compiler, so you mean the Editor preprocessor has to create these define macros from the options selected in general settings.

I mean that compiler could return some name or value, which is then given to preprocessor as macro..

**Comment by rofl0r** [comment] 2021-01-18 09:52
ascc does this:
```c
ccSetSoftwareVersion("3.5.0.12");
add_macro("__ASCC__", "3");
add_macro("__ASCC_MINOR__", "5");
snprintf(abuf, sizeof abuf, "%s000", req_api);
add_macro("SCRIPT_API", abuf);
```c
in short, it defines SCRIPT_API as the requested API level multiplied by 1000, e.g. SCRIPT_API 350000, this allows to check for version >= or <= etc using the `#if` support i added to cpp (the multiplication is done because recently a SCRIPT_APIv3507 was added to agsdefns.sh, so there is more space for minor revisions), as well as defining `__ASCC__` and `__ASCC_MINOR__` just like GCC does.
it would be great if the compiler in ags could do a similar or identical thing, so we don't diverge too much. however it should use a different macro instead of `__ASCC__` so a user can differentiate whether he uses ascc or official compiler.

**Comment by ericoporto** [comment] 2021-01-18 11:45
@ivan-mogilko instead of an id, isn't just a define like:
`AGS4_COMPILER`, and if it's not defined, assume it's compiling on legacy? Also I much prefer to reference the compiler made by Fernewelten as the AGS compiler and the previous one as legacy. Labeling one as experimental will reduce it's usage.

The thing with something like `__COMPILER_ID__` is it will fail on ags3 - unless people simultaneously check for it and that is indeed ags3.

**Comment by ivan-mogilko** [comment] 2021-01-18 11:56
I edited my comments above, and mentioned that it should not be actually a compiler's name, but a syntax id, because it does not really matter how the compiler is called, what matters is what variant of syntax it supports.
This may be similar to what you say about feature test. I don't know if it's worth to add one macro for each separate feature, as we do not have that much of variants as of now.

(It may define compiler's name too just in case, maybe for debugging purposes, like printing what compiler was this script compiled with)

**Comment by rofl0r** [comment] 2021-01-18 16:00
if there's [one thing i learned from musl development](https://www.openwall.com/lists/musl/2013/03/29/13) then it's that it's much better to test for features rather than product names or versions. POSIX came to the same conclusion, so e.g. unistd.h is supposed to expose macros that show that a certain feature is implemented:

http://manpages.org/unistdh

> If a symbolic constant is defined with a value greater than zero, the option shall always be supported when the application is executed. All headers, data types, and functions shall be present and shall operate as specified. 

e.g.
> _POSIX_IPV6
>    The implementation supports the IPv6 option. If this symbol has a value other than -1 or 0, it shall have the value 200112L.

**Comment by ivan-mogilko** [comment] 2021-01-18 16:39
What would this mean in practice for our case?

**Comment by rofl0r** [comment] 2021-01-18 19:19
in this specific case, where one compiler requires a different syntax than the other, and the user wants to be able to compile his code with both, we could have for example

AGS_COMPILER_REQUIRES_STRING_STAR

for a compiler version where String needs to be declared like `String*`.
i don't know in detail how the new compiler differs exactly, but something along those lines. there's even precendece, the old compiler seems to define a macro called `AGS_SUPPORTS_IFVER`.

though tbh, i think the new compiler should just accept the usual syntax.

**Comment by fernewelten** [comment] 2021-01-18 22:05
The new compiler does accept the old compiler's syntax. The one difference that I'm aware of seems to be an error of the old compiler. 

Namely, if a struct contains a `static` attribute – which of course is an attribute that does __not__ depend on a specific object – then the old compiler mandates that the getter and setter functions of that attribute must still be object-dependent.
```
struct FOO {
    import static readonly attribute int BAR;
};

int get_BAR(/* static */ this FOO *)
{ … }
```
Moreover, those getters and setters must be defined using the `int get_NAME(this STRUCT *)` syntax, or else you get strange error messages. 

OTOH, the new compiler really rewrites attribute declarations into the corresponding setter and getter declarations. As soon as the struct is closed, the setters and getters become indistinguishable from any struct functions that are defined explicitly; they behave in exactly the same way.  With the struct definition above, the compiler “sees”:
```
struct FOO {
    import static int get_BAR();
};
```
Thus, `static` attributes result in `static` getters and setters, non-`static` attributes result in non-`static` getters and setters. When the compiler encounters the following later on, it becomes unhappy and complains that a `static` function has been re-defined as non-`static`.
```
int get_BAR(this FOO *)
{ … }
```

Note that the generated Bytecode is still compatible between compilers AFAICS: Whether a static or a non-static struct function is called, the stack is loaded in exactly the same way.

**Comment by ivan-mogilko** [comment] 2021-01-31 16:28
All errors reported in the ticket were fixed, so closing this.

If more errors are found new tickets should be opened.

**Closed by ivan-mogilko** 2021-01-31 16:28 UTC
Labels: ags 4, context: script compiler
