### ISSUE TITLE
Refactor to Improve ScriptOverlay -> ScreenOverlay link logic performance

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#2042] opened 2023-06-21 01:43 UTC
**Describe the problem**
Originally, AGS had a limited number of Overlays that could be on screen, and it holds the ScreenOverlays in a vector, so the ScriptOverlays don't hold a direct reference (as these references can change), and the way is done is for each Script API access in the ScriptOverlays we look through every ScreenOverlays until we find the one that matches. This is alright, but once we have some big number of Overlays this can be slow. 

Still, Overlays aren't that used in the majority of AGS games so far, so this isn't a big priority and hasn't been a problem.

**Suggested change**
Right now each property you change you iterate through all indexes, which can make this to add up. There is probably some refactor that could simplify this access, but we use ScreenOverlays to render other elements too, so any refactor may touch other logic.

This is a very code specific enhancement request.

**Comment by ivan-mogilko** [comment] 2023-06-21 15:42
Ugh! to be honest, I have no idea why I did not address this immediately after removing overlay limit, in 3.6.0. Somehow this fell out of my mind.

This problem must be clarified though.

First of all, ScriptOverlay holds an overlay's ID, but if that were a container's key (vector's index) that would not be an issue. The issue is that this ID is an arbitrary number not corresponding to overlay's storage index. And there's no correspondence between ID and a storage index whatsoever.

First, this creates a performance problem when referencing an overlay from ScriptOverlay when a property has to be read or written. This problem may be a priority problem when you have a "pool" of thousands of *precreated* overlays to manipulate dynamically. I believe this is currently addressed by #2041.

But this is not the only problem.

Another thing is adding and removing overlays.

1. First of all, they are added/removed using standard push_back/erase in vector, which means that vector contents get moved in memory every time. ScreenOverlay is not a big struct (few ints and a bitmap pointer), but regardless this creates an overhead.

2. Secondly, if you look at the [`add_screen_overlay_impl`](https://github.com/adventuregamestudio/ags/blob/169320f1b54b7f778b118f2cabd93d580286e1b0/Engine/ac/overlay.cpp#L417-L422), you may notice that the engine is trying to find a free ID to assign for the new overlay. This is done in a horribly inefficient way, where it will iterate all possible ID values starting with, and *for each ID* it will iterate over the vector looking whether this ID is used.

---

What may be a solution here?

1. Store ScreenOverlays in a (hash)map.
2. If map will create complications for any reason, then keep them in vector, but at least don't erase the elements and replace with invalid (empty) overlay object. Added overlays will be placed in available empty slots first, and new slots pushed only if the vector is full.

The second variant will look similar to how the ManagedPool is implemented currently:
https://github.com/adventuregamestudio/ags/blob/169320f1b54b7f778b118f2cabd93d580286e1b0/Engine/ac/dynobj/managedobjectpool.cpp#L146-L161
It uses a `available_ids` stack, which contains a list of empty indexes in the middle of a vector.

Similar "available_ids approach may be used for assigning an overlay ID. Although, if doing a serious refactor, I would question why the IDs are non-sequential, and there's a need to have OVER_CUSTOM offset for non-speech overlays equal to 100.

**Comment by ericoporto** [comment] 2023-06-22 15:20
Ahn, just in case I missed, is there a sort in screenover so they change index every frame? Because if they have this may have something to do on why things are in this way.

**Comment by ivan-mogilko** [comment] 2023-06-22 18:49
> Minor question of refactoring, does script overlay extending screen overlay makes sense? As in there wouldn't be any need for references as it would be the same thing.

This is not a minor question, this is an essential question, and this relates to everything else too.

The reason they are divided is this: the ScriptOverlay is a script object, it is stored in script's managed pool and exists so long as the script refs to it exists, and disposed when there's none. ScreenOverlay is an actual object, it may exist without being in script, and removed or kept according to its own logic.

**Comment by ivan-mogilko** [comment] 2023-06-22 18:51
> Ahn, just in case I missed, is there a sort in screenover so they change index every frame? Because if they have this may have something to do on why things are in this way.

If that was a problem, this could easily be solved by having a separate storage for sorting, storing either pointers to overlays, or their indexes.

**Comment by ivan-mogilko** [comment] 2023-06-22 19:10
> Minor question of refactoring, does script overlay extending screen overlay makes sense? As in there wouldn't be any need for references as it would be the same thing.

This is not a minor question, but an essential question.
They are separated, because they have different lifescope and memory management. ScriptOverlays represent a script object, which exists so long as there are references to it. ScreenOverlay is an internal engine object, which may or may not be accessed in script, and some of these do not rely on being addressed in script at all.

*Maybe* this may be changed to have only a script object. I cannot answer right now, I once tried to think about this and investigate what happens if we merge all these script classes with actual objects, but for some reason keep forgetting. Probably, my memory is not good. I need to think again and write that down.
I know that won't be a simple change, because there are things that rely on how it works currently.

> Ahn, just in case I missed, is there a sort in screenover so they change index every frame? Because if they have this may have something to do on why things are in this way.

They are not sorted for drawing in their own storage, if that's what you mean. If that were a problem, it could easily be solved by sorting their pointers, or their indexes.

**Comment by ericoporto** [comment] 2023-06-22 23:02
Thank you for the explanations. Just to explain what I am trying to get at, I was trying to figure it out what kind manipulations can be done with screenover, because it's exposed, some manipulations use it directly and others are through calling overlay methods from different places.

The reason for this is because I was thinking if I could remove the per cal id->index update to something like once per frame - e.g. something even cheaper than once per index change. Anyway, I will try to just work from the suggested implementation in the PR comment.

**Comment by ivan-mogilko** [comment] 2023-06-22 23:16
> The reason for this is because I was thinking if I could remove the per cal id->index update to something like once per frame - e.g. something even cheaper than once per index change. 

You may completely remove the need for this update, if one of the solutions is applied, as was mentioned above:
> * Store ScreenOverlays in a (hash)map, where ID is the key.
> * keep them in vector, but at least don't erase the elements and replace with invalid (empty) overlay object. Added overlays will be placed in available empty slots first, and new slots pushed only if the vector is full.

The second option may be sped up by having a record of free indexes; that's an optimization option, but not required for this to basically work.

**Comment by ivan-mogilko** [comment] 2023-06-23 18:03
In regards to this:

> Also, if doing a serious refactor, I would question why the IDs are non-sequential, and there's a need to have OVER_CUSTOM offset for non-speech overlays equal to 100.

I suppose we may get rid of fixed special overlay IDs for blocking speech etc, if we instead request the overlay's ID and save it in  variables, somewhere in GameState. Then we use that variable's value instead of OVER_TEXTMSG, OVER_COMPLETE, and so forth.

**Comment by ericoporto** [comment] 2023-06-23 18:41
#2041 is merged so the performance improvement to be gain from further improvements is lower now, I think this can be closed

**Comment by ivan-mogilko** [comment] 2023-06-23 19:06
I'd like to look into this further, improving the storage and finding ID for a new overlay.

**Comment by ivan-mogilko** [comment] 2023-06-23 19:21
I made a test game in order to illustrate the remaining problem:
[test--361-overlayperformance.zip](https://github.com/adventuregamestudio/ags/files/11851527/test--361-overlayperformance.zip)
[test--361-overlayperformance-project.zip](https://github.com/adventuregamestudio/ags/files/11851528/test--361-overlayperformance-project.zip)

On startup it creates 1000 overlays, then starts randomly moving them around, thus accessing X,Y properties.
On "Space" press it toggles the "recreation" mode, where it deletes 1 random overlay and creates new 1 overlay each game frame.

Testing with 3.6.1.1 and a version with fixed performance, in the infinite fps mode:
Engine | Changing properties | Recreating
---|---|---
3.6.1.1 | 600 | 560
new version | 650 | 600

It looks like the deletion/creation of new overlays drop down by about same fps amount as accessing properties.

**Comment by ivan-mogilko** [comment] 2023-06-23 19:42
Perhaps I should move this to another ticket though, since this is about ScriptOverlay -> ScreenOverlay link

**Closed by ivan-mogilko** 2023-06-23 19:42 UTC
Labels: type: enhancement, context: performance

**Comment by ivan-mogilko** [comment] 2023-06-30 18:34
@ericoporto in regards to merging classes, there's a good existing example in the old scummvm port attempt, which fork we still have here: https://github.com/adventuregamestudio/scummvm

In this fork every game class is derived from ScriptObject, which is an equivalent of what is known as ICCDynamicObject interface in our code. ScriptObject exposes reference counting directly, without delegating this to managed pool (they have AddRef/DecRef methods).

I spent small amount of time reading the code, but from the looks of it, the code is still missing one important case: when the Overlay is getting disposed by loosing last reference in script. Unless I missed something, it does not properly remove overlay pointer from the engine's vector, which would result in engine crashing. But it might be possible to fix that by reworking Overlay's deletion and removal.

Supposedly, same system could be recreated in this engine too.
