### ISSUE TITLE
[AGS 4.0] Shift Right Click in a room only works when Object/Edges/Room submenu is selected

### ISSUE THREAD

**Issue by tarnos12** [adventuregamestudio/ags#1732] opened 2022-07-13 06:51 UTC
**Describe the bug**
When you shift right click it's supposed to show the menu option "Copy mouse coordinates to clipboard", it works fine when you select object/edges/room sub menu, but not for anything else.

**AGS Version**
4.0

**To Reproduce**
1. Open room and select Hotspots(or anything other than objects/edges/room)
2. Shift + right click in a room
3. Menu to copy coordinates doesn't appear

**Expected behavior**
Menu with "Copy mouse coordinates to clipboard" should appear when shift is being held when clicked.
Regular action like "Place New Object Here" should appear only if shift is not held down.

**Comment by ivan-mogilko** [comment] 2022-07-14 07:53
For me it works for all the area types (Hotspots, Regions etc).

It does not work for Characters, and also causes Objects' context menu appear for a split second before showing "Copy coordinates).

**Comment by tarnos12** [comment] 2022-07-15 06:59
Hotspots don't work if you select different tool(rectangle in my case, but probably applies to most of them)
Same for regions.
Also doesn't work when using Eraser.

Ideally when shift is being held down then any specific actions(create object, drawing with tools, eraser) should be ignored.

**Comment by ivan-mogilko** [comment] 2022-07-15 12:03
Actually, this may or may not be a duplicate of #1427 (need to re-read the older ticket, as it contained a longer discussion).

**Comment by ivan-mogilko** [comment] 2023-08-24 09:40
I will close this as essentially a duplicate of #1427.

As of this moment, judging on my tests, this works in most cases, but there's a remaining issue with the "Line" tool, where it randomly would still draw a line even though the context menu was called. This still has to be fixed.

I suggest to continue tracking problems with calling context menu in #1427.

**Closed by ivan-mogilko** 2023-08-24 09:40 UTC
Labels: type: bug, ags 4, context: ui/ux
