### ISSUE TITLE
Preprocessor: Adding whitespaces to #ifdef #endif statements causes the compiler to ignore them

### ISSUE THREAD

**Issue by 256colour** [adventuregamestudio/ags#593] opened 2019-01-24 16:03 UTC
Problem: The following statement causes the compiler (preprocessor?) to ignore the #ifdef and process AGS2Client.SetIntStat() even when AGS2Client_VERSION has *not* been defined.
```
#ifdef AGS2Client_VERSION
   AGS2Client.SetIntStat("Blah blah blah", GetVariable("Sidequests_Count"));
   #endif   <-- problem is here
```

Cause: The **three whitespaces** after #endif cause the preprocessor to ignore the entire IFDEF statement.

**Comment by rofl0r** [comment] 2019-01-25 01:09
i don't think that is correct.
if the preprocessor ignores `#` with proceding whitespace (which i doubt), it certainly doesn't make it ignore an ifdef statement on a previous line.

you can debug preprocessor stuff using `#warning foo` and `#error bar`
e.g. add this:
```c
#ifdef AGS2Client_VERSION
#warning "AGS2Client_VERSION is defined!"
#else 
#warning "AGS2Client_VERSION is NOT defined!"
#endif
```
just before the chunk you pasted and it will tell you what's really happening.

**Comment by ivan-mogilko** [comment] 2019-01-25 10:23
@rofl0r  this is about AGS Script, there is some bug in its preprocessor.

**Comment by rofl0r** [comment] 2019-01-25 14:47
oh. is there a specific reason you're not simply using the C preprocessor (or a library implementing it such as ucpp or mcpp) ?

**Comment by ivan-mogilko** [comment] 2019-01-25 17:48
Well... the preprocessor was already written when we got this code and no one took time to improve it. It was done in C# as an integral part of the Editor program, and it has its own additional commands.

**Comment by ivan-mogilko** [comment] 2019-01-25 19:32
When this project started there were suggestions on making a standalone game compiler. Perhaps if that happens preprocessor could also be replaced.

**Comment by ivan-mogilko** [comment] 2019-08-30 02:01
Well, this is awkward, don't remember anymore if I actually tested this myself earlier, but now when I do I cannot reproduce this bug.
Tested in several versions of AGS, from 3.2.1 to 3.5.0.

**Comment by ivan-mogilko** [comment] 2019-09-10 11:14
Upon further discussion (off github) it was revealed that the original user who noted this problem did a massive find/replace operation on script files with some separate program, and also script appears to be saved in UTF8 which is not supported by AGS compiler. My only guess atm is that they introduced an unconventional character(s) which were not recognized by compiler as whitespaces.

I'd like to close this now because the problem does not reproduce as described. Of course the source of problem could be the lack of unicode support in AGS which deserves its own ticket.

**Closed by ivan-mogilko** 2019-09-10 11:14 UTC
Labels: ags3, bug, editor, script compiler
