### ISSUE TITLE
Engine doesn't start on Raspberry Pi 

### ISSUE THREAD

**Issue by jagiella** [adventuregamestudio/ags#233] opened 2015-02-13 00:24 UTC
Compilation worked without any problem, but running the game engine inside the games folder of "A Golden Wake" demo I get the following error:

$ ags .
AGS: Adventure Game Studio v3.3 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
ACI version 3.3.3.0

AGS: *** ENGINE STARTUP ***
AGS: Reading config file
AGS: Initializing allegro
Unknown error initializing graphics subsystem.

**Comment by ivan-mogilko** [comment] 2015-02-13 08:25
Could you specify, which operating system is installed on the device?

**Comment by jagiella** [comment] 2015-02-13 08:49
I use the last available raspbian image (http://www.raspberrypi.org/downloads/) with the kernel and packages updated to their respective last version.

$ uname -a
Linux raspberrypi 3.18.6+ #754 PREEMPT Sun Feb 8 20:22:45 GMT 2015 armv6l GNU/Linux

Furthermore I tested several games available on http://www.adventuregamestudio.co.uk (A Golden Wake Demo, The Journey Down: Over the Edge, and Blackwell Epiphany Demo). All reproduce exactly the same error message. So I guess it's game independent and rather a problem of the engine or linked libraries (allegro?).

**Comment by jagiella** [comment] 2015-02-16 21:36
So anybody an idea what could cause the problem? Anybody running AGS on the raspberry pi?

**Comment by ivan-mogilko** [comment] 2015-02-16 22:19
Could you apply this patch and tell if it displays more detailed error message now?
http://www.mediafire.com/download/c730zvhptaih4eg/0001-Engine-display-allegro_error-when-Allegro-init-has-f.patch

**Comment by jagiella** [comment] 2015-02-17 08:35
Now the error message became the following

AGS: Adventure Game Studio v3.3 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
ACI version 3.3.3.0

AGS: *** ENGINE STARTUP ***
AGS: Reading config file
AGS: Initializing allegro
Unable to initialize Allegro.

**Comment by ivan-mogilko** [comment] 2015-02-17 08:53
Oh. So the library does not actually set any error message. My apologises, this seem to be wrong way to look.

I am afraid I am not much help here, I do not own Raspberry myself. I could try setting up a virtual machine and see if this problem will reproduce.

**Comment by tobihan** [comment] 2015-02-17 09:06
Only idea I have is that Allegro in Debian expects to have an Xserver
running. Do you have that?

**Comment by jagiella** [comment] 2015-02-17 09:22
Good point: Up to now I only tried to start AGS from Raspbian in console mode, i.e. no desktop environment loaded. In this case the Xserver should not be running. 

I will try out running AGS from desptop mode and report back if it behaves differently!

**Comment by ivan-mogilko** [comment] 2015-02-17 09:36
Oh. Right, Allegro uses X on Linux for drawing and input. :)

**Comment by jagiella** [comment] 2015-02-20 13:28
Alright, I made it running! :+1: If you want to start AGS from the command line (in non-desktop mode) you can use the following command.

$X & DISPLAY=:0 ags GAME_DIRECTORY

This starts the X-server, sets the display and starts the game :)

Now I have another issue nevertheless ;) The game is displayed as a tiny image at the center of my screen / tv. It seems like its displayed at a resolution of 320x240, although the console output suggests a resolution of 1920x1080. See yourself:

[1] 3246
_XSERVTransSocketOpenCOTSServer: Unable to open socket for inet6
_XSERVTransOpen: transport open failed for inet6/retropie:0
_XSERVTransMakeAllCOTSServerListeners: failed to open listener for inet6

X.Org X Server 1.12.4
Release Date: 2012-08-27
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-2-mx5 armv7l Debian
Current Operating System: Linux retropie 3.18.5+ #744 PREEMPT Fri Jan 30 18:19:07 GMT 2015 armv6l
Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708.boardrev=0xe bcm2708.serial=0xf95a209f smsc95xx.macaddr=B8:27:EB:5A:20:9F bcm2708_fb.fbswap=1 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait
Build Date: 10 December 2014  09:32:00PM
xorg-server 2:1.12.4-6+deb7u5 (Moritz Muehlenhoff <jmm@debian.org>)
Current version of pixman: 0.33.1
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	AGS: Adventure Game Studio v3.3 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2014 others
ACI version 3.3.3.0

AGS: *** ENGINE STARTUP ***
AGS: Reading config file
(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri Feb 20 13:09:19 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
AGS: Initializing allegro
FATAL: Module g2d_23 not found.
AGS: Setting up window
AGS: Initializing game data
AGS: Game data file: /home/pi/games/overtheedge/jdags.exe

AGS: Initializing TTF renderer
AGS: Initializing mouse
AGS: Checking memory
ci_find_file: cannot change to directory: Compiled
ci_find_file: cannot change to directory: Compiled
AGS: Initializing keyboard
AGS: Install timer
Checking sound inits.
AGS: Initialize sound drivers
AGS: Install exit handler
AGS: Initialize path finder library
AGS: Load game data
AGS: Game data version: 40
AGS: Requested engine version: 3.1.0.2
AGS: Game GUI version: 115
AGS: Over the Edge
AGS: Checking for disk space
AGS: Initializing MOD/XM player
AGS: Initializing screen settings
AGS: Device display resolution: 1920 x 1080
AGS: Game native resolution: 320 x 240 (32 bit) letterbox-by-design
AGS: Game settings: letterbox acceptable, side borders acceptable
AGS: Init gfx driver
AGS: Created graphics driver: Allegro/DX5
AGS: Supported gfx modes (32-bit):
	1920x1080;
AGS: Supported gfx modes (24-bit):
	1920x1080;
AGS: Initializing gfx filters
AGS: Requested gfx filter: None
AGS: Chosen gfx resolution: 1920 x 1080 (32 bit), game frame: 1920 x 1080
AGS: Applying scaling filter: None
AGS: Switching to graphics mode
AGS: Attempt to switch gfx mode to 1920 x 1080 (32-bit) fullscreen, game frame 1920 x 1080, gfx filter: None
AGS: Succeeded. Using gfx mode 1920 x 1080 (32-bit) fullscreen, game frame 1920 x 1080, gfx filter: None
AGS: Preparing graphics mode screen
AGS: Initializing colour conversion
AGS: Check for preload image
AGS: Initialize sprites
AGS: Set up screen
AGS: Initialize game settings
AGS: Prepare to start game
AGS: Audio is processed on the main thread
AGS: Checking replay status
AGS: Engine initialization complete
AGS: Starting game
AGS: Loading room 26

**Comment by tobihan** [comment] 2015-02-20 13:38
To scale the game closer to that resolution add the line

|gfxfilter=StdScale4

to the [misc] section of acsetup.cfg in the game folder.

Crimson, do you think there should be a hint that an X server is
required when Allegro fails to initialize in this way on Linux? On the
other hand, Allegro 4 has a Linux console mode, it's just deactivated in
Debian/Ubuntu (because the Allegro documentation does not recommend to
use it).
|

**Comment by jagiella** [comment] 2015-02-20 13:39
Using the rescaling command line option helps increasing the image size.

$ X &  DISPLAY=:0 ags --fullscreen --gfxfilter StdScale4 GAME_DIRECTORY

But unfortunately the game becomes incredibly slow. Almost unplayable on a Raspberry Pi with lots of sound glitches... Would there be a more efficient solution to strech the image without the need of a significant increase in computation time?

**Comment by tobihan** [comment] 2015-02-20 13:41
Lower your resolution. :)

**Comment by tobihan** [comment] 2015-02-20 13:43
Or, if you're up for a challenge, make the OpenGL drawing code that is
used on Android and iOS work on Linux.

**Comment by jagiella** [comment] 2015-02-20 13:48
Well, as Android is mainly based on Linux, that shouldn't be to much a deal, does it? :)

**Comment by jagiella** [comment] 2015-02-20 14:02
The scummvm port is performing quiet well in fullscreen on the Raspberry Pi. Wondering how they boost up their performance...maybe OpenGL as well.

**Comment by tobihan** [comment] 2015-02-20 14:09
Build system and display stuff (including OpenGL setup) are different
and the software drawing code that is currently used on Linux is of the
type that you better not touch if you don't have to. So you want to try it?

**Comment by ivan-mogilko** [comment] 2015-02-20 14:15
AGS software renderer is very much unoptimal and not suitable for high resolutions.
Making OpenGL work on Linux is what has to be done eventually. It is essential to at least perform game scaling using hardware acceleration.

**Comment by ivan-mogilko** [comment] 2015-02-20 14:19
@tobihan 
> Crimson, do you think there should be a hint that an X server is
required when Allegro fails to initialize in this way on Linux?

I can add a separate platform-dependant hint string to the message (Windows has one already).

**Comment by jagiella** [comment] 2015-02-20 14:24
So running the game on its native 320x240 resolution works quiet fast, but already scaling it just to double image size results in a tremendous slowdown. An other observation I made was, that al kind of image fadings (in or out) are extremly slow...even on the lowest resolution.

So using OpenGL and hardware acceleration would be a great thing to improve those issues.

**Comment by tobihan** [comment] 2015-02-20 14:28
Currently also on Android and iOS, OpenGL is only used to scale up the
finished image. So if the fadings are slow on the native resolution, the
Raspberry Pi will likely be too slow for that game even with OpenGL,
unless other optimizations are done.

**Comment by ivan-mogilko** [comment] 2015-02-20 14:33
@jagiella, just a note: if you are going to work on OpenGL, please fork your work from from "develop-3.4.0" branch. This is a WIP version that has number of improvements to graphic settings and renderer interface.

**Comment by jagiella** [comment] 2015-02-20 18:22
Where exactly is the renderer located, which file(s)?

**Comment by ivan-mogilko** [comment] 2015-02-20 18:37
https://github.com/adventuregamestudio/ags/blob/develop-3.4.0/Engine/gfx/ali3dogl.cpp

**Comment by ivan-mogilko** [comment] 2015-02-24 09:09
So, I close this issue, because it is was about having X running, and is solved.
For other issues (like OpenGL renderer) please open another issue.

**Closed by ivan-mogilko** 2015-02-24 09:09 UTC
