### ISSUE TITLE
[Bug] AGS 3.6.0.21 interpreter cannot playback WAV files with 48000 Hz sample rate

### ISSUE THREAD

**Issue by vga-256** [adventuregamestudio/ags#1587] opened 2022-03-24 22:10 UTC
Unsure if this limitation exists for other versions of AGS, but I just noticed it running the new 3.6 beta. I successfully imported a MS WAV file with the following characteristics: mono, 32-bit, 48000 hz.

In the editor, the 'play' button plays back the sound correctly. If I run the game, the sound does not play back (nor is there an error to indicate it cannot be played back). Re-sampling the sound to 44100Hz eliminates the problem, and it plays back correctly at runtime.

If this is an inherent limitation with the interpreter, or SDL2, it would be useful to have a note in the official help file to indicate that files should be exported at a 44100 Hz sampling rate.

**Comment by ericoporto** [comment] 2022-03-24 22:41
Can you share the audio file? We use SDL_Sound for decoding, so it's reasonably easy to check what's going on.

**Comment by ivan-mogilko** [comment] 2022-03-24 23:31
48 kHz sounds play in 3.6.0, there has to be another factor that causes an issue.

**Comment by vga-256** [comment] 2022-03-25 04:00
[Here is the unplayable WAV at 48Khz](http://vga256.com/ags/389511__bbrocer__digital-alarm-loop.wav). [Here is the same file resampled at 44100](http://vga256.com/ags/389511__bbrocer__digital-alarm-loop-44100.wav).

It is entirely possible some other changes were made to the file structure when I re-exported it in Audacity, but re-sampling was the only change I made.

**Comment by ivan-mogilko** [comment] 2022-03-25 07:04
@vga-256 , the original file is encoded as 24-bit, SDL_sound does not support these atm, it supports 8,16,and 32 bit afaik.

**Comment by ericoporto** [comment] 2022-03-25 07:47
See https://github.com/icculus/SDL_sound/issues/28

Probably opening a similar bug there including the file could be enough so it's fixed to work with it.

**Comment by ivan-mogilko** [comment] 2022-03-25 09:06
> Probably opening a similar bug there including the file could be enough so it's fixed to work with it.

Strictly speaking it's not a bug, SDL sound does not support 24-bit pcm at all:
https://github.com/icculus/SDL_sound/blob/main/src/SDL_sound_wav.c#L658

**Comment by vga-256** [comment] 2022-03-25 13:42
Perfect. Thanks for digging into this. Some kind of note about this limitation, somewhere in the documentation, would be helpful for end-users.

**Comment by ivan-mogilko** [comment] 2022-03-25 17:35
Opened a ticket in the manual: https://github.com/adventuregamestudio/ags-manual/issues/180

**Comment by ericoporto** [comment] 2022-03-25 22:27
So SDL_Sound just got a new release tag and we can use it and be happy.

SDL_sound appears to go for wav files that could have samples mapped to primitive types (char, short, int and float). It's generally easy to create a function to adapt 24bit to the MSBs of an int by following the SDL_mixer code and then actually add this feature in SDL sound though.

**Comment by ericoporto** [comment] 2022-03-27 17:11
24bit support added! https://github.com/icculus/SDL_sound/issues/31

I will soon submit a PR to update SDL sound, just waiting to see if something more happens there today (there are other fixes too!)

**Comment by ivan-mogilko** [comment] 2022-03-31 17:47
> 24bit support added! https://github.com/icculus/SDL_sound/issues/31

It still does not work with the file that vga256 posted, tried the latest windows build made on server.

**Comment by ivan-mogilko** [comment] 2022-03-31 18:09
So, now after sdl sound update (#1589) the library supports 24-bit pcms, but AGS cannot handle them correctly, so guess that makes it a AGS bug.

**Comment by ericoporto** [comment] 2022-03-31 19:14
@ivan-mogilko  did you build playsound_simple (an example in the SDL_sound source) and it worked for you? It may be somewhere in MojoAL if it works in playsound_simple but not in ags.

**Comment by ivan-mogilko** [comment] 2022-03-31 19:30
It's in ags, it has to do extra resampling, because there's no direct match between 32-bit integer data and openal's formats.

**Comment by ivan-mogilko** [comment] 2022-03-31 20:26
Ok, i think it's fixed in ags now: 8d77e5385254e70c9e9a0b3f7fcbbf928cbbd42c

**Closed** 2022-03-31 20:28 UTC
Labels: type: bug, context: audio, backend: sdl2
