### ISSUE TITLE
Red Hot Overdrive crashes a bit after starting a race with a script error

### ISSUE THREAD

**Issue by i30817** [adventuregamestudio/ags#1606] opened 2022-04-07 21:26 UTC
**Describe the bug**
The title, the script error is:
```

Starting game
An error has occurred. Please contact the game author for support, as this is likely to be an error in game logic or script and not a bug in AGS engine.
(ACI version 3.6.0.12)

in "room1.asc", line 468
from "room1.asc", line 5238

Error: Error running function 'repeatedly_execute_always':
Error: Null pointer referenced


***** ENGINE HAS SHUTDOWN

```
This might be a pure script error. From some experimentation the error appears to occur from pressing both the arrow up and the arrow left in the first curve at max speed. Like if a speed vector was being multiplied too much or something.

**AGS Version**

```
ags --version
Adventure Game Studio v3.6 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2021 others
ACI version 3.6.0.12


```

**Game**
The actual game:
https://www.adventuregamestudio.co.uk/site/games/game/1832-red-hot-overdrive/

**To Reproduce**
1. start game
2. Click on new game
3. Click on start race
4. Click on 'Baby'
5. Press up during the race until the curve, then press left.
6. See error

**Expected behavior**
Not sure. This probably shouldn't have crashed since it is listed on the ags contest winners page, so presumably it worked at one time... or maybe all the contest judges just passed on it and nominated it as default for 'not adventure game'.

**Desktop (please complete the following information):**
 - OS: `Linux sleipnir 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ericoporto** [comment] 2022-04-07 23:48
I can reproduce in AGS 3.6.0.22, here's the log right before the crash:
[ags_rho.zip](https://github.com/adventuregamestudio/ags/files/8447470/ags_rho.zip)
 
Right before the crash I can see a line like this:
```
Game : (room:1)[R 467] AudioClip.Play: no channels available to interrupt PRI:25 TYPE:3
```

Assuming the managed objects being disposed is just a consequence of the engine closing after that line, I don't know what it means exactly, but my guess is it fails to play an audio clip for some reason and maybe this returns a null audio channel that will then cause a failure right after?

**Comment by ivan-mogilko** [comment] 2022-04-08 04:03
This seem to work in release-3.5.0, but is broken in release-3.5.1.

**Comment by ivan-mogilko** [comment] 2022-04-08 17:25
Found what is happening; this started after b954ad324b6d0bc6b981419093c53062fc11f1f5

Prior to this engine did not make an attempt to restrict the requested channel's number to the real allocated channels count, so it could be anything. This could lead to crashes too, hence the fix (b954ad324b6d0bc6b981419093c53062fc11f1f5).
Problem is, there's a extra channel at the MAXCHANNELS index, which is normally used for music crossfading, and this game's sound luckily landed on that channel, and played.

**Comment by ivan-mogilko** [comment] 2022-04-08 19:43
@i30817 probably fixed, 86564e983572b4ffb3cd12b00c116ae91c6fcbe4 in master, and 64c60361a37b634b979e5a409ec080d418e6a23b in release-3.5.1.

**Comment by i30817** [comment] 2022-04-08 22:22
Fixed, assuming the other crash mentioned doesn't occur in some other game.

**Comment by ivan-mogilko** [comment] 2022-04-09 00:08
The crash should not occur, i think, because it still caps at the real channel limit.

**Closed** 2022-04-09 00:07 UTC
Labels: type: bug, context: audio

**Comment by i30817** [comment] 2022-04-09 01:07
BTW @ivan-mogilko , i found this bug reported messing around the scummvm tracker:

https://bugs.scummvm.org/ticket/12998

I've not seen it myself but that's probably because i haven't played in a while, and the scummvm ags is not totally equivalent to upstream because they cherry pick commits, but still.
