### ISSUE TITLE
AGS4: Documentation for building the Engine : Can't reproduce steps to create SDL_Sound

### ISSUE THREAD

**Issue by fernewelten** [adventuregamestudio/ags#1442] opened 2021-10-30 16:15 UTC
**Describe the bug**
I'm trying to follow the instructions in file `ags/Windows/README.md` to compile the Engine for Windows 32bit.
I can't reproduce the steps:
* I've downloaded SDL2 libraries from archive `SDL2-devel-2.0.16-VC.zip` as instructed in line 42, 
* I've downloaded and unpacked the sound source archive `997e90562b35.tar.gz` as instructed in line 58.
* So I open a VS developer prompt and `cd` into the source archive (the directory where CMakeLists.txt is located) and `cmake .`. This is how I interpret the first part of line 60 (quoted below), or am I supposed to do something fundamentally different here? 
> After you downloaded the source this way or another, use CMake to build MSVS solution from their provided CMakeList.txt, […]
* The cmake run fails with the following error:
```
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Files named `SDL2Config.cmake` or `sdl2-config.cmake` aren't provided anywhere in the archives that I've downloaded so far. So I can't make them available to `cmake`. 

Some step seems to be missing here. What am I supposed to do to get `cmake` to run successfully?

**Comment by fernewelten** [comment] 2021-10-31 01:01
So here's what I did to get at the built library `SDL_sound.lib`. 
The bold parts were unexpected for me.
This, or a shortened version, might help expand the instructions in file `ags/Windows/README.md` a little.

* Download and unpack SDL_sound-da0cecd33a39a16a84fb860e538e76e270589167.tar.gz 
* In the Windows Explorer, open the unpacked folder
* Within this unpacked folder, create the subfolders
	* include
	* lib
	* MSVC
* __Open the file `CMakeLists.txt` in the unpacked folder and insert a `#` at the start of line 32;__ it should now read:
> #find_package(SDL2 REQUIRED)
* Open a Visual Studio command shell (click on the Start button, start entering on the keyboard "Developer Command Prompt for VS" until it finds the command, hit "Enter")
* Within the command shell:
	* Enter the unpacked folder (using `cd`)
	* `cd MSVC`
	* `cmake .. -G "Visual Studio 14 2015"` 
	* The resulting console output should end with "-- Build files have been written to: [...]/MSVC"
* In the Windows Explorer, check that the subfolder MSVC now contains, amongst others, the solution file `SDL_sound.sln`
* Open Visual Studio. Open the solution `SDL_sound.sln` above (menu File>Open>Project/Solution...)
* In the Solution Explorer pane, select the following Lines, respectively, and for each such line, make the Modifications below:
	* Lines
		* playsound
		* playsound_simple
		* SDL2_sound
		* SDL2_sound_static
	* Modifications:
		* Open the properties by hitting alt-Return; a popup "Property pages" will open
		* Navigate to Configuration Properties | C/C++ | Code Generation. Set Runtime Library to `Multi-threaded Debug (/MTd)`
		* Navigate to Linker | Input, select the "v" icon at the end of the line "Additional dependencies", and choose "<Edit...>". A popup will open.
		* At the end of the entries, on a separate line, add the location (full path) where "x86/SDL2.lib" is
		* Below on a separate line, add the location (full path) where "x86/SDL2main.lib" is
		* Close the popup by clicking "OK"
		* Close the "Property pages" popup by clicking "OK"
	* Build the project by hitting CTRL-SHIFT-B on the keyboard. The project should compile without errors.
	* Open a Windows Explorer and 
		* Go to the `MSVC` subfolder of the unpacked folder, and from there to its subfolder that corresponds to the Solution Configuration (which is the first editable field in the Visual Studio toolbar, probably "Debug")
		* This folder should now contain the file "SDL2_sound-static.lib"
		* Copy this to the subfolder `lib` of the unpacked folder, above
		* __Rename this copy to "SDL_sound.lib"__
		* Go to the `src` folder of the unpacked folder.
		* Copy all the files that have the suffix ".h" to the subfolder "include" of the unpacked folder.
	* Now the folder "include" is the include folder of the SDL_SOUND project and the folder "lib" is the library folder of the SDL_SOUND project; the locations of both those folders will be needed below.

**Comment by fernewelten** [comment] 2021-11-07 17:45
So here are the include and lib files that I derived by the process above; they can perhaps complete the pre-compiled library files that Windows/README.md, line 77 refers to.

[lib_sdl_sound.zip](https://github.com/adventuregamestudio/ags/files/7492784/lib_sdl_sound.zip)

**Comment by ivan-mogilko** [comment] 2021-11-07 18:05
Sorry, I was not able to respond to this yet. We have a pre-compiled libraries attached to 3.6.0 github releases, the archive is called "WinDevDependenciesVS.zip", for instance here's one from the recent release: https://github.com/adventuregamestudio/ags/releases/download/v.3.6.0.10/WinDevDependenciesVS.zip

**Comment by ericoporto** [comment] 2022-01-26 17:45
@fernewelten were you able to build? Did the above link from @ivan-mogilko helped you?

**Comment by ivan-mogilko** [comment] 2022-01-26 17:49
I still forgot to update the prebuilt libs link in the windows/readme. But I am not certain how to link, as it is attached to every release. Do you have any ideas?

**Comment by ericoporto** [comment] 2022-01-26 17:53
I would do exactly as you said. Once 3.6.0 is not in pre-release state I think we can do as stated in GitHub docs here: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases , so a https://github.com/adventuregamestudio/ags/releases/download/latest/WinDevDependenciesVS.zip would work once the latest release is not a pre-release (from what I understand for how latest works)

**Comment by ivan-mogilko** [comment] 2022-01-26 17:55
Also, this reminds me, I tried to build SDL_sound using cmake recently, and it failed, because it could not find something in SDL directory. So I ended up setting up MSVS solution by hand again. But I was using SDL 2.0.14, which may be outdated now.

**Comment by ericoporto** [comment] 2022-01-26 18:06
> I ended up setting up MSVS solution for SDL_sound by hand

You could probably try to upstream those in SDL_sound. 

But regarding SDL2 they need to provide a sdl2-config.cmake along the VC stuff (the prebuilt windows lib and dll). I have some cmake stuff I want to fix there, I will try to find time for that. 

On our end, I thought I had added everything in the WinDevDependenciesVS.zip, if something is missing, please tell me so I can add.

**Comment by fernewelten** [comment] 2022-01-26 22:30
> @fernewelten were you able to build?

The lengthy process above solved my problem at hand, and it ended with usable libraries, so I didn't take it further. https://github.com/adventuregamestudio/ags/issues/1442#issuecomment-955616577 But IIRC I looked at the  instructions for AGS 3.6 and found them much more fleshed out than those for AGS4. They simply hadn't made their way into AGS4 yet, so I didn't notice that they existed.

Trouble is, I don't usually look into AGS 3.6 at all. The compiler is in AGS4, so when I work on the compiler, I'm exclusively in AGS4. On the other hand, when I code jam games and have to rely on a rock-stable version, then I'm in AGS 3.5, latest stable version. The 3.6 strain falls through the cracks for me, sort of.

**Comment by ivan-mogilko** [comment] 2022-01-26 23:00
> But IIRC I looked at the instructions for AGS 3.6 and found them much more fleshed out than those for AGS4. They simply hadn't made their way into AGS4 yet, so I didn't notice that they existed.

Perhaps this was a while ago; I double checked and they are synced now. AGS 4 should be built practically same way as 3.6.0, the differences are only in the editor/engine code.

**Comment by ivan-mogilko** [comment] 2022-04-29 16:38
Is this issue resolved? If not, what would be required to resolve it?

**Comment by fernewelten** [comment] 2022-04-29 17:55
Well, I've got my libraries, having used the process in https://github.com/adventuregamestudio/ags/issues/1442#issuecomment-955616577 . So for me, the issue is resolved.

**Comment by ivan-mogilko** [comment] 2022-04-29 18:20
So, from what I understand SDL_sound needs some tweaks to build on Windows, and if it's still the case then we should rather explain this in the readme.

**Comment by ericoporto** [comment] 2022-04-29 18:39
This was asked in SDL sound directly: https://github.com/icculus/SDL_sound/issues/30

The issue hasn't been solved upstream yet: https://github.com/libsdl-org/SDL/issues/5373

**Comment by ericoporto** [comment] 2022-09-11 18:19
SDL2 has fixed the upstream issue and added the necessary `SDL2Config.cmake` in their VC releases, they even added in some already released version of the library retroactively.

**Comment by ivan-mogilko** [comment] 2023-06-04 12:09
Finally I made myself to recheck everything, and confirmed that it's possible to use cmake with SDL_sound using updated SDL2 source packages. Updated readme in release-3.6.0 like this: ed5660c64a24802e9985ad0947c0e4c5f2d56d3c

Will pick to other branches too soon.

Will close this now.

**Closed by ivan-mogilko** 2023-06-04 12:09 UTC
Labels: ags 4, ags3, context: project

**Comment by ivan-mogilko** [comment] 2023-06-04 12:11
@ericoporto by the way, I noticed that SDL2_Sound is producing an output sdl2_sound for linux etc, and sdl2_sound-static for Windows. AGS is still requires it to be called sdl_sound.lib. Do you think it's okay to change? Perhaps this may help if linux distros would have sdl2_sound as a package (maybe some already do?).

**Comment by ericoporto** [comment] 2023-06-04 12:39
@ivan-mogilko sorry, I don't understand what you want to change but if you change something that breaks the CI I can fix later.

**Comment by ivan-mogilko** [comment] 2023-06-04 13:33
> @ivan-mogilko sorry, I don't understand what you want to change 

I was thinking to change the input name which is required in our MSVS project "sdl_sound.lib" to "sdl2_sound.lib" (or even "sdl2_sound-static.lib", which is the default target name that cmake-generated solution creates).

Other ports seem to be fine as they have `-lSDL2_sound` linker flag already.

**Comment by ericoporto** [comment] 2023-06-04 15:50
I adjusted for the default name and removed the renaming step in #2024
