### ISSUE TITLE
Audiofiles: Add Rightclick > reload from source

### ISSUE THREAD

**Issue by selmiak** [adventuregamestudio/ags#565] opened 2018-12-30 21:39 UTC
just like for sprites.

**Comment by ivan-mogilko** [comment] 2018-12-30 21:52
Normally audio files should reload automatically (into the AudioCache) without this command, but perhaps there are circumstances when they don't reload in time.

**Comment by ivan-mogilko** [comment] 2019-09-25 20:03
#778 is the duplicate of this, but they already added result of investigation there, so I will close this one and keep #778.

**Closed by ivan-mogilko** 2019-09-25 20:03 UTC
Labels: editor, suggestion
