### ISSUE TITLE
ags crashes on startup when trying to play "A Tale of Two Kingdoms" when built with gcc 6.2

### ISSUE THREAD

**Issue by berolinux** [adventuregamestudio/ags#366] opened 2016-10-14 22:45 UTC
Trying to run
www.adventuregamestudio.co.uk/site/games/game/905/
in ags (3.4.0.12 tag) on Linux x86_64 results in a crash on startup.

$ ags ATOTK.exe
Adventure Game Studio v3.4 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2016 others
ACI version 3.4.0.12

Initializing allegro
Reading configuration
Looking for game data file
Game data file: /home/bero/abf/twokingdoms/BUILD/twokingdoms/ATOTK.exe

Game data version: 32
Requested engine version: 2.7.2.0
Setting up window
Initializing TTF renderer
Initializing mouse: number of buttons reported is 3
Checking memory
ci_find_file: cannot change to directory: Compiled
ci_find_file: cannot change to directory: Compiled
Initializing keyboard
Install timer
Initialize sound drivers
Trying digital driver ID: 'Auto' (0xffffffff), MIDI driver ID: 'Auto' (0xffffffff)
Installed digital driver ID: 'ALSA' (0x414c5341), MIDI driver ID: 'AMID' (0x414d4944)
Install exit handler
Initialize path finder library
Load game data
Game data version: 32
Requested engine version: 2.7.2.0
Game GUI version: 115
A Tale of Two Kingdoms
Checking for disk space
Initializing resolution settings
Game native resolution: 320 x 200 (16 bit)
Device display resolution: 2560 x 1440
Game settings: windowed = no, screen def: max, screen size: 0 x 0, match device ratio: yes, game scale: max_round
Using graphics factory: DX5
Created graphics driver: Allegro/DX5
Supported gfx modes (16-bit): 
        640x480;640x480;640x480;640x480;640x480;720x400;720x480;720x480;
        720x576;800x600;800x600;800x600;800x600;832x624;1024x768;1024x768;
        1024x768;1152x864;1280x720;1280x720;1280x720;1280x800;1280x960;1280x1024;
        1280x1024;1440x900;1600x1200;1680x1050;1920x1080;1920x1080;1920x1080;1920x1200;
        2560x1440;
Supported gfx modes (15-bit): 
        640x480;640x480;640x480;640x480;640x480;720x400;720x480;720x480;
        720x576;800x600;800x600;800x600;800x600;832x624;1024x768;1024x768;
        1024x768;1152x864;1280x720;1280x720;1280x720;1280x800;1280x960;1280x1024;
        1280x1024;1440x900;1600x1200;1680x1050;1920x1080;1920x1080;1920x1080;1920x1200;
        2560x1440;
Requested gfx filter: StdScale
Using gfx filter: StdScale
Switching to graphics mode
Attempting to find nearest supported resolution for screen size 2560 x 1440 (16-bit) fullscreen
Attempt to switch gfx mode to 2560 x 1440 (16-bit) fullscreen; game frame: 2240 x 1400
Succeeded. Using gfx mode 2560 x 1440 (16-bit) fullscreen
        filter dest (160, 20, 2399, 1419 : 2240 x 1400), render dest (160, 20, 2399, 1419 : 2240 x 1400)
Preparing graphics mode screen
Initializing colour conversion
Mouse control: on, base: 1.000000, speed: 1.000000
Check for preload image
Initialize sprites
Set up screen
Initialize game settings
Cannot open translation: default.tra
Prepare to start game
Mouse confined: (160,20)-(2399,1419) (2240x1400)
Audio is processed on the main thread
Checking replay status
Engine initialization complete
Starting game
Shutting down Allegro due to signal #11
Segmentation fault (core dumped)

**Comment by ivan-mogilko** [comment] 2016-10-15 00:49
I could not reproduce this (running on Ubuntu 14.04 LTS).
Does it crash immediately for you, or after you do something (like switching to particular game screen)?

**Comment by berolinux** [comment] 2016-10-15 01:52
Crashes immediately on startup. Not even an info screen or anything.
Other games work (mostly) fine, so it's unlikely to be a problem with my build.

I'm on OpenMandriva Cooker (latest versions of just about everything).

**Comment by berolinux** [comment] 2016-10-15 09:08
"ltrace ags ATOTK.exe" ends in

[pid 11298] strlen("Chirp chirp! Tweet? Cheeep!")                        = 27
[pid 11298] memcpy(0x11e6440, "Chirp chirp! Tweet? Cheeep!\0", 28)       = 0x11e6440
[pid 11298] strlen("!")                                                  = 1
[pid 11298] memcpy(0x124fe00, "!\0", 2)                                  = 0x124fe00
[pid 11298] sprintf("on_event$", "%s$", "on_event")                      = 9
[pid 11298] --- SIGSEGV (Segmentation fault) ---

before the crash handler sets in

**Comment by ivan-mogilko** [comment] 2016-10-15 12:25
This lets to know the approximate location of crash; it is either **ccInstance::CallScriptFunction** or **ccInstance::GetSymbolAddress**.

**Comment by berolinux** [comment] 2016-10-15 15:59
Looking at it a bit, on git master, this happens in the last block of ReadDialogs(), lines 342 and up.

The if(newlen == 0xCAFEBEEF) is never run even when the magic value is hit. gcc 6.2 throws it out, but does enter the if statement if I change it to if(static_cast<uint32_t>(newlen) == 0xCAFEBEEF).
My guess is that without the cast, gcc 6.2 throws it out because it sees a comparison of an unsigned (size_t) variable to a negative constant (0xCAFEBEEF)

The game still crashes on startup (but at a later point) then -- probably because of a similar new shortcut the compiler decides to take.

**Comment by ivan-mogilko** [comment] 2016-10-15 17:26
Oh, it is gcc6, I forgot to ask compiler version. We had some issues with it before, it seems to be more restrictive with conversions.

I have an Antergos Linux on virtual machine which I used to test gcc6 compilation before, I may check the warnings it gives.

**Comment by ivan-mogilko** [comment] 2016-10-15 17:34
BTW, another instance of CAFEBEEF is in "read_gui", although it uses GUIMAGIC macro there.

**Comment by berolinux** [comment] 2016-10-15 17:43
I've just tried building with CC=clang CXX=clang++ (clang 4.0 prerelease), getting the crash there too.
(current gcc and current clang both tend to optimize away anything that could be in any way undefined though...)

I'm not hitting the CAFEBEEF thing in read_gui -- that would trigger a quit(); but I'm getting a segfault.

**Comment by berolinux** [comment] 2016-10-15 17:45
The CAFEBEEF problem in ReadDialogs happens with clang too.

**Comment by berolinux** [comment] 2016-10-15 17:47
After fixing CAFEBEEF, the game starts up when built with clang. Will send a pull request for that.

Probably still makes sense to check why it doesn't work when built with gcc 6.2 even after fixing CAFEBEEF.

**Comment by rofl0r** [comment] 2016-10-15 18:34
> Probably still makes sense to check why it doesn't work when built with gcc 6.2 even after fixing CAFEBEEF.

uhm, yes. MOST probably.

**Comment by ivan-mogilko** [comment] 2016-10-15 18:45
I guess this CAFEBEEF problem was introduced in latest master branch in the process of code refactoring, but the problem you were having with "Two Kingdoms" is present at 3.4.0.12 tag too, so this is something different.

**Comment by berolinux** [comment] 2016-10-15 18:48
True, I moved to master when starting to debug the issue to make sure any fix I come up with could still be useful. Looks like the switch to master introduced an earlier crash on top of the one I saw earlier, and the old one is still happening.
Definitely also gcc 6.2 related though (as it goes away when building with clang).
I've also seem some chopped sound issues with the gcc 6.2 build that aren't there in the clang build.

**Comment by berolinux** [comment] 2016-10-15 18:56
Warning-wise, this looks potentially dangerous:

script/cc_instance.cpp: In member function ‘int ccInstance::Run(int32_t)’:
script/cc_instance.cpp:972:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
               address = (char*)reg1.IValue;
                                     ^~~~~~
script/cc_instance.cpp:1006:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
               address = (char*)reg1.IValue;
                                     ^~~~~~

IValue seems to be a 32-bit value taking a 64-bit pointer.

Other than that, nothing overly suspicious the compiler would warn about (possibly conflicting definitions of MAX_TIMERS (21 in Engine/ac/runtime_defines.h, 16 in allegro's internal/aintern.h) -- if the smaller one is used to allocate an array and the bigger one to iterate over it, that could be a mess).

**Comment by ivan-mogilko** [comment] 2016-10-15 19:06
The "IValue taking 64-bit pointer" is a known issue, but it comes from the fact that AGS engine plugin API was originally designed to pass pointers into functions that accepted 32-bit integers as generic parameters.
That was a long while ago when I was rewriting script interpreter to make it safer (and compatible with 64-bit systems); I tried to find some workarounds for this plugin problem but could not do anything good at that time.
Since there are other bad issues related to plugin API, my thought was that it is easier to scrap it, or at least dangerous parts of it, and replace with something new (existing plugins are either open-sourced with  free license, allowing to upgrade them, or old closed-source ones that only exist in Windows version).

**Comment by onitake** [comment] 2018-05-04 07:49
It might make sense to switch to smart pointers for object arguments, such as:
```c++
void Object_Close(std::shared_ptr<Object> obj) {
    // clears the reference, which also causes a destructor call
    obj.reset();
}
```
Or perhaps weak_ptr to avoid circular dependencies.
That would mandate C++ code, though. Not sure if this is reasonable or not.

Perhaps all objects could be made engine-managed, with plugin-controlled member fields instead...

**Comment by ivan-mogilko** [comment] 2018-05-04 08:14
@onitake , imho it's better to open a new issue discussing problems of plugin system and suggesting changes to it. Also, to be honest, I did understand your last sentence, that needs some elaboration.

It was not clear if original thread's problem was related to plugin API, that was mentioned only as an example of something suspicious in the code.
Perhaps it would first make sense to test how latest version of AGS works with gcc6 today.

**Comment by ivan-mogilko** [comment] 2018-05-04 08:27
This was not mentioned anywhere in this thread, so I think it's worth clarifying that original freeware version of "A Tale of Two Kingdoms" did not use any plugins.

**Comment by onitake** [comment] 2018-05-04 17:42
Sorry about that. I stumbled upon this thread while looking for an answer to a different problem related to the plugin API.
Please disregard my post - I fully agree that this isn't the right place to discuss architectural decisions.

**Comment by toojays** [comment] 2019-01-02 11:09
Possibly this was the same bug as #553?

**Comment by ivan-mogilko** [comment] 2019-01-02 12:07
@toojays , that could be... 

Unfortunately developers removed old ATOTK from the games database and download link now redirects to the commercial deluxe version. Unless someone has the old game to confirm this guess.

**Comment by ivan-mogilko** [comment] 2019-02-23 17:03
> Unfortunately developers removed old ATOTK from the games database and download link now redirects to the commercial deluxe version. Unless someone has the old game to confirm this guess.

Alright, considering this report is 2+ years old and that it is *pretty likely* the same problem, I will close it. If problem resurfaces please open a new one.

**Closed by ivan-mogilko** 2019-02-23 17:03 UTC
Labels: compiler: gcc6, system: linux

**Comment by rofl0r** [comment] 2019-02-25 14:08
> Unless someone has the old game to confirm this guess.

what a pain. i once wrote a script to mirror all ags downloads, but it worked only in some of the cases (347 total). i yesterday went through all my backup disks only to find ATOTK.exe is one of the files that weren't downloaded correctly (probably it was hosted externally).

anyway, if someone is willing to host those 347 saved games (or upload them to archive.org) i'll be sharing a download link to my archive.

**Comment by ivan-mogilko** [comment] 2019-02-25 15:54
@rofl0r, there was a AGSArchives website, now they are closing, but the games may be accessed using torrent: https://www.agsarchives.com/agsarchives.torrent

Related:
https://www.adventuregamestudio.co.uk/forums/index.php?topic=56578.0

**Comment by rofl0r** [comment] 2019-02-25 23:20
hmm, the tracker of that torrent seems offline. is it possible to modify it to use DHT and magnet instead of relying on agsarchive.com's tracker running ?

**Comment by ivan-mogilko** [comment] 2019-02-25 23:47
> hmm, the tracker of that torrent seems offline. is it possible to modify it to use DHT and magnet instead of relying on agsarchive.com's tracker running ?

I am not the person in charge there, I think you should ask Peder Johnsen.

**Comment by ivan-mogilko** [comment] 2019-02-26 17:46
@rofl0r I was able to download this game from torrent today; I provide this temp link only for testing purposes because tbh I don't know if it's okay to distribute now (knowing that developers prefered to remove it from database and enforce commercial-only release) :s

https://www.dropbox.com/s/ehyf8s4wj418uhw/twokingdoms.zip?dl=0

**Comment by rofl0r** [comment] 2019-03-01 03:16
there's also https://0x0.st/z-dK.zip (arj0n/01-Repacked-no installers/777/0905.A Tale of Two Kingdoms v1.2.zip) which matches the game number of OP

> don't know if it's okay to distribute now

certainly. if it was free once there's no way it can be purged from the internet.
