### ISSUE TITLE
AGS Executables are unable to quit properly

### ISSUE THREAD

**Issue by Dualnames1** [adventuregamestudio/ags#829] opened 2019-06-10 19:51 UTC
I've explained the issue with images on discord, but I can't be arsed to copy these here. I spent 2-3 hours trying to isolate the issue, also confirmed by catpunter, who I'm also assuming is on Windows. This wasn't present in 3.5.0-Beta 2 and back, this only came present after i went from 3.5.0-Beta 2 to 3.5.0 -Beta 4 (well, AGS 3.5.0 Beta 4, I'm not sure if that's the proper ennunciation).

So, the issue is, aside from the first execution of your compiled game exe, be it from debug through the editor, or from compiled, with the editor closed, it doesn't matter,ags executables right now, if they use QuitGame(0) will hang. The exe will not draw any excessive CPU usage or resource usage, but it will stay there inactive, unable to close. I think it closes after a long while 2-5 minutes. So there is some issue with disposing things.

**Comment by ivan-mogilko** [comment] 2019-06-10 21:32
This is strange because I cannot reproduce this.

Does this happen with any random game or it should have something specific in it?
Could you upload a compiled game that has this problem?

**Comment by Dualnames1** [comment] 2019-06-10 23:26
I'm on Windows 8. And yes of course! http://primordia-game.com/Files0/test.rar

**Comment by ivan-mogilko** [comment] 2019-06-12 20:58
I tested on Windows 7 and Windows 8 (virtual machine), windowed and fullscreen, with all 3 gfx driver options, and it still closes normally for me when I click on Quit.

**Comment by morganwillcock** [comment] 2019-06-16 22:18
@Dualnames1 is there any chance that you are running some ~~heavy-handed~~ feature-rich security software that might try to inject itself into running processes?

**Comment by ivan-mogilko** [comment] 2019-08-17 22:37
@Dualnames1 was there any resolution to this? Does this still happen with latest 3.5.0 betas?
Seeing as no one has reported similar problem after public beta releases, I tend to think this may be related to particular enviroment.

**Comment by Dualnames1** [comment] 2019-08-19 17:42
This is probably an issue on my side i guess.

**Comment by ivan-mogilko** [comment] 2022-05-02 22:36
Unclear situation, and nobody reported anything similar since, so closing.

**Closed by ivan-mogilko** 2022-05-02 22:36 UTC
Labels: type: bug, res: wontfix, system: windows
