### ISSUE TITLE
Game.StopAudio() does not remove queued audio

### ISSUE THREAD

**Issue by sonneveld** [adventuregamestudio/ags#857] opened 2019-07-01 09:36 UTC
From the documentation: "If there are any audio clips queued up with PlayQueued, they will also be cancelled."

Using Windows 10, AGS 3.5 beta5.

Test game: [audiotest-windows-20190701.zip](https://github.com/adventuregamestudio/ags/files/3344847/audiotest-windows-20190701.zip)

To test, select a short audio clip and .PlayQueue multiple times (with repeat style once). Then press Game.StopAudio in the lower left corner. It will stop the currently playing clip, then continue with the next queued one.

**Comment by ivan-mogilko** [comment] 2019-09-10 13:57
This is an interesting case, because it does not work like said in the manual from the very beginning since AGS 3.2.0 when function StopAudio was introduced.

For that reason, this is not a regression by either original mistake or wanted behavior (then the manual is wrong?). In any way, I suppose, if changed in the future versions original behavior should be kept for old games.

**Comment by ivan-mogilko** [comment] 2023-04-02 02:53
> I suggest updating the manual and later add a Game.StopAllAudio() or Game.AudioClearQueue()

I have doubts about extra function, because StopAudio assumes nothing is going to be played now, and then suddenly you may have more sounds playing without any command, just because some were queued.
In regards to queue, one nuance about PlayQueued function is that it may have unclear intent. It may be used both to strictly queue sounds or music, and to "schedule" them to play either now or bit later when any channel is free. These uses are separate by meaning. From this perspective of *intent*, StopAudio should stop only second cases (but that's technically impossible, as *intent* is not passed as a parameter).

**Comment by ivan-mogilko** [comment] 2023-04-08 16:02
Erm!

Not sure how I overlooked this, or did not mention last time I checked the code properly, but Game.StopAudio actually **does** at least **try** to remove sounds from queue:
https://github.com/adventuregamestudio/ags/blob/38d0dd3d7f0d6a4624d1f908f2e8d3c1abfee52a/Engine/ac/game.cpp#L178

I must test this properly and see what's going on there.

**Comment by ivan-mogilko** [comment] 2023-04-08 16:27
Sigh, alright, I found the mistake.

`remove_clips_of_type_from_queue` only tests if the queued clip's type exactly matches the function argument, but it does not account of SCR_NO_VALUE, which means "stop everything".

**Comment by ivan-mogilko** [comment] 2023-04-08 16:41
Fixed with 8d1751508b7f7d9925931144de1e3cb8ed1d2f51

**Closed by ivan-mogilko** 2023-04-08 16:41 UTC
Labels: type: bug, context: audio, context: script api
