### ISSUE TITLE
Occasional crash to desktop on Android & controls question. 

### ISSUE THREAD

**Issue by vile80r** [adventuregamestudio/ags#275] opened 2015-09-13 11:17 UTC
Apologies if this is not the right area to post this. I'm not a frequent user of GitHub and I DO have trouble navigating around.  

I recently got AGS for Android.  I'm running it on an Nvidia Shield Tablet.  I've been playing Resonance and I have to say,  it looks and plays fantastic.  You've done a great job with this port. The only issue I've encountered is at least once in a game play AGS will just close with no warning or message. Just straight to desktop but, it fires right back up when I open it and I continue to play. 

I was also wondering how I could change the controls, specifically,  the two-finger double tap for right clicking. It's a little strange to pull off to be honest and sometimes the object is too small to get 2 fingers on it. Right now I'm struggling to right click these tiny objects in Resonance. 

I'd prefer every mouse control to be able to be executed with a single finger or stylus. SCUMMVM has a very good control system that AGS should consider adopting. Its:

Tap + movement: Mouse movement
Tap without movement: Left mouse button click 
Tap held for >0.5s without movement: Right mouse button click
Tap held for >1s without movement: Middle mouse button click
Double Tap + movement: Drag and drop 

On devices supporting multitouch: 

Hold down one finger, tap with second: Right mouse button click 
Hold down two fingers, tap with third: Middle mouse button click

One last feature request is to have the screen shrink when the keyboard is toggled.  Currently the keyboard pops up and covers half the screen.  I'm unable to see what I'm typing.  So,  if the game window could compress in height in relation to the keyboard's space I think that would make a more seamless gameplaying environment. 

Thanks for taking a look.  Again,  excellent work on this. 

T

**Comment by sonneveld** [comment] 2015-09-13 11:39
Thank you for reporting your feature request.. first up, do you might logging separate issues for 
1) the crashing (possibly any hints to reproduce)
2) the touch controls suggestions
3) keyboard toggle/screen shrink?

Second up, not sure if anyone is currently working on android port. One of the things on my list todo after my holiday is to build android releases via the build server.  I think that's a good first step before I can start to look at these features.

**Comment by ericoporto** [comment] 2022-01-09 10:25
The idea of this issue is to do all three things? Like the crash I can tell I can't reproduce. :/

**Comment by ivan-mogilko** [comment] 2022-01-09 10:36
> The idea of this issue is to do all three things?

First of all, this should be separated into 3 tickets each for one problem. The crash is likely to not be relevant anymore, as we have a different backend and different java app.

Then, of course, it's not necessary to do this exactly as suggested.

In regards to controls, imho it's best to gather all the known suggestions and consider what is best. Personally, I don't have any opinion on them, as I don't play on Android often. But even if we follow scummvm control scheme, as proposed, it's best to first find out what they *currently* are, as this ticket was written in 2015, and some things could've changed since.

In regards to shrinking, this is something to think about, but I guess it's best to find (or even make) a good game example where you can reproduce the problem.

**Comment by ivan-mogilko** [comment] 2022-06-26 23:58
The issues of controls were split out into the two tickets: #1713 and #1716; closing this one as it was primarily about crashes, which were fixed with updated engine.

**Closed by ivan-mogilko** 2022-06-26 23:58 UTC
Labels: type: enhancement, system: android, res: in consideration
