### ISSUE TITLE
Broken MMM game on Linux

### ISSUE THREAD

**Issue by ffaf1** [adventuregamestudio/ags#2099] opened 2023-08-18 09:37 UTC
**Describe the bug**
Completing some MMM games on Linux is impossible.

**AGS Version**
HEAD (6244e20)

**Game**
[MMM Episode 3: Staubenarrest](https://www.maniac-mansion-mania.com/index.php/en/spiele/episoden/staffel-1/15-episode-3-stubenarrest.html), played with the above-mentioned version of the AGS engine.

**To Reproduce**
1. open door
2. try to walk downstairs
3. you cannot walk downstairs

**Expected behavior**
You walk downstairs, [like in this LP](https://youtu.be/NLhBcOSZe8U?t=318)

**Desktop (please complete the following information):**
 - Debian 12.1

**Comment by ivan-mogilko** [comment] 2023-08-18 09:47
This seem to be a duplicate of #663, if they used same room assets, including walkable masks etc. The details are in comments to 663 ticket, but in short, with the newer engine the character is restricted by walkable area 1 pixel lower than in the old engine, where it could go 1 extra pixel up, ending up on a trigger region.

As a temp workaround, in #663 I was able to go down by standing very close to stairs and clicking around; usually it takes few attempts. Could you try that?

**Comment by ffaf1** [comment] 2023-08-18 10:09
Workaround does indeed work, took me a dozen of tries.

I will close this as duplicate.

**Closed** 2023-08-18 10:09 UTC
