### ISSUE TITLE
Music file with the wrong extension

### ISSUE THREAD

**Issue by Crystal-Shard** [adventuregamestudio/ags#2250] opened 2023-12-05 20:36 UTC
**Describe the bug**
If a game includes a music file that's listed as the wrong type (e.g. it's an MP3 file with the wrong extension, and the Game.agf file lists it as type OGG) then in AGS 3.3 it would play anyway (even if it's a renamed MIDI file!), and in the current version it will not.

**AGS Version**
3.6.0

**Game**
ATOTK

**To Reproduce**
1. Take an MP3 file.
2. Rename it to OGG.
3. Note how music players (e.g. VLC) have no problem playing this.
4. Import it into an AGS game.
5. Note how this music doesn't play.

**Expected behavior**
At the least, I'd expect a warning in the log file if the game attempts to play music and can't.
But really, I'd say storing music type in game.agf is not necessary, because music files are stored as binary in the VOX or EXE file and when opening one it's easy to find out what type it actually is; I think both Allegro and SDL have a generic PlayMusic function that figures out the format by itself.

**Desktop (please complete the following information):**
Windows 11

**Comment by ericoporto** [comment] 2023-12-05 21:40
I don't think wrong file format should work at all, and it's best to fail this stuff in the Editor than wait it to error at runtime in the Engine later.

**Comment by Crystal-Shard** [comment] 2023-12-05 21:53
I agree that the editor should pick this up, but it is possible for it to trigger only at runtime, so the runtime should also deal with it (e.g. by logging a warning).

**Comment by ivan-mogilko** [comment] 2023-12-06 05:40
The game package may be created by a separate tool, the music file may be placed in the game dir too, so we cannot fully rely on the Editor in this regard.

**Comment by ericoporto** [comment] 2023-12-06 06:50
The problem is the failure of a wrong file format is unpredictable, SDL_sound for example is not using Xiph, it's using stb_vorbis, which you can read the code (and the issues) and see it has lots of assumptions on the file and can fail due to malformed files.

**Comment by ivan-mogilko** [comment] 2023-12-06 07:20
The question is then, is it possible to detect a format type by reading a file header. If it's possible, then at least it should be possible to treat is as that type regardless of an extension.

If the errors occur because the particular format itself has mistakes, and library does not know how to handle that, that's a separate case, because it will have same result if the extension is correct.

**Comment by ivan-mogilko** [comment] 2023-12-06 11:52
I was speaking of a sound format itself. Often formats have a signature in the header that tells what data format to expect.

> I still feel if something like this is done you want the failure to happen at compile time or asset import (or both) in the Editor, so you can fix the file. Having this happen later at runtime may be uncaught and only noticed after release, it's better things are consistent.

One does not prevent another. There may be both a check in the Editor, and handling this in the engine.
Like I mentioned, the game package is not guaranteed to be compiled inside the Editor too.

**Comment by ivan-mogilko** [comment] 2023-12-07 06:19
First of all, in my opinion, the title of this issue is misleading, because it is not about music being in a "wrong format", but file having a wrong extension. 

Second, I tried to reproduce the problem, and could not, at least with a randomly chosen MP3 file. I did as told:
- use AGS 3.6.0.
- get a random MP3 file.
- rename to OGG.
- import into AGS. Notice how the clip is tagged as "OGG".
- play it in the game.
- music still plays for me.

@Crystal-Shard could you double check what happens, and if you still have this issue, then is it possible to upload the music file for investigation?

---

Now, in regards to the Editor/Engine behavior. Here's to summarize the situation.

Current AGS behavior is this:

1. When the audio is imported, it is assigned a "audio type" value. This "audio type" is taken out of the hardcoded list of constants called AudioClipFileType ([see here](https://github.com/adventuregamestudio/ags/blob/master/Editor/AGS.Types/Enums/AudioClipFileType.cs)).
This "file type" is selected simply by *matching the extension*. Editor makes no effort to find out what the file contains.
The "file type" property is saved both in the project, and written into the compiled game data (so it's available for the engine to read).

2. When the engine is ordered to play an audio clip, it refers to this "audio type" property, and uses it as a hint for the sound decoder implementation.
But here's where the old and new engine behavior differ.

3. The Allegro-based engine (pre-3.6.0) had separate decoding libs, and chose which to call depending on this property. It's not impossible that the underlying libraries could do their own format check and make further decoder selection (I did not investigate this too far, but this may be done if interesting).

4. The SDL-based engine (3.6.0 and on) converts this property back to an extension "hint" and passes this hint on.
*However* it does not use this generated hint right away, but instead it *gets the file extensions again* and if extension is present, then uses this extension. If the extension is not present (quite an unlikely case in AGS games...) - *only then* it uses the hint generated from the clip's property. This makes the clip's property practically useless in 99.99% cases. [See the code here](https://github.com/adventuregamestudio/ags/blob/7fdda099bc0e3b6dff3bca9c7d7dae50f927fc50/Engine/media/audio/sound.cpp#L135-L136).
In any case, the extension hint (whether a real file extension, or a hint from clip's property) is finally passed into the SDL2_sound library. There it's used in the library's own decoder selection. This selection works like this:
    * First it searches for any decoder that can recognize this extension. When a decoder is found, it tries to open the stream. If decoder failed to do so, it *continues searching*.
    * If there's no decoder knowing this extension, OR if decoders which *know this extension have failed*, then it will basically try every other decoder in the list.
    * In other words, SDL2_sound *always* tries every other decoder if the decoder for extension have failed.

5. When I tested the above case under debugger, this is what happens for me in 3.6.0:
    * Given the "ogg" hint, SDL2_sound tries to open the clip as OGG, using a vorbis decoder, and fails,
    * Proceeds trying all the other decoders, and succeeds opening the clip as MP3, using MP3 decoder.

---

So, the problem mentioned in this ticket has to be investigated further, since it is not clear to me what happenes in the particular case. From the looks of it the engine (or rather SDL2_Sound) currently DOES try other decoders if the first attempt failed.

Besides that, there are following questions on the Editor/Engine design.

1. The implementation of the "audio clip type" property. Personally I see 2 problems with it.
    Problem 1. Getting the "type" from extension, without checking for the actual format inside the file.
    Problem 2. Saving this value in the game data seems redundant, as it is always possible to repeat same action: either get the format from extension, or deduce format from the contents. Having this value saved in the clip properties, separated from the actual file, also may lead to inconsistencies (desync between data) if the game data is compiled by separate tools, or other means. In the end, at the runtime the engine may have the actual file in one format and this property telling another. IMO it would be better if engine would get the format same way as Editor does (whatever that method is: by extension or by checking format header, or in a combined way if one does not work reliably).

2. The question of whether Editor should test the file's actual format and issue an error or warning if the extension does not match this format.

3. The question of how strict the engine should be when trying to open a media asset. To put it simply: should it fail if the selection by extension failed, or should it try decoders until one succeeds (or all fail). I believe that this rule should be uniform for all media opened from files: sound, video, image, and so on.

In regards to the answer on q3, I've already stated my personal opinion in previous comments (that is: try everything), but I guess there may be alternative opinions, so long as there are valid reasons behind them. In any case, I think this decision should affect all media assets.

If we choose for engine to be "strict", then we'll have to somehow deal with the current SDL2_sound behavior, where it proceeds checking all decoders. Maybe this can be configured, if not then there may be workarounds for this.

**Comment by ericoporto** [comment] 2023-12-12 16:32
A good chunk of the crashing on invalid data and safety issues that existed on stb_vorbis in SDL_Sound have been patched recently so what I said is probably not an issue anymore. I still need to upgrade our SDL_Sound with a recent version with these improvements, will make a PR for it.

**Comment by ivan-mogilko** [comment] 2023-12-12 16:40
@Crystal-Shard , sorry for the nudge, but could you double check this issue, and possibly provide a music file that lets to reproduce this? As I mentioned in the above big comment, I was not able to reproduce the problem, as engine tries the file with other existing decoders if the one run by extension failed.

**Comment by Crystal-Shard** [comment] 2023-12-13 13:56
Sorry, I don't have a lot of time this month. You can close this issue if you want.
________________________________

**Comment by ivan-mogilko** [comment] 2023-12-13 15:36
> Sorry, I don't have a lot of time this month. You can close this issue if you want.

I may keep this open and return to this later if more details I known. If there's an actual regression related to playing some files, then it's good to get to the bottom of it.

**Comment by ericoporto** [comment] 2024-01-17 12:12
@Crystal-Shard hey, reminder if you can find a little time to retest this and provide the music file. :)

**Comment by ivan-mogilko** [comment] 2024-02-02 13:04
I will close this as not reproducible.
@Crystal-Shard , if you still have this problem, feel free to post here, or open a new one, but also please give more details about the failing sound file (which file, how is it played in game, etc).

**Closed by ivan-mogilko** 2024-02-02 13:04 UTC
Labels: type: bug, context: audio
