### ISSUE TITLE
Castle Agony (Steam) - "Craft" button not working

### ISSUE THREAD

**Issue by tag2015** [adventuregamestudio/ags#2146] opened 2023-09-22 16:39 UTC
**Describe the bug**
The "Craft" button in Castle Agony's GUI does not open the relative window.
Crafting is required even to complete the tutorial, so the game is unusable.

**AGS Version**
3.6.1.8

**Game**
[Steam link](https://store.steampowered.com/app/827830/Castle_Agony/)

**To Reproduce**
Just start the game

**Desktop (please complete the following information):**
Win10

**Comment by ivan-mogilko** [comment] 2023-09-26 19:41
I found that this is caused by changing in commit dcec61ba9825be21a0d2009a73b2af24df6a912d
Apparently the game is making some button invisible when you hover over "Crafting", and that resets its "mouse over" state. But i haven't yet understood the logical connection.

**Comment by ivan-mogilko** [comment] 2023-09-26 20:37
Ah, alright. So, for an unknown reason this game toggles `bCraft` button's visibility on and off repeatedly each game frame.
Since that commit the mouse-over flag is reset when the button gets hidden, but it is not getting updated soon enough after it gets visible again.
This is probably related to the order in which the mouse reaction is handled compared to scripts.

**Comment by ivan-mogilko** [comment] 2023-09-26 21:09
So, this is my mistake, not backwards compatibility issue, I did one "fix" wrong so it resulted in another potential issue.

Fixed in master branch with: fc336554a25bb763f721fb1a694a09771ad09b07
and in release-3.6.0: cc247845762e12e924e36e0922149d3b862bbcce

**Comment by tag2015** [comment] 2023-09-28 17:12
Confirmed working, thanks!

**Closed** 2023-09-28 17:21 UTC
Labels: type: bug, context: input, context: game logic
