### ISSUE TITLE
3.5 performance regression: 100% CPU usage

### ISSUE THREAD

**Issue by rofl0r** [adventuregamestudio/ags#771] opened 2019-05-17 00:02 UTC
when loading Gemini Rue DEMO.exe with 3.4.3.1, the title screen consumes about 33% CPU, whereas 3.5.x (from ags3 branch) consumes 100%.

**Comment by ivan-mogilko** [comment] 2019-05-17 00:05
This may be duplicate for #715

**Comment by ivan-mogilko** [comment] 2019-05-17 09:29
Right, so, this started after f2ab428a596c67d950f2aed5fbd335f6ccc72e3f.
Note that on Windows you must also include c6d1601615b6dd8936a6db50861baa4bda279fc6 otherwise engine won't compile

**Comment by rofl0r** [comment] 2019-05-17 15:03
good find. i suppose reversing that commit would be an appropriate fix.

**Comment by sonneveld** [comment] 2019-05-30 00:41
This should be fixed in `ags3` now if you'd like to test it.  Still waiting on PR to update the 3.5.0 release branch.

**Comment by sonneveld** [comment] 2019-05-30 00:42
Closing because duplicate of https://github.com/adventuregamestudio/ags/issues/715

**Closed by sonneveld** 2019-05-30 00:42 UTC
Labels: ags3, bug
