### ISSUE TITLE
Walk animation keeps going after character arrived at destination

### ISSUE THREAD

**Issue by ericoporto** [adventuregamestudio/ags#935] opened 2019-10-01 17:30 UTC
![walkinplace](https://github.com/adventuregamestudio/ags/assets/2244442/6f5288bf-c679-4da6-a52c-136155e6017c)

Observed by Francisco in higher resolution games, when character walks all the way from right to left in some of his rooms, with movement linked to animation, once the character has arrived at destination, the animation still goes for a few frames before stopping. Not sure if relevant but he also reported using 1:2 mask resolution. He also noted he has observed the glitch before at AGS 3.4.

**Comment by ivan-mogilko** [comment] 2019-10-01 17:36
Francisco's gif: https://cdn.discordapp.com/attachments/221048075207180288/628636698913538049/walkinplace.gif

**Comment by ivan-mogilko** [comment] 2020-09-27 12:25
Not sure if relevant, but there's a confirmed bug when on-going animation may reset to frame 0 and play again as soon as character stops: https://github.com/adventuregamestudio/ags/issues/1123

**Comment by ivan-mogilko** [comment] 2023-08-30 19:24
By the way, I did a fix where a character was stuck in either a "walking" state or "between" states for a short while. I wonder if this is related somehow:

1084cf5207cf3e05af6e6b8eeb3a3345ffbe13bc

**Comment by ivan-mogilko** [comment] 2023-09-22 15:22
@AlanDrake do you know if we are allowed to attach the test game from Franscisco, the one that you sent to me, as a test case which reproduces 100%?

I wonder if it will still reproduce if we replace game gfx with placeholders, as this likely is not related to sprites.

**Comment by ivan-mogilko** [comment] 2023-09-22 16:01
This is for the record, because there has to be a reproducible test case in the ticket.

**Comment by ivan-mogilko** [comment] 2023-09-22 16:18
So, testing this under debugger, what happens in the code is this.

The algorithm in question is `do_movelist_move` function:
https://github.com/adventuregamestudio/ags/blob/f4bd80df1d7b487fd6ff1d69636659ab67b2ecea/Engine/main/update.cpp#L64
Specifically, what happens when the character finished walking along one axis, but did not finish walking along another axis. For instance, it reached X destination, but not Y:
https://github.com/adventuregamestudio/ags/blob/f4bd80df1d7b487fd6ff1d69636659ab67b2ecea/Engine/main/update.cpp#L73-L76

The the engine does the following:
1. Sets flag "x done", locking x position (won't be updated further);
2. Tries to "hack" the Y destination, by moving it closer to the current position. Right, moving the *destination*, not the character. This hack is only 1-3 pixels, so if the distance is bigger, then the character will still not finish walking.
3. If Y pos is still not at the destination, then increments `onpart` and waits for the next frame to repeat the process.

Now, there are few nuances in this:
1. This "destination hack" is not saved, meaning next time the destination is far again, and engine repeats same exact fix.
2. Since `onpart` only advances the y pos by a fraction of a pixel, it takes many frames for Y pos to actually move a single pixel closer to the destination.
3. If there's also "movement linking to animation", then this update is done not each frame, but once in N frames (depending on the animation speed, frame delays etc).

This makes the process longer, and this visible effect happens.
And yes, because of the hack, it also means that the character may end up on a slightly wrong Y pos.
Possibly same may happen in the inverse case (X becomes Y) if walking is done along almost vertical line.

The reason for the coordinate mismatch is likely a relatively low precision of fixed-point values, compared to e.g. floats.

**Comment by ivan-mogilko** [comment] 2023-09-22 16:28
So, my guess is that there are 2 solutions:

1. Using float math, as it's much more accurate, and will likely make X/Y relation precise enough. Then presumably the destination mistake will never be large, possible 1-2 pixels tops, and this hack may be replaced with a simple "jump" to dest.
2. If not p1, then invent something to make final Y step faster.

**Comment by ivan-mogilko** [comment] 2023-09-22 16:36
For p2: for example, adding following code in this function reduces the "walking on the same spot" considerably:
```
  // Update target in case it was hacked in any of the above clauses
  cmls->pos[cmls->onstage + 1] = ((targetx & 0xffff) << 16) | (targety & 0xffff);
```

**Comment by AlanDrake** [comment] 2023-09-22 16:45
Well, p1 is already done, so it could be backported to 3.6 I guess.

**Comment by ivan-mogilko** [comment] 2023-09-22 21:20
The small fix posted above solves the issue.
But i also want to investigate porting floats solution, as I also wonder if that may fix #1879.

Besides that, it was interesting to examine this code, as it contains old variants of logic in comments. I think it's worth to take it out and make a combined "history of changes" above the function, for convenience.

Specifically noticed this piece of code:
https://github.com/adventuregamestudio/ags/blob/f4bd80df1d7b487fd6ff1d69636659ab67b2ecea/Engine/main/update.cpp#L132-L136
I immediately remembered this ticket: #663
may be worth checking that out too.

**Comment by ivan-mogilko** [comment] 2023-09-23 21:15
> Well, p1 is already done, so it could be backported to 3.6 I guess.

I've been thinking about porting floats, and then I recalled there already had been a backwards compatibility issue when we replaced a pathfinder. Which means that maybe it's best to stick with the existing math in the compat. branch.
I guess we could have both float and fixed point stored in that struct depending on game format, but that might increase complications, so i'd leave that as a backup idea. I guess if someone would want to support that, they would better use 2 different MoveList structs, and 2 variants of `do_movelist_move` function, one for fp math and another for float math.

**Comment by ivan-mogilko** [comment] 2023-09-23 21:35
In terms of possible move corrections, there are 2 approaches: 1) accept that the final destination is inaccurate and just stop where we are; or 2) walk part or all of the remaining destination along 1 axis. Current code does the latter, but it walks too slow, because the velocity angle is away from the axis in question. This is what is causing this few moments of animation "in place".

I came to another fix idea, which hopefully will be compatible. Since the problem is that the speed along that other axis is not big enough, my idea is to create a "extra step" state in that function, which would in that case "turn the velocity vector", so to speak, and make character move remaining distance fullspeed along the remaining axis.

In terms of code, this looks roughly like this:
```
yps = cmls->fromy + (int)(fixtof(ypermove)*(float)cmls->onpart) + // main move
          (int)(fixtof(fin_ymove)*(float)fin_onpart); // final move
```
in other words, the current position would consist of 2 parts: the regular move part, and the "final" move part which is added only in case of this unfortunate situation (otherwise it stays zero).

I noticed that in high-resolution games the behavior is almost indistinguishable from simply "jumping" to the destination, as the diff is too small relatively to the screen.

However, when testing the low-res game (320x200), i found that the jump will actually be quite noticeable. While the fix I am trying here visibly looks like an extra step in a new direction.

So, I would really like to know opinion on this looks *visually*.

Here's the test game I compiled:
https://www.dropbox.com/scl/fi/r52c6zy1odiabeuwnautu/walk-problem-test.zip?rlkey=3e9yfgeze8dujeeb1n4ov6d3u&dl=0
and a project, in case necessary:
https://www.dropbox.com/scl/fi/4qngs3cdm58601stbb8qx/walk-problem-project.zip?rlkey=89529mos1kyc3cft7h70u9p4u&dl=0

I scripted this game to make a walks between very particular coordinates that illustrate this problem case: this is done by pressing Space button.
But if you walk manually around, you might also get similar cases. I think that the trick is to choose long distances and directions where move along one of the axes is very small.

---

If you think that above looks bad, I guess a remaining option would be to increase the allowed destination mistake for hi-res games. Because the 2-3 pixels of allowed diff is only suitable for the low-res.

**Comment by ericoporto** [comment] 2023-09-23 21:53
Ideally, if there is a path to the destination, it would be nice if the ending position is exactly the destination, because people usually script a check using equality (`player.x == DEST_X && player.y == DEST_Y`). If coordinates were float, maybe people would be using some epslon for the tolerance.

> So, I would really like to know opinion on this looks visually.

Only in the specific case with pressing space I can note that the player kinda "slides in", maybe because you mentioned, but any other clicking around I didn't noticed.

**Comment by fernewelten** [comment] 2023-09-23 23:01
> Ideally, if there is a path to the destination, it would be nice if the ending position is exactly the destination, because people usually script a check using equality (`player.x == DEST_X && player.y == DEST_Y`)

A bigger problem of inexact stopping would be that the end point of the walk might happen to be at the very edge of a walkable area. When an automatically scaled character“overshoots” for their last step and moves *off* the area, and the edge of this area would have the character at, e.g., 20 % size, then this overshooting makes the character suddenly become five times as big as it should be.  

When inexact walking makes the character stop *outside* a region instead of *on* the region, then the event “Steps onto” won't trigger.

**Comment by ivan-mogilko** [comment] 2023-09-23 23:10
@ericoporto 
> Btw, if this changes the final position, while it's good for newly created games, this can still impact the older ones

This is true, but I might also keep the destination fixup for the old games. The old fix and this new solution do not conflict with each other. In case of a destination fix, the "final step" will simply be shorter.

**Comment by ivan-mogilko** [comment] 2023-09-23 23:17
In regards to ags4, now when I understand all this code better, it seems all or most of these fixups are not necessary at all, and if it's true, then this whole function may be stripped to a minimal code.

**Closed** 2023-09-25 16:53 UTC
Labels: type: bug, context: game logic, context: pathfinding
