### ISSUE TITLE
Quest for Glory II VGA cheat keys no longer work in current AGS interpreter

### ISSUE THREAD

**Issue by dreammaster** [adventuregamestudio/ags#1249] opened 2021-04-10 02:14 UTC
Quest for Glory II VGA has two cheat keys as described on this page: https://tcrf.net/Quest_for_Glory_II:_Trial_by_Fire_%282008%29
However, the cheat keys don't work on the current AGS 3.5 interpreter, though it does on the 3.3 interpreter.

I had a ScummVM bug report, so investigated the problem and tracked it down to the GUI_GetVisible method in engine/ac/gui.cpp. In AGS 3.3 the method was using: if (guis[tehgui->id].on != 0)
In 3.5, however, it calls the GUIMain::IsVisible() method, which uses the new _flags bitset.

The problem seems to be that the game, for both the F10 and F4 keys, does a check to see if the toolbar at the top of the screen is visible, the intention being to not open the dialogs if they are. In 3.5, however, the toolbar (gui index 2) has kGUIMain_Visible and kGUIMain_Concealed. So the cheat code always treats the toolbar as always being visible, and won't open. I've already done a game-specific workaround in ScummVM, but I thought it worth reporting, in case it might cause problems for other older games, and there might be a cleaner, more generic way to fix it. Such as not creating concealed guis for 3.3 and earlier games.

**Comment by ivan-mogilko** [comment] 2021-04-10 02:36
I guess proper is to test what corresponds to the property value, that is strictly Visible flag. This might be a mistake made during GUI refactoring. But I need to double check this.

**Comment by ivan-mogilko** [comment] 2021-04-10 02:43
Well, iirc it should be possible to make double test: IsVisible && !IsConcealed.

But yes, I probably changed GUI_GetVisible to act strictly as a property getter, while older "on" variable had several meanings including automated hiding of iconbar (this is what Concealed means).

**Comment by ivan-mogilko** [comment] 2021-04-10 19:44
@dreammaster 
so, to clarify situation. This "on" variable in older engine, it was not a boolean, but had 3 states:

-1 - locked off
0 - visibility off
+1 - visibility on

The regular guis used only 0 and 1, switched by toggling GUI.Visible property or more ancient InterfaceOn/InterfaceOff pair of functions.
However, there was a "popup at y" type gui, which used all three in following way:
- when it was shown it set it to +1
- when it was hidden it set it to 0
- but when InterfaceOff function was called it set it to -1, thus locking itself from showing

It's interesting to also note that setting GUI.Visible property to off won't actually lock that popup gui, but just hide it until mouse moves back and forth again. In a sense, this popup gui was adjusting its own Visible property.<br>
Unfortunately, after InterfaceOn/Off functions were deprecated in favor of GUI.Visible property, it seems that new script API did not have direct equivalent to InterfaceOn/Off at all, which increased confusion. In other words, with new API it was _impossible to actually disable popup gui_.

Now, to what I did when refactoring the project.

First, this "on" variable behavior seemed complicated, so I replaced it with 2 flags instead:
- Visible - tells whether Visible property is on or off
- Concealed - tells whether "popup at y" gui locked itself
This alone seem to be equivalent to old "on" variable.

But then I also changed the logic of Visible property, because I thought it's logical that if user set Visible to off then gui should not show up at all. So instead of letting this popup gui changing Visible property, I made it set this special internal "Concealed" flag when it hid itself.

Also on a side note, while testing AGS 2.72 I found that it on contrary has a bug which was coincidently fixed in AGS 3.5.0: in 2.72 if you disable popup gui with InterfaceOff, GUI_GetVisible will still return 1 although gui would not show up. It returns 0 only in 3.5.0.

**Comment by ivan-mogilko** [comment] 2021-04-10 20:05
@dreammaster 
so, to clarify situation. This "on" variable in older engine, it was not a boolean, but had 3 states:

-1 - locked off
0 - visibility off
+1 - visibility on

The regular guis used only 0 and 1, switched by toggling GUI.Visible property or more ancient InterfaceOn/InterfaceOff pair of functions.
However, there was a "Popup At Y" type gui, which had special behavior and used all three in following way:
- when it was shown by moving mouse to the screen's top - it set it to +1
- when it was hidden by moving mouse away - it set it to 0
- but when GUI.Visible was set to false, or InterfaceOff function was called - this popup gui would set "on" it to -1, thus locking itself from popping up

In a sense, this popup gui was adjusting its own Visible property, unless user set it to false from script explicitly.

Now, to what I did when refactoring the project.

First, this "on" variable behavior seemed complicated and bug prone, so I replaced it with 2 flags instead:
- Visible - tells whether Visible property is on or off
- Concealed - tells whether "popup at y" gui locked itself
This alone seem to be equivalent to old "on" variable.

But then I also changed the logic of Visible property getter, because I thought it's logical that if user set Visible to "on" or "off" then it should return "on" or "off" accordingly to this setting. It is *this* change that is causing the problem now (not introduction of flags per se).

Also on a side note, while testing AGS 2.72 I found that it on contrary has a bug which was coincidently fixed in AGS 3.5.0: in 2.72 if you disable popup gui with InterfaceOff, GUI_GetVisible will always return 1 (although gui will not become visible). This is because of incorrect condition involving "on" variable...

**Comment by ivan-mogilko** [comment] 2021-04-10 21:48
I pushed a commit that returns old behavior for pre-3.5.0 games: b07ddea6d2a16cd4e77e687675853dbc914b15ca

But while investigating this I found another logical mistake in 3.5.0 (which may or not break something), so there's another commit that fixes it: ce3e8355e5e20b59a6fa73546669cb25b3084a2f

Additionally renamed one legacy constant just to make its meaning clear: b31631d749e8a8ce7dd06d47e87e0193d8fb8871

**Comment by dreammaster** [comment] 2021-04-14 04:29
Thanks for letting me know. It'll be cleaner for me to apply these to ScummVM then rely on just the specific workarounds

**Closed** 2021-04-14 20:28 UTC
Labels: ags3, context: bw-compat, type: bug

**Comment by lwcorp** [comment] 2021-04-28 23:22
Wow, where were you back in https://www.adventuregamestudio.co.uk/forums/index.php?topic=57956? ;-)

For the record, can you link to the ScummVM issue which dealt with this?

**Comment by dreammaster** [comment] 2021-04-29 01:07
Sure :). The bug URL is: https://bugs.scummvm.org/ticket/12338

**Comment by lwcorp** [comment] 2021-04-29 05:49
Thanks but I meant their Github issue about it (which their ticket doesn't mention).

**Comment by ivan-mogilko** [comment] 2021-04-29 08:07
@lwcorp I am not scummvm dev, but from the looks of it their [github repository](https://github.com/scummvm/scummvm/) does not have "issues" module enabled.

Speaking of the bug, this was a regression in AGS 3.5.0, fixed now in AGS 3.5.1 (currently in beta stage).

Unfortunately I missed your question on forum back in 2020, imo it's better to report similar problems in the issue tracker or "engine development" forum section.

**Comment by lwcorp** [comment] 2021-04-29 10:48
> @lwcorp I am not scummvm dev, but from the looks of it their [github repository](https://github.com/scummvm/scummvm/) does not have "issues" module enabled.

What about the Pull requests? Is it found there?

**Comment by ivan-mogilko** [comment] 2021-04-29 11:37
I'm not sure which exactly information do you seek, but the last comment to their ticket mentions 2 commit hashes, they may be used to find exact commits which did the fix to their repository: 
https://github.com/scummvm/scummvm/commit/879a06fabfb48f70ed5693ee1ceb8f88fa683c3e
https://github.com/scummvm/scummvm/commit/5650217194a7fc836ae8f3fe42cb72e27b6db9a0

I don't see many [pull requests related to ags](https://github.com/scummvm/scummvm/pulls?q=is%3Apr+is%3Aclosed+%22ags%22+), and none related to this bug, which probably means they push directly to the master.

**Comment by dreammaster** [comment] 2021-04-30 00:45
Yes, Most work on AGS is directly done with commits to master. Pull requests have only been necessary for non-team members. As for issues, we have our own bug tracker at bugs.scummvm.org
