### ISSUE TITLE
Incorrect ScriptValueType for attributes used in same script as object function

### ISSUE THREAD

**Issue by monkey0506** [adventuregamestudio/ags#414] opened 2017-06-23 06:34 UTC
As described in the [wiki entry on attributes](http://www.adventuregamestudio.co.uk/wiki/Keyword:_attribute), user scripts can use `attribute`s in the same way that the `builtin` types do by defining a member function (possibly using an extender function) with the appropriate name for the accessor (`get_Attribute` or `geti_ArrayAttribute`) and/or mutator (`set_Attribute` or `seti_ArrayAttribute`). However, the wiki is slightly out of date as to the runtime error message that is raised **if you access a user-defined attribute in the same script where the accessor/mutator is defined**. The current error message is slightly more revealing as to the underlying problem.

    ---------------------------
    Adventure Game Studio
    ---------------------------
    An internal error has occurred. Please note down the following information.
    If the problem persists, post the details on the AGS Technical Forum.
    (ACI version 3.4.1.5)
    
    Error: Error running function 'game_start':
    Error: invalid pointer type for object function call: 10
    
    
    ---------------------------
    OK   
    ---------------------------

*NOTE:  If using an extender method, the extender must have an import, even if the import is immediately above the extender definition in the script file, otherwise the resultant error is an unresolved import.*

This error message (raised at [Engine/script/cc_instance.cpp:1168](../blob/master/Engine/script/cc_instance.cpp#L1168)) indicates that the `attribute` itself is being interpreted as a `kScValDynamicObject` (even if using a primitive type like `int` as the `attribute` type), rather than a `kScValObjectFunction`.

I don't know how easy or difficult this may be to fix, and it's a **very** low-priority request, though it would be terribly useful if module writers could expose attributes to the end-user and also be able to take advantage of them directly (as opposed to littering their scripts with `inst.set_Attribute(inst.get_Attribute() + 1)` and the ilk.

**Comment by monkey0506** [comment] 2017-06-23 06:36
Clarification:  This **only** applies when accessing the `attribute` in the same script where the accessor/mutator is defined. The `attribute` can still be used properly in subsequent scripts, as with all prior versions of AGS (since 2.7).

**Comment by ivan-mogilko** [comment] 2017-06-23 09:55
One thing more I'd like to clarify, how exactly do you reproduce this? I recall I usually get "script link" errors when using imported attributes in same script, so it never gets to actually run the script.

**Comment by monkey0506** [comment] 2017-06-23 10:54
Sure.

    // SomeScript.asc (local definitions only, but the same applies with global definitions)
    
    struct Type
    {
      readonly import attribute int ConstantValue;
    };
    
    import int get_ConstantValue(this Type*); // this import must exist to avoid unresolved script link error (as noted in original report)
    
    int get_ConstantValue(this Type*)
    {
      return 42;
    }
    
    function game_start()
    {
      Type t;
      int value = t.ConstantValue; // error occurs HERE
    }

The same occurs if using a struct with a non-extender import, such as:

    struct Type
    {
      readonly import attribute int ConstantValue;
      protected import int get_ConstantValue();
    };

**Comment by ivan-mogilko** [comment] 2017-06-23 12:34
A small note:

> This error message (raised at Engine/script/cc_instance.cpp:1168) indicates that the attribute itself is being interpreted as a kScValDynamicObject (even if using a primitive type like int as the attribute type), rather than a kScValObjectFunction.

It requires kScValDynamicObject because the get/set function is a member of an object. It needs "this" pointer to send to the function, but the value stored in the register seem to be something else. Maybe the opcode arguments are messed up when this script is compiled.

**Comment by ivan-mogilko** [comment] 2018-06-13 09:52
Don't think this was ever fixed (unless I missed somehow), why is this closed?

**Comment by ivan-mogilko** [comment] 2021-01-31 18:33
This is fixed in a new compiler in ags4 branch.

**Closed by ivan-mogilko** 2021-01-31 18:33 UTC
Labels: context: script compiler, type: bug, what: editor
