### ISSUE TITLE
Duplicate string entries in Translation (TRA) file

### ISSUE THREAD

**Issue by vga-256** [adventuregamestudio/ags#1119] opened 2020-09-15 22:13 UTC
Description:
Occasionally, the editor will add duplicate entries of a string in the translation file, in two different parts of the file.
For example from German.TRA:
```
Line 19031: &1383 Alas, poor Desiree. A woman of infinite riches, of tastes most fancy. Well, where's all your money now?               
Line 19032: &1383 Ach, ärmste Desiree. Eine Frau mit unermesslichem Reichtum und mit exquisitem Geschmack. Und wo ist dein ganzes Geld jetzt?
```

Several weeks later into development, after compiling/updating German.TRA a few times, this new (duplicate) entry appeared:
```
Line 23023: &1383 Alas, poor Desiree. A woman of infinite riches, of tastes most fancy. Well, where's all your money now?

```

** AGS Version **
AGS Version 3.5.0.24

** Steps to Reproduce **

I can't seem to reproduce the problem as it seems to happen randomly. I've searched the source files several times to ensure the string only appeared once. The originating string appears in a room script:
```
function hSkull_AnyClick()
{
  cBill.SayEx("&1383 Alas, poor Desiree. A woman of infinite riches, of tastes most fancy. Well, where's all your money now?");
  cBill.SayEx("&1384 Come to think of it, that question might be worth answering.");
}
```
**Expected behavior**
The problem is that when two duplicate entries appear in the .TRA file, the engine seems to only use the _last_ entry as the basis for a translation. When a duplicate entry appears, there is no translated string available below it, so the string is rendered un-translated in the game.

**Desktop:**
 Windows 10

**Comment by AlanDrake** [comment] 2022-09-15 21:12
In this case, the duplicate is due the extra spaces added at the end of the line.

**Comment by AlanDrake** [comment] 2022-09-16 17:11
Closing this since it's a user error, though it's also a fault of the current format, which makes it hard to catch such cases.

**Closed by AlanDrake** 2022-09-16 17:11 UTC
Labels: type: bug, what: editor, res: needs testing, context: editor assets, context: translations

**Comment by ericoporto** [comment] 2022-09-16 20:49
> In this case, the duplicate is due to the extra spaces added at the end of the line.

At the end of which line where?

**Comment by AlanDrake** [comment] 2022-09-16 21:57
The very first quoted, I doubt vga would purposely add that many extra spaces at the end while pasting it here, so it's very likely they were from the translation file, and extra spaces are indeed cause for a duplication because they're recognized as different entries.
I don't like it very much but this is a weakness of the current format, there are no quote delimiters to avoid such mistakes when editing manually.

**Comment by ivan-mogilko** [comment] 2022-09-16 23:08
Sorry, but I also don't understand still, where do you have to add extra spaces, in script or TRS?
@vga-256 mentioned that he could not find exact steps to reproduce this, have you found them? If so, could you add exact steps please?

**Comment by ivan-mogilko** [comment] 2022-09-16 23:14
This needs a clarification.

*The cause of a problem is that there are two lines in **TRS** file which are different only in spaces in the end.*

I'm still not certain how did they both ended up there, were they added by a user, or they were added automatically by the editor (in which case there's a question whether the original script line contained them or not).

**Comment by AlanDrake** [comment] 2022-09-17 07:23
I don't see anything in the code that could cause extra spaces to be inserted, except maybe an unterminated string, that would force the user to edit the trs manually to clean up the mess.

Either the space was once in the original string and got removed, or it was added in the TRS. 
Note that Dialog style texts (eg: `player: lorem ipsum`) are always trimmed so will never produce trailing spaces.

As things stand we just don't have enough information to rule out a user error, or even a third party tool error. I'd also expect many more reports about duplicated lines if we had something really broken.
We really should move translations to a more solid format, like PO files, that would enable us to spot extra spaces with certainty and let users use mature third party tooling for translations.

**Comment by fernewelten** [comment] 2022-09-17 10:12
So this is a plausible course of events:

1. User requests a German translation file in the AGS Editor.
2. Editor generates `GERMAN.TRS` and populates it. At this point in time, the source line without the trailing spaces is populated as well.
3. User works with the German translation in some editor that does not visibly mark spaces. For instance, the very common Notepad++ doesn't show some kind of dot for each space by default.
4. At some point, user adds some trailing spaces to the source line by mistake. One way to do this “naturally” is by inserting a spurious line behind the source line that only contains some whitespace and then to “delete” the spurious line by backspacing over its first character. Bang, the content of the spurious line will be appended to the preceding line.
5. At a later point in time, the Editor is told to “Update” the translation files. The Editor notes that a line is in the program that is NOT in the TRS. Thus it writes a copy of the missing line to the end of the TRS file.
4. From the vantage point of the user, it looks as if there were “two copies” of “the same source line” in the TRS file and that the Engine was only paying attention to “the last line of them”. Actually however, the source lines are different by the trailing spaces, and the Engine only pays attention to “the last line” because it is that line that happens to be the one that matches the code exactly.

The situation is acerbated here by the fact that the lines of this project have a prominent, starting ampersand identifier. A user might be led to falsely __believe__ that lines are considered equal whose starting ampersand identifier is equal; but that is a red herring, of course.

@AlanDrake : 
> We really should move translations to a more solid format, like PO files

Second that.

**Comment by fernewelten** [comment] 2022-09-17 10:35
Also note, in this specific example, that the two lines form a context:
The original is: 
```
cBill.SayEx("&1383 Alas, poor Desiree. A woman of infinite riches, of tastes most fancy. Well, where's all your money now?");
cBill.SayEx("&1384 Come to think of it, that question might be worth answering.");
```

The system "re-generates" the first line near the end of the TRS file, which is the correct thing to do from a "programming" point of view. But it is a very bad thing from a translator viewpoint. Now the __second__ line of the text ends up in Line 19032, and the __first__ line, that forms the context, ends up more than a thousand lines later in Line 23023. 

When "new" lines are always added at the end, then those lines that haven't been translated yet might be easy to find by looking near the end of the .TRS file. That might be seen as an advantage. But now find the __context__ that these new lines have been embedded in. This context may be very important in languages such as German where it may well be the only hint to whether an "it" needs to be translated as masculine, feminine or neuter.

**Comment by ivan-mogilko** [comment] 2022-09-17 12:01
> We really should move translations to a more solid format, like PO files

I suggested to open a task ticket for this before, but at the moment there's only comments in other tickets, and a forum post.
These comments are referenced in this [ags4 milestone proposal](1298) - look for "Better translation system".

**Comment by ericoporto** [comment] 2022-09-17 13:05
From @fernewelten observation, it seems instead of full string identifier, it could be:

1. Ampersand number is used instead as identifier
2. If this isn't available, use strings, but trim before

**Comment by ivan-mogilko** [comment] 2022-09-17 13:08
> Ampersand number is used instead as identifier

The problem with number is usually that it's not descriptive, same as when you use numbers in the code.
