### ISSUE TITLE
Scripting: const arguments are useless

### ISSUE THREAD

**Issue by ghost** [adventuregamestudio/ags#632] opened 2019-02-15 14:14 UTC
AGS script supports "const" function arguments, but these are useless because the bug in complier prevents you from using them in any expression with regular variables.

For example:
<pre>
function f (const int a)
{
    int b = a; // compiler error: Type mismatch: cannot convert 'int' to 'int' (sic)
}
</pre>

**Comment by fernewelten** [comment] 2019-02-15 17:00
As far as I understand, "const" arguments have been introduced as a kludge to allow mingling String and string variables -- the one are modifiable, the other aren't, so the compiler must keep track on what can be modified. 

We also have "readonly" and "writeprotected" in the language, which BTW translate to the same exact same word in German, but are sligntly different. So far as I can see, "const" parameters correspond to "readonly" variables. So we probably need to write "readonly int  b = a" to make the example work.

I'll look into that.

**Comment by ivan-mogilko** [comment] 2019-02-15 17:24
There's an updated documentation being worked on here:
https://github.com/adventuregamestudio/ags-manual/

For instance, readonly and writeprotected are explained here:
https://github.com/adventuregamestudio/ags-manual/wiki/ScriptKeywords#readonly

**Comment by fernewelten** [comment] 2019-02-15 18:42
I've modified my comment above with more notes about what I was able to find out.

**Comment by ivan-mogilko** [comment] 2019-02-15 19:18
> I've modified my comment above with more notes about what I was able to find out.

Please don't do that after someone has already commented, this may make following replies look out of place, and make it difficult to understand what one should reply to.

**Comment by ivan-mogilko** [comment] 2019-02-15 19:53
Well, this seem to be a bigger topic than I expected, so not to rush things following is my preliminary opinion, only to start with something.

First of all, regarding readonly, AFAIK its main use-case is _struct member_ fields and _attributes_, where it means that the member field can be only read by external user, but not assigned to.

Is there a difference between *readonly* and *const* in regards to these?
Well, first of all, I am not sure if "const" would make sense with an attribute, because attribute is not a plain data field but a specific construct.
Secondly, some of the *readonly* fields in the built-in structs are not really const: they may be still modified inside the engine, but only read in script.
(E.g. see mouse.x and mouse.y)

On another hand, in terms of choosing between *readonly* and *const*, and deciding where to support them, IMHO I'd give *const* higher priority.
I would personally also vote for its implementation that would match C# *const* behavior, at least where it is allowed to be applied in AGS script, that is: const variables which may only be assigned during initalization and const function arguments which ensure that argument is never changed inside the function.

Reading the "string" examples that you've found I did not notice anything illogical, unless I miss something all examples of legal and illegal behavior are matching C#/C logic for const strings.
So I don't see any need to maintain "special" behavior for strings, they seem to be already in line with the expected behavior.

Finally, back to *readonly*, like I said previously there are cases where readonly may be necessary, but still there are also cases where its use seem to duplicate const. So, if everyone will be okay with my proposal above, then what remains is discuss where readonly should work.
BTW, in C# readonly fields can be initialized in constructors. AGS structs do not have constructors, which makes "readonly" useless in user structs, because they also don't support initializing variables in struct declaration. So if you have readonly member variable then you won't be able to init it at all.

**Comment by ivan-mogilko** [comment] 2021-01-31 23:45
UPDATE:

With the new ags4 compiler, the example posted in ticket still does not work, but error message is slightly different:

> Error: Cannot assign a type 'const int' value to a type 'int' variable

Which ofcourse still does not make sense considering what const type is.

**Comment by fernewelten** [comment] 2021-02-01 05:14
As concerns __struct__ attributes and variables, they currently cannot be `const`. 

But there's `readonly` and `writeprotected` (which is unfortunate for us Germans because we translate both with exactly the same word). 

* A `readonly` struct __variable__ cannot be changed. Behind-the-scenes, it's a normal memory space, only the compiler prevents anyone from writing to it.
* A `writeprotected` struct __variable__ can be changed within a function of the same struct, but not from the outside.
* A `readonly` struct __attribute__ doesn't have any associated setter function.
* No `writeonly` struct __attribute__ s AFAIK

__Non-struct__ variables can only be `readonly`, which means that they can't be changed after their initial assignment. Unfortunately, they aren't constants proper. Memory is still allocated for them, only the compiler prevents write access.

The only way to get proper constants at the moment is defining an `enum` for them. This makes for kludgy, non-straightforward code:

```
enum MainCompileTimeConstants
{
    number_of_knights = 7,
    max_health = 100,
    background_color = 17,
    candle_burning_rate = 8, // inches per hour
    …
}
```

I'd much rather have a `const` keyword that defines proper compile-time constants at least for `int`s and `float`s so that you can do:
```
const int number_of_knights = 7;
int knight_strength[number_of_knights];
```
This way of using `const` should work for `int`s and for `float`s.
```
const float pi = 3.141592654;
```

**Comment by ivan-mogilko** [comment] 2021-05-03 20:50
Related proposal: #1255

**Comment by ivan-mogilko** [comment] 2022-01-09 01:47
This is resolved by the new compiler. See #1255.

**Closed by ivan-mogilko** 2022-01-09 01:47 UTC
Labels: type: bug, what: editor, context: script compiler, res: in consideration
